apiVersion: v1
kind: ConfigMap
metadata:
  name: attic-config
  namespace: attic
data:
  config.toml: |
    # vim: ft=toml
    listen = "[::]:8080"
    allowed-hosts = ["attic.${CLUSTER_DOMAIN}"]
    api-endpoint = "https://attic.${CLUSTER_DOMAIN}/"
    max-nar-info-size = 1048576 # 1 MiB
    soft-delete-caches = false
    require-proof-of-possession = true

    [database]
    heartbeat = true

    [storage]
    type = "s3"
    region = "garage"
    bucket = "attic"
    endpoint = "https://garage.${CLUSTER_DOMAIN}"

    [chunking]
    nar-size-threshold = 65536 # 64 KiB or larger
    min-size = 16384  # 16 KiB
    avg-size = 65536  # 64 KiB
    max-size = 262144 # 256 KiB

    [compression]
    type = "zstd"

    [garbage-collection]
    interval = "12 hours"
    default-retention-period = "1 month"
