apiVersion: v1
kind: Secret
metadata:
    name: attic
    namespace: attic
stringData:
    token-hs256-secret-base64: ENC[AES256_GCM,data:xLFWu/h8UuAy/xZ58lDpMt+4a4xJu37QqQTSJ8KA9PMEmPR9cuyhESpW7z1Z2RXfPzTrx7Wjb/uM/eDTvJ4Cjx0VTJZzUPdR1dJV0GiVk8d6mqmBxu35QQ==,iv:GjnQ7itq9fVesWiyHg+o4P9yVb9XYSRVVgWb05UgZUU=,tag:cJIxbEbGVw6ueIfyX2hJig==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWNzU3NYVTgvaHJEL3hS
            dlJJaFAyemhsbjJoazQvUjJuU0ZvaDBKTG5vCnZJY0gxa2FhZGpvMEdOQ1R6S3FJ
            R3lNTFBpbEtDTFhRZjhpK01Hb0dEY1EKLS0tIGpMK2N0azl2emhsbXc1b3AzTGhs
            TXZybWFpNk1GalNDVE9pOVBLSHY0Vm8KqG+eBYlQtN5thnvMdlTAfJxC47U64oEi
            Vg8SCLW0H6CJq4LWmIojtltRoSRN9bDx0sbKFAoGipXYKTmgQfYuIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBeUVPMkZ4
            eHRzellWRjdGQndyNzJtek5BQXJkMHRjYnlCSU1JSHRtK0RnRwpQNEZkcmFCbmRJ
            K2dBZ3l0S1lzUVhvZklCbzZocE52VUdBTS82VlBkbmFBCi0tLSBRWDdyNm9mZ3kw
            WUt1Z0p2bXFyL0hNME81VUJxV0pOdmJ3aVEvQmp4YlhFCorlybKZPvenf7zLpm7Y
            MgtD40crERIWK3+2Flr0k9k06Zj/lzVE5KyTw8uNJMcqfVKvwFDXOt57bqtjEuit
            /Qo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBcGNubzRt
            Z1Rmend1Qy9DdU11SHNkVnIxQ2Z2bnI3bFlNTW00SXg2WUNkUgppc3BLUnBqamxx
            TGpISkhqcVlMUGNBUEFDNURwbzRCbmM5b3VlaTZpblpvCi0tLSBLcnRqRWRNbDc3
            YTdzUjQ2YmdpTzR6VXJ4VllERUZKRko4aVI2dlRPTXVRCkafBT6lzX9HH6QyN9CU
            Ik3awVO2aBIiWcjy/lJYUAMm3bXTb5mKiPJX1xl/jsCFq+ljF+sSzMkuxnL6sYdn
            HuQ=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T00:43:01Z"
    mac: ENC[AES256_GCM,data:+wix2hNg9sQgJHovTGU38cX6UZlbhCoaxbVB/d25k5BFzBhCqBBd9C3+zoq4tGL/HMR1E+GkVFQsttgF3mksqC+9295Nh5vEa+rwIX7YFtJ7xYd3pPXPQNDHGotDKXVWmLQvAK8CtC0qsgMUPvAiptCeNAUKVGVXtTarYBMmgb4=,iv:DREzqJl5va5VkfSoe5NCKjWbTd1l7FYfgOQGzW/9Icg=,tag:R0m2DSNA4v02uscwCALLjg==,type:str]
    pgp:
        - created_at: "2026-04-21T00:43:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAuRgePIjgBtfIQAAltLjkPgT3yedQeIk60EUXY0l2hT2a
            M4moVXblPWuWRLW3YO982+FsSInsFrdBsEzvLBSBtQXytCH7K15UB4RcfE/64RvW
            pNYPwvej+HIlpW69tY7bv/AqZ3i/InpZgKcnW86cmWtmQg70xDuchenwnYexlD+S
            KdKwhsGzOcYYwHrkYK2CCZaf0xwDuQ68dkhd8KIbDmYrmG/g10Wz1vy5F2njJVOp
            qNvhi32N4WJCzOoIbagRU+jCCAoq2arfKB4GZ5/OHlcjTWt8kvRrJFPAMOIrYAYz
            Y5bySb3GMyi8tjN9RGtMr4ETSb4oCfTcxRBfuVa8EyZMUaPVzrrdypBd4unWYob2
            9Vca8TBajgo9Age0kM45RRO0VqZhDqoJ4p59xNbYiPg5xhCA06dP/fTCz92K5wMJ
            C0uxbLbJf7tV5OSizt4Nf4NdsNQuBoixTCaqXFmCYwtelzNdJPK7OGuJ21ss9PE8
            fPyKYOMDXZC8EvcDaI/YlNZbLZi0OPKLLSri3DLFJv/6pNke8IX2AAzJreg6mAiL
            RMw54S30SFi/ApViHS+cYUmAKN9bNx611TTRT26CH0/qbg5ykCZbJW4KOl5W40rK
            TlFU5JRrLin7DZBGGd1wqL1BpnLWlzMLU7S61/3JjjzJAnPqxhbhAYwzArj6lpnS
            XgHBlMJVrrv54z1L5Fkc3t1MRdXXOrf4JYYnUythc2EMT199HoIVHwvqpx4NJ9ZU
            QNxvwERYkkMj9Uo1kdCuLXlW6Tc6zLf174JzTr/tDgWfCBlDGuGRU5bJrLh5tu4=
            =P7to
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.2
