# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: jwt-hmac
  namespace: attic
spec:
  length: 32
  allowRepeat: true
  noUpper: false
  encoding: base64
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: attic
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jwt-rsa
  namespace: attic
spec:
  commonName: attic
  secretName: jwt-rsa
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secrets
  namespace: attic
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: attic-secrets
  target:
    name: jwt-secrets
    template:
      engineVersion: v2
      data:
        ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: "{{ .hmac }}"
        ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64: "{{ .rsa | b64enc }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: jwt-hmac
      rewrite:
        - regexp:
            source: password
            target: hmac
  data:
    - secretKey: rsa
      remoteRef:
        key: jwt-rsa
        property: tls.key
