{
  inputs,
  lib,
  self,
  ...
}: {
  flake.nixosModules.base = {
    modulesPath,
    pkgs,
    config,
    ...
  }: {
    imports = [
      inputs.disko.nixosModules.disko
      self.diskoConfigurations.default

      (modulesPath + "/installer/scan/not-detected.nix")
      (modulesPath + "/profiles/qemu-guest.nix")

      inputs.sops-nix.nixosModules.sops
    ];

    sops = {
      # Should be auto-generated by CI
      defaultSopsFile = ./secrets.sops.yaml;
      age.sshKeyPaths = ["/etc/ssh/ssh_host_ed25519_key"];
    };

    services.openssh = {
      enable = true;
      authorizedKeysInHomedir = true;
      settings.PasswordAuthentication = false;
      settings.KbdInteractiveAuthentication = false;
    };

    sops.secrets."ssh/root/authorizedKeys" = {
      mode = "0400";
      owner = config.users.users.root.name;
      group = config.users.users.root.group;
      path = "${config.users.users.root.home}/.ssh/authorized_keys";
    };

    nix.settings = {
      experimental-features = ["nix-command" "flakes"];
    };
    nixpkgs.config.allowUnfree = true;

    boot.loader.grub = {
      efiSupport = true;
      efiInstallAsRemovable = true;
    };

    system.stateVersion = "25.11";
  };
}
