# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 2h
  timeout: 30m
  chart:
    spec:
      chart: loki
      version: 13.1.3
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    loki:
      # TODO: Enable when ingress supports service auth, not just user auth
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      limits_config:
        retention_period: 744h # 31 days
      querier:
        max_concurrent: 2
      compactor:
        working_directory: /var/loki/compactor
        retention_enabled: true
        delete_request_store: s3
        compaction_interval: 10m
        retention_delete_delay: 2h
        upload_parallelism: 2
      schemaConfig:
        configs:
          - from: "2023-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              period: 24h
              prefix: index_
      storage:
        bucketNames:
          chunks: loki-chunks
          admin: loki-admin
          ruler: loki-ruler
        s3:
          s3: http://garage.garage.svc.cluster.local:3900
          s3forcepathstyle: true
          region: garage
          insecure: true
          accessKeyId: $${S3_LOKI_ACCESS_KEY_ID}
          secretAccessKey: $${S3_LOKI_SECRET_ACCESS_KEY}

    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        storageClass: freenas-api-iscsi-csi
      resources:
        requests:
          cpu: 20m
          memory: 1Gi
        limits:
          memory: 2Gi
      extraArgs:
        - "-config.expand-env=true"
      extraEnv:
        - name: GOMEMLIMIT
          value: 1750MiB
        - name: S3_LOKI_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: garage-creds
              key: access_key_id
        - name: S3_LOKI_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: garage-creds
              key: secret_access_key

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0

    chunksCache:
      allocatedMemory: 512 # MB
      resources:
        requests:
          cpu: 50m
          memory: 615Mi # allocatedMemory * 1.2
        limits:
          memory: 615Mi # allocatedMemory * 1.2
    resultsCache:
      allocatedMemory: 128 # MB
      resources:
        requests:
          cpu: 50m
          memory: 154Mi # allocatedMemory * 1.2
        limits:
          memory: 154Mi # allocatedMemory * 1.2
    monitoring:
      serviceMonitor:
        labels:
          release: prometheus
    test:
      enabled: false
    gateway:
      nginxConfig:
        # Needed for CrowdSec to verify if Loki is ready
        serverSnippet: |-
          location = /ready {
            proxy_pass "http://loki.loki.svc.cluster.local:3100/ready";
          }
