apiVersion: key.garage.m.crossplane.io/v1alpha1
kind: Key
metadata:
  name: velero
  namespace: velero
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: garage
  forProvider:
    name: velero
  writeConnectionSecretToRef:
    name: garage-creds
---
apiVersion: bucket.garage.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: velero
  namespace: velero
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: garage
  forProvider:
    globalAlias: velero
---
apiVersion: bucket.garage.m.crossplane.io/v1alpha1
kind: Permission
metadata:
  name: velero
  namespace: velero
spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: garage
  forProvider:
    accessKeyIdRef:
      name: velero
    bucketIdRef:
      name: velero
    read: true
    write: true
