apiVersion: v1
kind: Secret
metadata:
    name: postfix-accounts-cf
    namespace: mailserver
stringData:
    postfix-accounts.cf: ENC[AES256_GCM,data:hXaHgIAjSs4FopYq0jmS+GiNAcEOncg/zW1SVJA6bsf9YWvYM7/jRozbSSfirbstrjNYFFPBZ1o3735swerwvoOzjBNKkyPwDfpq2fAoRWGKJR0Pe/L381M4pA/hmzHaEcnkDBbJJXRGQuVbbzDIbNT+oBgvD69IqDDPQFtLs7//FGa/Fa0saJT0f+9lRKKtpd0ayy3CumQAsnK6plFNAe6wDTs1YD/Qp3MXHOp3jWJ5HSlqzQsKPWEy7TzODAef/531Ap4LO/vZL/9qIrR/RULRjmsxx3DoJDOJUxVFSOeoLpWMZhV1efG+XaZBRYujj49czCFv+5HWOw0sTDtDBB0e3HN3GLwCgsV1xwApA82ZuQltWXsJFRyHwHcBENuH32KBDcgxhWe2fbIq8/0rRXQYnWpf5vKjjzBcnatixSHugKY5ZkQuc0UruxEKHgryMP6e1K8yZ0gFIUbBdon8bwEbJ777/Y2aElHhHeTgegPGQJuUuhQWkWHpohhurTwzqgAlf7DqHEvrgLivbpNIeaxuF5idUvPyc2wDXDXRT5F/RVaCq8kv00mauS3Q7kzSX+RC6JkfVKNnH/v5iv2ctsDd7k+nvMSa+FoqScjPoOKw3f9EdycI2LwCnTByAAO1tXOri2u2K8Ljm7KHI7sIO+60EaCjAeRdQ8OyQBDMtCR9rs7LDMulh1666mV82lbDdbiw/2Y4bkYft4ZUVP2K0EPODxuWlPY8j12pH2/Fq/zVDMTZC0Bl3sZEaImkKM3VLdoHGsxx19Ee3qIxtcdsUXhpIfFXRPBkhtSeQ7V/fayMVDKvbiIF8MDGXg+H1Uy1t7C9hEGOBNdYaFlsHW3QkX83XhA7xBrWp07U7AxVeOFXNJXVymEvAB55SoKr/qPgJJ0Wj6Slj0YTA/VVRhdf6shEEBI=,iv:oL2tQ9Zu4VV2xpiHuy3ThEAg9nNjtPgBou1NdenqCXI=,tag:oYU/Z+VRBm4LHGsn244qRQ==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQjU0MXB5UHlQdktUcjFj
            SVFNR200SS9wU20rbElrdjV6bXJuZUtUaHowCnpsRHFDcHRWZTMzQ1lEb3Z4a1Rt
            akx4THNvQzFZcGhJenhnT1JoTWhoYVUKLS0tIDgzZEtjdEV3eDBVdGkzUk44OG9a
            alFJVEZIL1BNNU9odkR0eFlOdzAzRncKvaZ88rdtx6Y8ntXYCGyC+EdegU8dFAEm
            of6RtgyCPKwehNkRzVDyDMQne0VN6Ei+Y/00T0/FdFeb/uUQAo84aA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBcnhib0JS
            WHBoZURrb1VsUWlPQTdpd2g0czBWNVllWFdZMUduU2hLMExhcQp1QUthcFNwcFN4
            YzNFVmxoVXFSQ1o5OUZtOFVibkU5bUZzdmpmQzkyTnpjCi0tLSByV2pNZFFCL2Ev
            cWVXT1gyZ3JucXIwTGF2RzdkNFZmUVRTeE1OeWZpSHNzCm4UaYqjOvbbj0BQfARf
            2a003UKYfCoNSyyYKQbHS8RykklTxFB6b0gQ8fq/fG57u2q3syxcCkYMKz/2BA/U
            hpU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBdEY5N2J3
            aTRHdUV3aGpjRW05RDdnTUpGRFZkdjI4VlF2TXdsZFNxNXhGdApKbFBlSzFrQmh6
            NFBwbC9wV0JCQUZwWXp1Q2xiT3RYNHNDOTdRVXhPUno0Ci0tLSBQWHR3OVFZZysv
            cFRLT05ubkwyT09HNEtVNEhkZ0tUOURsRitZaG82VDI4Copduqlnqa9EV883Daz/
            Fpj1D2Mc+Mdis/72QUKTg9IhfEP4gve8hVH23sJDImQEYfd0cWoYZyitBBWh2Cde
            GG4=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:xeztrC2ugoiGflTZJIPnaE6BkQEjDOd1n/4XF4oIsvjBB1nR9a+RPkzeERdglV7YML+nUdwtneNHG4lJ3JGDF5UpIFt6iux2rNJViD+0J9YtvVvl9Ja481N1NcXzVyl0h5+1Y2eSUSgzf9geAec3EuQvbg/i5e6Zh2ajT+TVw+M=,iv:SLSMX9Yz8RMMk4j98SbuOKrP6nif6UZF1Fk9M++pdbQ=,tag:7BaCJseKjVGWrV365avu2Q==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+LAgPAqISepTj5+CT4iIPfDi5XCExlmuO3ImL8ekWtLLB
            tv1bfkSgLWvdPXRs+RkGfmEhgMzVZNijmNKo/3QxelyaPqVdVVWtGNmgo97gdoNb
            /Bbiita8oPI+9MoRFjuC/Jie7w8djmB+0p3uNXAsTUgcUr6xC5Ygs5PNE0865U9P
            y6UtKZslR7V0ovjyo5r6eGVJ9v5WXpbSzyliJTDsmXSLfo4l715+Bn3RPUgHC6dm
            BIOgAaEpzrwwOgvYhgrcqtR0QW8KdtykLKK0dHTAcudzvv2EBY60OkLjD952v1Uw
            Iu/3X63p4qIK8KNwpmhelxu+QYXLWhfEyeInn2lCVSQVCGQy38bMSbI4pS9FqWUI
            VG+a3p9sKACP1D8B66YrPUODUJPOC43dudkes4SzwDLqRHmuymIgbneJQ7oNCpDV
            LAyWvOS+OX9oA0EwpPYISgRnk5KnevltbcJ1PwYAv583gT7cfiHw9Z7PmthGpQcv
            G6L4uh/QwLMCn4GREqSUGi8wPRSn4Pbaw7QN+2Yd3KiOJTI5UY2wrcbSqK2x5t2u
            wO3yZMHhsU++/+wknfyNCHkC8vEGactFmWVOnNLdHpno/J8O6s3yAH9hhi+wY8EN
            SoXndsfdL/edKXZe3N7fUIaIJwHsvHmyzHzoowPyNS36cb/JA0zeEVbVkVzGig7S
            XgFnK0iw9j8oG1Da6aK3xFz2uydbe8FNFfEE8HjE8bkZJV8tmohro/wcGq0w5sSu
            cXNHikDgPcSaMYWtCvzN872kaaxSnab9p1MJSvFoN+a6LLRjRgNlJRObLw3yTtI=
            =v+yn
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
