apiVersion: v1
kind: Secret
metadata:
    name: dkim-ed25519
    namespace: mailserver
stringData:
    cluster_domain.ed25519.private: ENC[AES256_GCM,data:9JkaT6rSpgpVg8bx6pmhBXWPBEMKuNAHpEQxbc1qqdd1XGCvYwdfahaPG2BL6egm+IqDGfSiAm9XSm1TTbzSb1cz4edVkysB+UXNgfHJqFtOpM1JJ0NpYQ==,iv:aZs/jNOkGQ6kSm2n68DPzd42gyyiEHopQ2DWWtm2tuk=,tag:f+4FnGPFnzL3i+vFspPvSg==,type:str]
    cluster_domain.ed25519.txt: ENC[AES256_GCM,data:bNFsuc1h0v77AbA72fRVr/MGvZTdIcMZiAwMZJgUDlBU2h8YavdEU/e9wLi0sDbhks9iKgxaJwTBcOiZhE+TGfwVqFxIU8nYYOYqyPaBAzmix3PhIu1d99zHmG0Pe5zxZ2Ftn3xMgw7YqKelWM8=,iv:RAHLfzBhT04XG6TXosyNPL2SlujsTz7h7j60BiJiN0w=,tag:aye9AFfWfnxvT66ZmZI4Gg==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUXVBZmZ4c2NtcWF3b056
            cERqcXRPUkZaVW1MU3U0OENKaVFBTTF6ekUwCllrbWJRYWtERFhsQ1h5ODZQUEVF
            TzJLT0pnOGhhcGppM2hWVVRLSksrS1EKLS0tIHdIbGxYTjhlUW5xNTVrNmJiL0hm
            V0YrVTZycVJFWWpiVlY5RGJUWDhvZ0kKwEV2LQUqb0ng5ENKnkwKupkApN/jSTW7
            2x37bNuET0pmt6LP2+5TmsFgfg+siB4Slec2JNHfoZ1b8ftsHoIw8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBL0dreUdY
            WUpRSldZQmJ6MGpwMDFHbWVpbXZDa0tBbk9VWVVYYlN5bE1Uawp6amlZSmtDZjFR
            dWExM0N1VG9OZXJDZks3VW1qOS82TGdka0pPYnNnY0JzCi0tLSBHV1pQU1ZwelZT
            K3NiczZjK1JZRWg1TENzNCtzejQvMmU0cXM5SzFzQS9rCsUiPL4lHAdHk+61E8RF
            HXg7IcxiFiL5mFPVMHIBCZyThJFs37AAyTTALy4BGmH8KlFwyugiR6FDZ3qdPCD9
            25o=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBeGpRNFlo
            WXhJcVEwMndxcVYzQ0pPcnlUcDdYelQ3ZzFUKzdrQ29vQmJMKwo0eHM2anYxSkJO
            dGJlQUxlbTJmaEZqOU0rakpFKzlFZjVlQnpzY3V2TkhZCi0tLSBtc2FCSDNxYVpH
            WnpIRHRhUXVMWGNXUndHdGRzUnVxZS9pb0g0dzNKeTBFCva6c3n+tRVwZJgFa2XT
            AXpqUQQr/csFYoiGlFqgOdnrG32V356GA+wl+kfuhtWAZBmz7sTHTiHFbW2QOhma
            cv4=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:J5J2Qm+GQhR+JW0hYTC9z40vxizNZegSmOEeE3VXurjDzcH2fc37WEyvb2RvHuHS7Azunmk+qVmyu8BctmemuDkAbWPhjOXZbvmM8iGOViD2OPxu09TsVyRj3ObhPoJl3WBewzSpDgfUrYf44LLcM/RQa/iTCrA6Sgp57jYpcUs=,iv:cGJbv7/4wo1gxH50kG4aOwdrA3g3YCekkEi7BQ3OQhw=,tag:3xgbyph3v2y3rnUoSHHaHQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//dFMa6yiwaDUIdOLrXaXDDVNKYCmfyNklH586YdTPkArY
            cmwcDFtPGToK528yWJXT+n038wK+Sv+4k03Puxt4rf6QEBxpXVMv2xGO3kYVSCuN
            uigwtDKArqifxVQLtdbIEeT8XgpMxMgHxpvbibJas53Z8JAYspscIPDa2HFQ5WIZ
            rmZWQskVrmU5B2GljfmZtffXbUS0FYp2qfL503UEBGNMCR1DO6vNq1mh9eTwgecj
            k3LtacEEOiqpNbg4cbA92jEOZUKgy5F52WFKtP3ni54XQdeJUrvTTvlWPVL5W75T
            /+W77h7eo118Bp7BNvqiQ6LMwjW3f9qvphlYnsCJu7oSbd7qBMm0azyRyFnWBw26
            uXSOAmkSVaF2qVr/gBP105ou175Ursypb52oBrjrHtgWE3wEu4lQT4bsmZWopyJW
            udffVneWPWbSIsEzH2tSRSa90NM7zSPsGVwBwBCRTCjgfsqDwmeU/AcGLKaDK/q4
            nm4cuk173CXmWNi8wPkd8vW1ed6hKpFiYtEs5OcAuzaD0M3x1jV90+HU3hq1ej8t
            rqHsBRPicV+pBSTDubTrp0xq9noOjBJKSR9mpVaVy2MySfe6PkWsN7C1Kvjh5ktL
            7konjUTU5Td4PPYuCMHZvNr6KWjz58lsrRtOm8Rx618yzHNO8p6t+KvH2hLyqmzS
            XAGyoePwzROnIM56+vY1W1MJ7cwX8hPUc1+Tgj5m5nYpA5qRoThzVaMm/QZFle1g
            sohUY/l1BJzN4tNvCLMxqKGzNzUXZ9EXJGeporBYzn6xHo/l6q+TSCFWJtKH
            =jFkn
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: dkim-rsa
    namespace: mailserver
stringData:
    cluster_domain.rsa.private: ENC[AES256_GCM,data:g1RDj/bJGSxZBUwm8a8Q3f6y9sAZ41RDZS2dDf3B0ixBYvkbvql5BjPXOOMz21Q6PBTAFeZlOpPuLMoQpanoS0uEqto6QFhteGong7nGD8hd4BaZ1/y0tU4ueF2mVgD8NkK/jY4+9xdm9SOKp7NKNVjB4kUbDWrb005j8sRbcLmr7yrcQiwxnBMzr0MV424TFHbkuxStrU2ipgCupMaFTQaor4RmFkTT6/yW0r1D6wKnGw0Osm+V4djsAOURS/1tobXrPFFezhnuM+MY+lhKEKvXZbdJtDRppbanUi5W6IvtlygbycamfO/CSz2Y+JcJ0LgcsdYbo1TyAqkz0gQlmJ2Yb2ht5Mo78wlqFgUpnIxdJh0sVJiZtjKyclj5T3pmatAqqvsApPXBilSX1UmlbaUqHVpxM1iuEb+e865ovIgml1g9dS6q6Ck0Cfk+PF/NByjxdyyxqNQAYSzfm9HBzZHIDVch0Jh4vwdVjwwWt9i9CfxdHE9hvD3WGoPVXWQQSi02UW5VC9/LcBqaYTJ+P7rbYIZ6MD0iC2Oq7DgfzPE1YPyA80YS1yLwHca1DiCeSBkTkivxJq9LGWS35biw/Qh3OD1mExzxZY5fT+YSx6nKbhHWeJesGcQYZ2HVDdyldOIGrjMEylATj0wiwgTVVrq47+O6xfBHqw8oJLgkSNiJ/2RQyjFSvm6rFn26j4OwC8qhMGZUlu5FuOzlSQPO8SdCHVm0V17mFU2iTo3FxJkt5dF6D6I657G9rRNG+DVsF95BB7ClhF5MSo2J9GrvhcSzJEwm6DG5vvG+cPT2uKQ/g8GK5AJJsfVumtWjq5Amxi+W9YRBRHVFMDlpg9NG+UUGsLT5Gu/n+uHcnd+Zg1YeLubbdD/LbX/GODdyG0K2u5GTuDRecRT/P6zDZwMhUmw/OoBTWOByoE/dpL7WCsz0cSLjxYhPl7+vfwyMBfabWzGGhgIKqaTEr/ZMQi/Hx+auyz8fTFe4sVr6icl58jPYEKtwaP3mb3Wi9C1yuHzaf8uloELPrm7wrIOv+RtXUSEqSih/lKaGbYO91YeimV1dnfvFuJx353dYwCqDTUBRjNG/ekAiaQf76UG3Z/w94FmFma+R9UnzKzZHAoZBYhQQYadbu3Xrec053aRWwdEmd73dgVSYftiX0mg7V9dBb8NslTkfeUzcsk2XX7ew+OPIU+vyqHj6Vhced8ac8EDuZdom6ExBneMsncOcgVkxWlAS+HXPbhMs7Z9PEe+kpU9cb9hW6dX0wJ5o7xzsmdFeu5nFjLFi3eLJc5qc2iNlPXqYq/n5qRfWm57NvFLiV+DJ3nYVLJ/S5z4SU+Mj87i95gAyDx4hqprP+82B0shyp7SEbRSyFRrYf5zwmICXugyn8vWZxM00lbztecRZi3rLKCTsr4qk4kAUdUYTCRoggAPI392vv6FOV5NxSE29SyzuLyiyVuqiDSjflVXJUEd91nB2rY/T7rf5rcEg+P+L5TvlD76e+AQ4qiy0fakmzGL8Ib/K/QKYhqQ7hfxdItWGfQWHDVfpDkJvA3nN4OwXlOGXr678Nl8EhPE2yKsPOUuOpvbhJBfQHB68FOHXXEznbiOIJOzRdtQRLPqGwJceDD+t4Mof1PQ2RjDkqiGXhkNrMYXIDh6UVg2IR48LB2khl1mmxJtctkt80cUjJRlH7plITw7C7U0nxzc034663UG4rfBHPkNSN3R9epnbPxGbbvyq6htqAYdwmmfpDpxnArwWrWE4b1yqgJrN6llavlUbu/Road+Xaj7B5HcdwFc+9ukLG64BIoEolWFnSd1R1UECS4q13IHlZg6RtlQIkuxZOV/SX2RMF7Yp5jJuBNx3yy2+yE4KCJwWASN5EhgAn2HMbqJ2kVd6LFkq34Sck9M8mq6B1lFTi2A5ra5HiSn6LYMnJhI7eEMTOO+zKtWn9sGALXl7hQE+O8pKdFB2LmVW+J7CTSmNgrXVY7A1hzsDOWsm4bu8S1FvlmCZG6CnhUvl4WcsXFoCIoOp9xNTgF2wgO8m8CQnNqjoZITjb27cUw8kSRM7F+CJpat4KOEiFP1jjd/j4Wpszrt5wfojp5Kc/0xuyuUlaxxpJUpyE6QvLNgkgEo3DU9MOqvgX4Jnoxz0umszhL88Z6RNzUsDfpyV3bHJGEmO7/4yLg4H/r3RYujqGLwkezQLc6D2y7C3ou2HVkpNdcveTKzJ6Q/L6KPcjIt/Fo1fnTsGM49YuG/XHJNvN0aFOeb4xKsHRcFBHfkBjt1A8xc=,iv:jRM1y+sY9Q3hVnsVS2VCuV/ri/kC5RqVaqfvww18n20=,tag:+GoG4mrR4b+94+loQiW5Ug==,type:str]
    cluster_domain.rsa.txt: ENC[AES256_GCM,data:goMZxyKImMIcQFCd4krY/Peau1Qb9TX9ocLR3wIV5CUGuQDOiwn/3P9NNWnvql58BL1kWtb/d6UxMtXGhTLBAu2d9Bh2WAh7/jvXePn7QWWTqTFEVLs+C78g/p93DSA2mBRn6cIkFOi8iB3Vhcw6R7WmLn2GePPtfimh7Ge/2C8Yxsc3qaZwuCH9EJtyItVC/kZ6W9LUWYEhcDq5wOiYStXJ3qlBi7e2zHiIpiu0rmsX4Jsnk0HTjZMEQczwnnK8zifAy1kXMc7BCrUxA2xUB9SLLtszWzaBSQ/Zdou9JATkRIpY4szdfYagSRdOBdv6TAgudrA6BIpKvfxli6D7fug66c1EUy3fu5XrrI/4exGCMvGf8Rbw29FggBhu3odt2zmRjTLyc3GJai6OXBjaiFV2Nx1h7ZY9xj6q5GXeXFqBjejFeDiItyd3hIuc62nMkwcZWrXlAC8D10Aa96kE4Dnu/52o2/oYwLgTqj929LQoK2yItmv+O/E2iuZecCQUcEPKR6i9SAdwm2S7T9d6MX0XJb1LahhY2Mcr4XZhup/Ov774FxpTIyZE1OtUskFgaHCQvV2C4VJrU72EI4T+Yf5YimLikP8=,iv:9TlUGTbKihwNHUbV3OpKORmOcgkezrsNru+Tr1Xc3xM=,tag:/OgKDDRNMidNEAuQmn/S2A==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUXVBZmZ4c2NtcWF3b056
            cERqcXRPUkZaVW1MU3U0OENKaVFBTTF6ekUwCllrbWJRYWtERFhsQ1h5ODZQUEVF
            TzJLT0pnOGhhcGppM2hWVVRLSksrS1EKLS0tIHdIbGxYTjhlUW5xNTVrNmJiL0hm
            V0YrVTZycVJFWWpiVlY5RGJUWDhvZ0kKwEV2LQUqb0ng5ENKnkwKupkApN/jSTW7
            2x37bNuET0pmt6LP2+5TmsFgfg+siB4Slec2JNHfoZ1b8ftsHoIw8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBL0dreUdY
            WUpRSldZQmJ6MGpwMDFHbWVpbXZDa0tBbk9VWVVYYlN5bE1Uawp6amlZSmtDZjFR
            dWExM0N1VG9OZXJDZks3VW1qOS82TGdka0pPYnNnY0JzCi0tLSBHV1pQU1ZwelZT
            K3NiczZjK1JZRWg1TENzNCtzejQvMmU0cXM5SzFzQS9rCsUiPL4lHAdHk+61E8RF
            HXg7IcxiFiL5mFPVMHIBCZyThJFs37AAyTTALy4BGmH8KlFwyugiR6FDZ3qdPCD9
            25o=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBeGpRNFlo
            WXhJcVEwMndxcVYzQ0pPcnlUcDdYelQ3ZzFUKzdrQ29vQmJMKwo0eHM2anYxSkJO
            dGJlQUxlbTJmaEZqOU0rakpFKzlFZjVlQnpzY3V2TkhZCi0tLSBtc2FCSDNxYVpH
            WnpIRHRhUXVMWGNXUndHdGRzUnVxZS9pb0g0dzNKeTBFCva6c3n+tRVwZJgFa2XT
            AXpqUQQr/csFYoiGlFqgOdnrG32V356GA+wl+kfuhtWAZBmz7sTHTiHFbW2QOhma
            cv4=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:J5J2Qm+GQhR+JW0hYTC9z40vxizNZegSmOEeE3VXurjDzcH2fc37WEyvb2RvHuHS7Azunmk+qVmyu8BctmemuDkAbWPhjOXZbvmM8iGOViD2OPxu09TsVyRj3ObhPoJl3WBewzSpDgfUrYf44LLcM/RQa/iTCrA6Sgp57jYpcUs=,iv:cGJbv7/4wo1gxH50kG4aOwdrA3g3YCekkEi7BQ3OQhw=,tag:3xgbyph3v2y3rnUoSHHaHQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//dFMa6yiwaDUIdOLrXaXDDVNKYCmfyNklH586YdTPkArY
            cmwcDFtPGToK528yWJXT+n038wK+Sv+4k03Puxt4rf6QEBxpXVMv2xGO3kYVSCuN
            uigwtDKArqifxVQLtdbIEeT8XgpMxMgHxpvbibJas53Z8JAYspscIPDa2HFQ5WIZ
            rmZWQskVrmU5B2GljfmZtffXbUS0FYp2qfL503UEBGNMCR1DO6vNq1mh9eTwgecj
            k3LtacEEOiqpNbg4cbA92jEOZUKgy5F52WFKtP3ni54XQdeJUrvTTvlWPVL5W75T
            /+W77h7eo118Bp7BNvqiQ6LMwjW3f9qvphlYnsCJu7oSbd7qBMm0azyRyFnWBw26
            uXSOAmkSVaF2qVr/gBP105ou175Ursypb52oBrjrHtgWE3wEu4lQT4bsmZWopyJW
            udffVneWPWbSIsEzH2tSRSa90NM7zSPsGVwBwBCRTCjgfsqDwmeU/AcGLKaDK/q4
            nm4cuk173CXmWNi8wPkd8vW1ed6hKpFiYtEs5OcAuzaD0M3x1jV90+HU3hq1ej8t
            rqHsBRPicV+pBSTDubTrp0xq9noOjBJKSR9mpVaVy2MySfe6PkWsN7C1Kvjh5ktL
            7konjUTU5Td4PPYuCMHZvNr6KWjz58lsrRtOm8Rx618yzHNO8p6t+KvH2hLyqmzS
            XAGyoePwzROnIM56+vY1W1MJ7cwX8hPUc1+Tgj5m5nYpA5qRoThzVaMm/QZFle1g
            sohUY/l1BJzN4tNvCLMxqKGzNzUXZ9EXJGeporBYzn6xHo/l6q+TSCFWJtKH
            =jFkn
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
