apiVersion: v1
kind: Secret
metadata:
    name: abusix
    namespace: mailserver
stringData:
    ABUSIX_API_KEY: ENC[AES256_GCM,data:IrifbCRvL6Ey3+35cESL4Zz8U9fQRce7GJD9nl1+Rfs=,iv:7sP5zouoxgImCKMssADThELgndOxp7eQ9UhwGSU7wFk=,tag:XXLa09xVdJJwyIX9/VjSNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVU91b0Y3NjZDRGI0RUtI
            TlY2YytLU1BiR00vZUR4ZmJtNnlVcVFJZm00CmpMMU9GamN2QTl2Qm5KSFZaZHpW
            TEhBT0FRMks2U0RxNlFJZnAvNHJXVWMKLS0tIDdMQUlTS3FtVjNZR3Zib2FpaURD
            cVNiS0w2RVhxWjU4TXdYdGQyb2hWbFEKaoiED3pZkyP4+z+48O2VGqGGzqNaCNTP
            V3WrQ8p1VXkZmmxGWX2cQiEw1h+EnfzAm7AVqjrNjue579UHbToUag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBNGZTUHRL
            dXc5eVRHc3hCWmFkQ1JaUHhBaUt0WDRKdTN2WGl2TXlkejNvMQpOQndRK240dTBu
            UWVkMHJaOFZsdEczTWljeU51b0VKKzdVM3diZmJXUllBCi0tLSB3aFVuUElVQitZ
            SGV5MW84OEtRbHE2U2xLT3ErVE13eExQbzNJTFVqWnRRCiaHnaTywClvMiAyjLyC
            jagOKJFA2+C3iAh5G3iQ4L0u65IJIvxVTnZxbfXS8cDeYhg2CNF2JLXvHP1RL3j4
            LsM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBMXFZUmti
            MVdkejJocmVxNUNYeTB3bFlBU3BibmVxUVZYNyt0S2o3UUpuNgptTjFPSVU1RGNE
            a1lQcTB3dG10L1E2Y2kxSmczOXIrYVdvSTFwSUNGay84Ci0tLSA2Rm5lK3dKcUlB
            Q3FzRktQOWZxcDl5QlZVYitjQVNBN1BOTFFGdjE5N3hVCvTknF7bugmrmkmkWNf/
            kc+WLYvBsiDQWfB8FP0YZFEeHc9rI6Kn4nlZDBBSDH/J8IBhlc0XU/RmAlQwpERG
            AHE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-14T22:32:49Z"
    mac: ENC[AES256_GCM,data:DAOpFISIf/OKqYXdBjD23sPy+9KyjWBBobdpHD8QBTpUXddv7I7odcQUtpEFkSltsF5YyHq5xjCsT93ogVH9wXpIyRfaBsvLU0NPrkIeNKmnQx7wZOHffCy8NxciA8EaoqVglFubzjR7gufYGtDcpwr9aUyKSnZajLayatjL5QM=,iv:y83rEYDiFI25aqdUvMPBOmAeyPwJcSDkrmihN761nv0=,tag:S1Nlkrd7LR//DTyFP9DXkA==,type:str]
    pgp:
        - created_at: "2026-06-14T22:32:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+LULbkvntrsnGJDSrP8Ej+lgW7aXHbdG7bKV5KUiwTREX
            DuJkAcF7G5KsnYH9vs/fXilOUoWjWgkGCSL2mlSkiw1QVOYa78MCe7z6IcBi9moh
            dePh1x5/vnle3KppSyqruWEthnwfbnaVT665uvxdDM9Ge5lFCBnIZpDtgsGG3oHe
            vj/jSXwNF2EQu1AER3WvZmcmhC6Djce6AtjKAmnhns4ObZnMjuaDp3OW/udIRt5n
            ls2pt8LILdj6JMbbOniNH9lGScR2O6RNSY9OtIsFvHFeiLHm629gJQ8B78qY/ZyK
            qyf4T5VPUPHJvQDli4z/3fUDNV0sYq37oZ3rR9jSsWQTCnysVfgjLc96aXWY+9hb
            GtYdomd9u+pFDpL1v/pYjtRnK2VufUy6w+CdEnc+pO3MgtARNKmj95GuU4o18XHv
            Lgaf2GoNVSCRjhwoRPPU0JB42XFbw/H5qwIKo5Qtvp/8mWmMfyfhNRA938d3rwPD
            j0y1xh4xpRQ7yoPr6HTnOpyWPdMV1f/Af5ACtnr9YttOCdevbK5L8SfZDzjv/aPU
            Si2PUZywOORDRsm68wxqq9fYBkompwosgD2IuNjB8tvABV6Zj1Axi+cfM3IHU+Zl
            yosNI7+/SAyD1aAoLeECtPJjqIU4WVQzZd68qBTzvrpofAYSpJcs58T7v7ZKcmTS
            XgGL+PR1Seokkh/IxUUrUQcVszFIv/XQmg7YcqF7uKB45ORFynILrYbxrREu61ra
            8lUUeUfGR/bI9PeebYskET5Nsx86EYdSVwMQmI3ljvOxY+WviWlGhMImoXMufFY=
            =V3ac
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rspamd-controller
    namespace: mailserver
stringData:
    worker-controller.inc: ENC[AES256_GCM,data:fxeTrGTEhzfYkNB+C2BsJsn7+2Ri/zmbjWJXBjeKIQBBYkkhQldgPqbYob1EPvWnt2EH7epmjwSvYZ1WO06W7TCAEEK21rCqxyYqcbZxwgBbcaIf4xUFU0eJywIlQld+keULahMgTU6iv3gfmUjRbrkyaG6QTnj4TNkjcUUhXTHe01dbrBzNZyF9h712+2judLvKkiDKMbJ8G2x8lsk/OAqdtNaG3ae0qIlWMvCIt5o9VsQslJM5VJI3iHRyJmPFT6zkEjX1,iv:TJNGez8xYrR34aXRCTr6VyhArdoxs9b+ufQZHv+e8Ck=,tag:iswpBXD0btaQAZdWG5PONA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVU91b0Y3NjZDRGI0RUtI
            TlY2YytLU1BiR00vZUR4ZmJtNnlVcVFJZm00CmpMMU9GamN2QTl2Qm5KSFZaZHpW
            TEhBT0FRMks2U0RxNlFJZnAvNHJXVWMKLS0tIDdMQUlTS3FtVjNZR3Zib2FpaURD
            cVNiS0w2RVhxWjU4TXdYdGQyb2hWbFEKaoiED3pZkyP4+z+48O2VGqGGzqNaCNTP
            V3WrQ8p1VXkZmmxGWX2cQiEw1h+EnfzAm7AVqjrNjue579UHbToUag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBNGZTUHRL
            dXc5eVRHc3hCWmFkQ1JaUHhBaUt0WDRKdTN2WGl2TXlkejNvMQpOQndRK240dTBu
            UWVkMHJaOFZsdEczTWljeU51b0VKKzdVM3diZmJXUllBCi0tLSB3aFVuUElVQitZ
            SGV5MW84OEtRbHE2U2xLT3ErVE13eExQbzNJTFVqWnRRCiaHnaTywClvMiAyjLyC
            jagOKJFA2+C3iAh5G3iQ4L0u65IJIvxVTnZxbfXS8cDeYhg2CNF2JLXvHP1RL3j4
            LsM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBMXFZUmti
            MVdkejJocmVxNUNYeTB3bFlBU3BibmVxUVZYNyt0S2o3UUpuNgptTjFPSVU1RGNE
            a1lQcTB3dG10L1E2Y2kxSmczOXIrYVdvSTFwSUNGay84Ci0tLSA2Rm5lK3dKcUlB
            Q3FzRktQOWZxcDl5QlZVYitjQVNBN1BOTFFGdjE5N3hVCvTknF7bugmrmkmkWNf/
            kc+WLYvBsiDQWfB8FP0YZFEeHc9rI6Kn4nlZDBBSDH/J8IBhlc0XU/RmAlQwpERG
            AHE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-14T22:32:49Z"
    mac: ENC[AES256_GCM,data:DAOpFISIf/OKqYXdBjD23sPy+9KyjWBBobdpHD8QBTpUXddv7I7odcQUtpEFkSltsF5YyHq5xjCsT93ogVH9wXpIyRfaBsvLU0NPrkIeNKmnQx7wZOHffCy8NxciA8EaoqVglFubzjR7gufYGtDcpwr9aUyKSnZajLayatjL5QM=,iv:y83rEYDiFI25aqdUvMPBOmAeyPwJcSDkrmihN761nv0=,tag:S1Nlkrd7LR//DTyFP9DXkA==,type:str]
    pgp:
        - created_at: "2026-06-14T22:32:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+LULbkvntrsnGJDSrP8Ej+lgW7aXHbdG7bKV5KUiwTREX
            DuJkAcF7G5KsnYH9vs/fXilOUoWjWgkGCSL2mlSkiw1QVOYa78MCe7z6IcBi9moh
            dePh1x5/vnle3KppSyqruWEthnwfbnaVT665uvxdDM9Ge5lFCBnIZpDtgsGG3oHe
            vj/jSXwNF2EQu1AER3WvZmcmhC6Djce6AtjKAmnhns4ObZnMjuaDp3OW/udIRt5n
            ls2pt8LILdj6JMbbOniNH9lGScR2O6RNSY9OtIsFvHFeiLHm629gJQ8B78qY/ZyK
            qyf4T5VPUPHJvQDli4z/3fUDNV0sYq37oZ3rR9jSsWQTCnysVfgjLc96aXWY+9hb
            GtYdomd9u+pFDpL1v/pYjtRnK2VufUy6w+CdEnc+pO3MgtARNKmj95GuU4o18XHv
            Lgaf2GoNVSCRjhwoRPPU0JB42XFbw/H5qwIKo5Qtvp/8mWmMfyfhNRA938d3rwPD
            j0y1xh4xpRQ7yoPr6HTnOpyWPdMV1f/Af5ACtnr9YttOCdevbK5L8SfZDzjv/aPU
            Si2PUZywOORDRsm68wxqq9fYBkompwosgD2IuNjB8tvABV6Zj1Axi+cfM3IHU+Zl
            yosNI7+/SAyD1aAoLeECtPJjqIU4WVQzZd68qBTzvrpofAYSpJcs58T7v7ZKcmTS
            XgGL+PR1Seokkh/IxUUrUQcVszFIv/XQmg7YcqF7uKB45ORFynILrYbxrREu61ra
            8lUUeUfGR/bI9PeebYskET5Nsx86EYdSVwMQmI3ljvOxY+WviWlGhMImoXMufFY=
            =V3ac
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ldap-account
    namespace: mailserver
stringData:
    dn: ENC[AES256_GCM,data:+ySu0O8xT3sWzPt93ZOOpLs/efZ+VSR32DpyUJLy4YhD5GNs8AI/G2nBeqTG,iv:bbQGZ6JrT7it3BfcY7/hI8CXjQU6iwXorXatqoEM1/U=,tag:fQ0F37R7kpO7Keru+SVGcg==,type:str]
    password: ENC[AES256_GCM,data:kGvRD5GkOSILQ6BPeXG2wGkUhHrIP4IoUCul6d1aGV9kCq/Rym9S7Kfe3YvBlinraErsXo/EN5x1WCOd,iv:SgoqQ/Y92uMzKK3ErkXzTkLbndg2i0CNmu9gJKBXApw=,tag:3gbi3f5R4i34G07soCY7MA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVU91b0Y3NjZDRGI0RUtI
            TlY2YytLU1BiR00vZUR4ZmJtNnlVcVFJZm00CmpMMU9GamN2QTl2Qm5KSFZaZHpW
            TEhBT0FRMks2U0RxNlFJZnAvNHJXVWMKLS0tIDdMQUlTS3FtVjNZR3Zib2FpaURD
            cVNiS0w2RVhxWjU4TXdYdGQyb2hWbFEKaoiED3pZkyP4+z+48O2VGqGGzqNaCNTP
            V3WrQ8p1VXkZmmxGWX2cQiEw1h+EnfzAm7AVqjrNjue579UHbToUag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBNGZTUHRL
            dXc5eVRHc3hCWmFkQ1JaUHhBaUt0WDRKdTN2WGl2TXlkejNvMQpOQndRK240dTBu
            UWVkMHJaOFZsdEczTWljeU51b0VKKzdVM3diZmJXUllBCi0tLSB3aFVuUElVQitZ
            SGV5MW84OEtRbHE2U2xLT3ErVE13eExQbzNJTFVqWnRRCiaHnaTywClvMiAyjLyC
            jagOKJFA2+C3iAh5G3iQ4L0u65IJIvxVTnZxbfXS8cDeYhg2CNF2JLXvHP1RL3j4
            LsM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBMXFZUmti
            MVdkejJocmVxNUNYeTB3bFlBU3BibmVxUVZYNyt0S2o3UUpuNgptTjFPSVU1RGNE
            a1lQcTB3dG10L1E2Y2kxSmczOXIrYVdvSTFwSUNGay84Ci0tLSA2Rm5lK3dKcUlB
            Q3FzRktQOWZxcDl5QlZVYitjQVNBN1BOTFFGdjE5N3hVCvTknF7bugmrmkmkWNf/
            kc+WLYvBsiDQWfB8FP0YZFEeHc9rI6Kn4nlZDBBSDH/J8IBhlc0XU/RmAlQwpERG
            AHE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-14T22:32:49Z"
    mac: ENC[AES256_GCM,data:DAOpFISIf/OKqYXdBjD23sPy+9KyjWBBobdpHD8QBTpUXddv7I7odcQUtpEFkSltsF5YyHq5xjCsT93ogVH9wXpIyRfaBsvLU0NPrkIeNKmnQx7wZOHffCy8NxciA8EaoqVglFubzjR7gufYGtDcpwr9aUyKSnZajLayatjL5QM=,iv:y83rEYDiFI25aqdUvMPBOmAeyPwJcSDkrmihN761nv0=,tag:S1Nlkrd7LR//DTyFP9DXkA==,type:str]
    pgp:
        - created_at: "2026-06-14T22:32:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+LULbkvntrsnGJDSrP8Ej+lgW7aXHbdG7bKV5KUiwTREX
            DuJkAcF7G5KsnYH9vs/fXilOUoWjWgkGCSL2mlSkiw1QVOYa78MCe7z6IcBi9moh
            dePh1x5/vnle3KppSyqruWEthnwfbnaVT665uvxdDM9Ge5lFCBnIZpDtgsGG3oHe
            vj/jSXwNF2EQu1AER3WvZmcmhC6Djce6AtjKAmnhns4ObZnMjuaDp3OW/udIRt5n
            ls2pt8LILdj6JMbbOniNH9lGScR2O6RNSY9OtIsFvHFeiLHm629gJQ8B78qY/ZyK
            qyf4T5VPUPHJvQDli4z/3fUDNV0sYq37oZ3rR9jSsWQTCnysVfgjLc96aXWY+9hb
            GtYdomd9u+pFDpL1v/pYjtRnK2VufUy6w+CdEnc+pO3MgtARNKmj95GuU4o18XHv
            Lgaf2GoNVSCRjhwoRPPU0JB42XFbw/H5qwIKo5Qtvp/8mWmMfyfhNRA938d3rwPD
            j0y1xh4xpRQ7yoPr6HTnOpyWPdMV1f/Af5ACtnr9YttOCdevbK5L8SfZDzjv/aPU
            Si2PUZywOORDRsm68wxqq9fYBkompwosgD2IuNjB8tvABV6Zj1Axi+cfM3IHU+Zl
            yosNI7+/SAyD1aAoLeECtPJjqIU4WVQzZd68qBTzvrpofAYSpJcs58T7v7ZKcmTS
            XgGL+PR1Seokkh/IxUUrUQcVszFIv/XQmg7YcqF7uKB45ORFynILrYbxrREu61ra
            8lUUeUfGR/bI9PeebYskET5Nsx86EYdSVwMQmI3ljvOxY+WviWlGhMImoXMufFY=
            =V3ac
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
