apiVersion: v1
kind: Secret
metadata:
    name: abusix
    namespace: mailserver
stringData:
    ABUSIX_API_KEY: ENC[AES256_GCM,data:lqzUqa33U5Lma+kspd4Tr0PSL9yNnukZPDEo72BfVYo=,iv:81GWLMkKoHzt5mzGsx5pPhi/ReSXPDU3E8xjzGB3r8Q=,tag:vGC8UloLZDv+bO6geEHc6Q==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaEorcERTQW1XN3JQNE1P
            cUsyaXRQRk1LZUtlZDZzVnVlZnNiYUVrOFg4CkdieTBTdU9oUTRWRG94L2IwdFQw
            dkdSV0RLUURuajN5UHkrd2xaTHhhVVEKLS0tIDFoZ1N4SmMyZkU2b0FEUVRIUUpD
            ZHF6d0NTVkQxNHkxQlUxdENFNFFVY0kKa7XujMU/cpNI2ISOeY0JkJ1AY6DWGcQI
            R30yRyT+wl0wPT3o5+SIqcc5WjqqLNNUFkx+R7Zquud8bXMCY9gp9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBK3NuNjd4
            Y09Cekl4RnhqcEJzb0M4dms2VUNxWVJvR2taZ0RRS2RZZHlVMQplN0dCZU9JT1E4
            ZGVKQTMrUU9xL3RnZTBOUmhpcU1CNXRXWi9NSlU1dWVzCi0tLSBiVFhOVWJYcUpt
            c1p5YzRXdWptcjl0dUl3Y1loWjluQm1hTDg4ZWh4NUo4Ch8xy7uLFpvVKIhmIkq0
            C7ox7tbwwIv9uJA/1xCLm2e2R5hmMZEk7CHkdKzJ0jXhp+F70HZtFOSjIYceBihG
            6AI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBdTRGaE5s
            RVo3VjdtR2VwRUtvdDdaRjVIVnZHTzZ0SHJSQzViZnFXZ09GYgowYlNTQnZSWjRw
            VDdpNVFqMHVlRldUKytFK1p2RCtHb0p6VUpLcFpMdnNNCi0tLSBWSkRFWHJ5dTJx
            YndiV01Hcm9oU0EwaGplczVsdzJ2ZGliM1FueXB3MzZjCnuvACE0OpDDWMFcnpRs
            oKYfd9DdYagWkshdfcr17yEC46tOpMs1NiGn9urRLnAjf8YDzLv8bcslstJ2wYIQ
            b+w=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:BVda6CDzrf/eh0M49yiO8F5a/1S8Y4pZ466DCeoJIQepfViTXeBD3lDIh/CJbfJAzok1+rASOwNvDOaJTSE0PcHAdy87oFhISkFBNBs7arrKTUYNA+1l73r4G31P632Vs5Sa0P25UYCzpZ8sgVkS5uVv53pY8po3WhOv2c/93Ow=,iv:otrIJs4Rh1vx2Nf0I4QL69nyBiLiKMrKUaG5mjkCv6A=,tag:NaocnLWe8QUTEsTVJ+lAxQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAkpQGH3kqhkHuyxyHd7Byt7EqoxXuQyMCvDmtbic64NeO
            Ttg3tfe6Vg55Nc9kNmB1yeU9M1KssxHNA0aVYJgqgoKsoX4lg4Iph9yQ93uvgrgH
            /aAobSelM1eIJV7G6jyF8HSMEcqkikMEngL9GBPfDQy3vJ0CQ65bT8uMaEtkaiP5
            4USPjqAsUfQ7OOuvp9Avp1nfo5+2Cm0A2vWcIhWXK7tejxZoJKtOzmcXPKPWV1bG
            CGhPoXMrzHOkoF6Lt+UNW+XTmCrZc+IGGiHvZTPcr/FFy6ahJzCDykChKzZBBYSc
            vmjfqo604n+cpSzDubz5Wtut3DMybFcvuX8UC4NrqzsagkqplexGMWF1fvCzev1D
            oUECdSSFR8V1APidi9gtwjXggW3/8rIjtPTKGAYHCjr30LAP++mQrM40HKIgt99P
            GPb1p1erwRG30VaV4xkFqrABoybLxRRntucfPJ6iIWcgGs72NDOcFWHdbC/8ludL
            RNgHx1WujDK2HCVUFYjL+Ih3HQMd1ytos9nIAyAKlkIul5SNIp3L4FvavR1Ps/zD
            oZ00TNto8DeBFozhVeVteLPZ+OZA/iVNE4vVUuDoIyVkfKciVY0e4YXpYJ6VWPnX
            v/kAygCqwUJKLreQnwxgg4sRURl93fg2Oh2GdOGodkmJvqPIpRicYCm1iDZAV4PS
            XAEmhMEjRHVtwbkZ4fnEkzx9sbAnCEem96K5dz6a2pq8zWrJED7cK0qeGVP4dRL5
            p6K4ou9R+HjQlvrzLmDTBBke+nDDm5U3Mqs54KrgL233EW5fSOIreklHzPM/
            =K28L
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: rspamd-controller
    namespace: mailserver
stringData:
    worker-controller.inc: ENC[AES256_GCM,data:THuEVEtocBSGpuXmqWA9MJwyFiWKPlwQUjyrJJ1GNiPNoX4b1ZMkzIB/IxWQKlFF6er4YcEgftzKDygNb3z4D3WutPn70jfZ4r7MAJy26JPjnJdaY7GHuSGGw0YeBwsSOynk075WQkLYBuFfYQQJz3BJ8nKTzQlLGG3O5TGv4V/aWIhslM+Hz2Gms2Af7ZbOu1QILczog55vORiINKs4lWlARGTVP0s9oMQXkYUm0QBVFE8/QDkdJy4ap2ljtX6rK653j+XC,iv:BO1wwiGY4gnL8VhLC5Z118WCSm1dMELVyD5jdcJxPlY=,tag:1ITJEDgCyl05fTUy7XDPOA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaEorcERTQW1XN3JQNE1P
            cUsyaXRQRk1LZUtlZDZzVnVlZnNiYUVrOFg4CkdieTBTdU9oUTRWRG94L2IwdFQw
            dkdSV0RLUURuajN5UHkrd2xaTHhhVVEKLS0tIDFoZ1N4SmMyZkU2b0FEUVRIUUpD
            ZHF6d0NTVkQxNHkxQlUxdENFNFFVY0kKa7XujMU/cpNI2ISOeY0JkJ1AY6DWGcQI
            R30yRyT+wl0wPT3o5+SIqcc5WjqqLNNUFkx+R7Zquud8bXMCY9gp9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBK3NuNjd4
            Y09Cekl4RnhqcEJzb0M4dms2VUNxWVJvR2taZ0RRS2RZZHlVMQplN0dCZU9JT1E4
            ZGVKQTMrUU9xL3RnZTBOUmhpcU1CNXRXWi9NSlU1dWVzCi0tLSBiVFhOVWJYcUpt
            c1p5YzRXdWptcjl0dUl3Y1loWjluQm1hTDg4ZWh4NUo4Ch8xy7uLFpvVKIhmIkq0
            C7ox7tbwwIv9uJA/1xCLm2e2R5hmMZEk7CHkdKzJ0jXhp+F70HZtFOSjIYceBihG
            6AI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBdTRGaE5s
            RVo3VjdtR2VwRUtvdDdaRjVIVnZHTzZ0SHJSQzViZnFXZ09GYgowYlNTQnZSWjRw
            VDdpNVFqMHVlRldUKytFK1p2RCtHb0p6VUpLcFpMdnNNCi0tLSBWSkRFWHJ5dTJx
            YndiV01Hcm9oU0EwaGplczVsdzJ2ZGliM1FueXB3MzZjCnuvACE0OpDDWMFcnpRs
            oKYfd9DdYagWkshdfcr17yEC46tOpMs1NiGn9urRLnAjf8YDzLv8bcslstJ2wYIQ
            b+w=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:BVda6CDzrf/eh0M49yiO8F5a/1S8Y4pZ466DCeoJIQepfViTXeBD3lDIh/CJbfJAzok1+rASOwNvDOaJTSE0PcHAdy87oFhISkFBNBs7arrKTUYNA+1l73r4G31P632Vs5Sa0P25UYCzpZ8sgVkS5uVv53pY8po3WhOv2c/93Ow=,iv:otrIJs4Rh1vx2Nf0I4QL69nyBiLiKMrKUaG5mjkCv6A=,tag:NaocnLWe8QUTEsTVJ+lAxQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAkpQGH3kqhkHuyxyHd7Byt7EqoxXuQyMCvDmtbic64NeO
            Ttg3tfe6Vg55Nc9kNmB1yeU9M1KssxHNA0aVYJgqgoKsoX4lg4Iph9yQ93uvgrgH
            /aAobSelM1eIJV7G6jyF8HSMEcqkikMEngL9GBPfDQy3vJ0CQ65bT8uMaEtkaiP5
            4USPjqAsUfQ7OOuvp9Avp1nfo5+2Cm0A2vWcIhWXK7tejxZoJKtOzmcXPKPWV1bG
            CGhPoXMrzHOkoF6Lt+UNW+XTmCrZc+IGGiHvZTPcr/FFy6ahJzCDykChKzZBBYSc
            vmjfqo604n+cpSzDubz5Wtut3DMybFcvuX8UC4NrqzsagkqplexGMWF1fvCzev1D
            oUECdSSFR8V1APidi9gtwjXggW3/8rIjtPTKGAYHCjr30LAP++mQrM40HKIgt99P
            GPb1p1erwRG30VaV4xkFqrABoybLxRRntucfPJ6iIWcgGs72NDOcFWHdbC/8ludL
            RNgHx1WujDK2HCVUFYjL+Ih3HQMd1ytos9nIAyAKlkIul5SNIp3L4FvavR1Ps/zD
            oZ00TNto8DeBFozhVeVteLPZ+OZA/iVNE4vVUuDoIyVkfKciVY0e4YXpYJ6VWPnX
            v/kAygCqwUJKLreQnwxgg4sRURl93fg2Oh2GdOGodkmJvqPIpRicYCm1iDZAV4PS
            XAEmhMEjRHVtwbkZ4fnEkzx9sbAnCEem96K5dz6a2pq8zWrJED7cK0qeGVP4dRL5
            p6K4ou9R+HjQlvrzLmDTBBke+nDDm5U3Mqs54KrgL233EW5fSOIreklHzPM/
            =K28L
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
