machine:
  install:
    disk: /dev/sda
  nodeLabels:
    openebs.io/engine: mayastor
  sysctls:
    vm.nr_hugepages: 1024
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
    match: mac(link.permanent_addr) == "6c:4b:90:1e:6e:3c"
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
up: true
mtu: 9000
addresses:
  - address: 192.168.25.112/24
routes:
  - gateway: 192.168.25.1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-worker-2
