machine:
  install:
    disk: /dev/sda
  nodeLabels:
    openebs.io/engine: mayastor
  sysctls:
    vm.nr_hugepages: 1024
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: eth0
selector:
    match: mac(link.permanent_addr) == "00:23:24:f1:07:cc"
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
up: true
mtu: 9000
addresses:
  - address: 192.168.25.113/24
routes:
  - gateway: 192.168.25.1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-worker-3
