apiVersion: v1
kind: Secret
metadata:
    name: freenas-iscsi-creds
    namespace: democratic-csi
stringData:
    node-db.node.session.auth.authmethod: ENC[AES256_GCM,data:XuwwbA==,iv:4NdLDcv5g961UJ91uaYYIx+ltVx32LUBSIUQpmj/wSk=,tag:Hv87ZZqLWsrcxCXkBnQcrA==,type:str]
    node-db.node.session.auth.username: ENC[AES256_GCM,data:ZAL4wAvuOg==,iv:qp4flf0cQoA1/1tdfmMqSPwImBZaTh2PkO2NhOum4hQ=,tag:tm82j1jNcMy5hmLJ+fT9sA==,type:str]
    node-db.node.session.auth.password: ENC[AES256_GCM,data:SZsul7z42crLPVVnJiNw2g==,iv:gl4QkTq2GtEAutp442e/K3arw+qoWIh9LsvLgTdu/mM=,tag:uae9TGui+r0oXXmuOUvnhQ==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcG9hR0VnWlY1NzI2RXlR
            VE5PUXlYSHN3NkpveDlyYkJUOTRPSEYzelhNCnVZLzVRb0dBK3ZWU21UaGVnbFJm
            aG05ZVJxdmd5Y1hHdVV6aTRpVFNBZFEKLS0tIFdwTk1NOHJvOEpYYlpLWFBiSVJO
            dUlXRE9PNkdWWmZ2YVB3M1BUek5RS3cKeGJuO1ozTY369rnDZ11+ULI8qiJjJcxg
            l0WaKA5kWPtxQz94nn1lL9eMehzMGmWtbhTtju3qJBjWbrB+8xrcKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBczRSVk10
            S1JCc2hQYlpmb09uTmYrRlhlUHJkelJmMlhndmFHdlFnNzhncApreTkvQ08zaFQz
            QTg2UmVobDg3SC9RcFNMWDFQVmV4U3ZzRkF2amlNZDNjCi0tLSBlQzFFa2JlWEFP
            YTNrOHVoN0JKSStiUVZSVnBZZVhOTHJNK3V0bWF4c2lvCs7OTlGeQKFPDfFZC3Nt
            +UR6+sYrU1/KE2OSubcJu65nUmcHXUOhwhqR6erSBBgs7Owu4icgxkfRRKwRbV2a
            RNU=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBeE1zanFs
            WEJnZmJLdjNFalIycy9qek1DcmFKUFlXNlY2RmE4VnZZclp5agpsWGNhWnlXYzFp
            bWFxUUFtMDJ3VHFBZUF4bzdZV2FqRXU3K0dHMW4rdjVFCi0tLSBGU0ZVeDR0OTJv
            V2srUlFYeHo0NW50WFRZTitLekpGbW9sYWJqT1p6TGhzCsFbP+b18Cq1s9zYoCgi
            qcrwBn1Ap4qrHTAryxy8fJhbeVQHOEf3Jo5mGPkHVtGZNdUhOX1XYMPXvoAcv63D
            HWc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:Ia/3SL9t+z8LDP5PrkvhMaFwCAvAUENBVSOxillk4MW/MjSbXvJ6JpaL8vu2WARq9ceQQQWxT3p46u86fXHeqvNY68dVLZ9THuO+L70HI1r2Zf1xuVsxn4RFsRLDWDlbz8NXGzk+SAxWw6lxRqTXs/FyJJfGtgASPrQ5m20Yu5g=,iv:iO7pnV5ebfMQCfjlDP1uCVVTJ6dfe78lj+dqQnbWrUI=,tag:NjjglhV1sKoi9ZIlVBE0PQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+Im5NibKnckjMEVHR/Th9uY86Fi/+RFAk9KFrRRKvM4ex
            tJFys5k8EETkGDEKpcZkXNDm4A1R4Rzy3iEw/x7Acc3aTwl47Ls3a5VZM0UeKjwj
            w6KqZjfhjNJhWdgMSdt0524YNzEQ/BjfZIuuHfRYGd8ssdqh3Ng82kt64Kv6ys1H
            LZdhpZ4Ul8rTx79s8K2NAwguak/9PNhldVfZC/9S/cm3RNotH/dUQM/WGZhGL9Em
            MIyzNRDIiwu/1XEl/hAm+XiLWGPbHjWENvbJeBnwVYImt/5yded9InGXE9yCajrg
            5ojC57ZN3A9Jp14HMhV1i0Y0fFyZo6480KF4RcNAzTNLA04FXpGnd6vBsNJV+RTJ
            Rkv86WQlttswPEtkHXi2PxJcQywoM7hbyJouWk8GzXXcPrbTpGbB311IIMR4s5Vs
            qkIVVvttThVL1CxWYvnKcaYFo6kK3kR0kP7RZIuMououMPcUIJh1Tzom6xeXFXAK
            E6zZt0+AIlwfmXtYyXYlH7arZkLZaJ0SnZb8wMKw6u6ZaBVMOIVNJVviBDVA6WQL
            mjSLOfLQf00o+rt3O4Ew0FGvWnxwe8MX06FtBMqOEnroybcXKzWgH0xloyMCk3qH
            qktNEgkWCJ11wBFYhVp+i03qurdYo5f4AaQzstYp0Y5nkOlW7qoiaOlNuXvMc/XS
            XgGwdp451zX5PSNzN5xgcFcYRtQv50kJ/68TSyOnt7ljySw2UUmZVMGYiMDWcaU/
            PHlaYDXPohUyjWfu+PrWaj59HOM6hHiVZV+8e9fSm0ra14efcDsR28JLcPgFUnM=
            =bvED
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
