apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-driver
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:Lu/n1vmCf233Yi+qSdzoa6h5afXH0WGPVQgZQb9CbWfVsHqvnhEVWcoJ0F535yBOMpwZsZ4Ca0s1k917Hf2rZsuMK8pfVXveaLOnprGwDI/AysCI83ewehMf8nKunp1s7ldE4Y5kZlz9As5XVbLyOXd4i8HXLJLiKQTWYpPTlZ2f6peSx7FkmqViK5UDf1t72VVo82BDcvHRpc59h5u2PaZXYdguxLWQb7rcHwdTsVj18ksI9RgSPuX77/YY1BkEQR7iRICwb/s0D+9AO3BMz/hOYV05IGM8yXvl1dl6sVM5Go9O72wxZ7VIXVvgFOLKzspvphLm34vywCPKU3ni467iQXOPfCSU2yd4rtOL+X4hV3A796uTEh3EFkkKPKQUMMoKWEi3ZtXpdnr4DrSB65h8ktG2Atr8i7cDHiAM/C9P7+iJtAgEBuJHjQURVzVWbybW655f35PslVCh6p+wOabPWXgn8czwBV7lRydWsy2AUm7g4eNTyasZYXNE5F//jPS9pjVjRWG4p4y2YFEpw0TBUJGb7lLkbAn/gDPulWpBFZAsjHzF9MMyBMqnZU7SVQdirqwXq19VFiwsnlJbRuEAFjCMVSnBsIUgv7A5J96wdwPf5rLJjRRkJTkOJok0HhtKdfHf+/JOoOitxNyZvVq/hNO+AYE564S/1i1h8pn33pXktW0NdqYsIZtoTybWWQ0GRC62i0XaOnG0aGpPTW+8Ves8LAhXdkITcgHzFHV4DWUGB46LH9qWiJK0XNG1IXJnUYVobx9Z00xlNeNI30hRPX6HjWToHYlFLaiJbbINOZGcXGAdWZQRGfYoTK/8W0vRbo56w6DYOkhTa5wqNj/lPP71L/OD6oO/fW6hnIM8oMO5M+gVIHZ6k8oIaylkBjdspSvdRR14VOTPzufKJTXVK+JN11fKT/NOtvuuAEPX8DXhlE5JSvRPGlJdsYlB0k/7GzGCxiDzFPnUrwbeW5P4ABPReYA5tBpRp4Y4VmXt7ikh6dQ2MiFoyswqe3OHn6YrmDxXnYqwCSuPyrxchlW/qABBKCaXukZ/a3fTT+RTJ8aaJkIc5CB35tEow6xa0TYgvM6oVaTlMYfUU+tVJ2YINzfhFISy+Aeiro9QV4iXrrkUNIegD0tqUVw+T1gCCbcalluAnVEOHYQJ/wY/Ay87zXwlL6mHKTMg1tPa+C2moqyvmct/ObthgvCITC92vrSh/kTiuWvzLSB31OcpUqpYkhtSDXD9fiPO9i3rrNgnT+YuAVhJ4OfOc+7tvSBGPFIvGFcVA7fhtzQiswVhGj0NHQFT25yxWqJhPb/WS4iDUM981LnTRyG6ULTCgb0i65N2ca3drV2NHJrvrJHxd7ViVXrb2M6qkNF+J9mojV03uIAfS7eyMTsvG/wsf4ctoQwxSQr0syAtLPULq+TxiXD2q2YCQbk29h+oso0J1VpnHU0lK/p9dBhKQ4a8M+AvKmZpSyC6TRflHmRK4Jo/O/moDQSIj1j5rDz2c4fmF+1Yv0Zfx2atgvdUDHBoAvVJAH6iiz936OfKVOYGEovm/e1gkSrNPhxJ5RgiLF3xkwQ/SwvWAyB1YwtMilyVYYqee0gS89WO9fxmyK9u4TDg+YhGdRfD3jbH84VG/fewgKOam98GITuoFMlV0EQwW8YK25c36N9g1/CaYFC6nVZEQwpgH0nQiqIvZtKnXBVKq/AWcSQBJUgMJ2dsy+PO8t5Bv6qy3uW76ONWokk/DzwzOCeEskav3dprZ/APheWlzFR5ouHEPgB/Gk5ruFOXqQ9bYN+DtAU2kR0zwTao8OjYi8DTWo52FT2lzJWydcCJYUYsemVuacvVMcvX9g8EMDLym+gXL+oooaUIrGdeptrZh8YNGVVStYjixR+UVF70gryCO8tzPwcoDmcQRuOH2+hp7rbORnqJmp2t6seGIISuVneHAzj+yXmUSPACrHx/l+HZKlQk35S223VMpR14WuNV++ej2zXrKr72nYQ6n6SXVAFHsVsRt/2KDLAkpEmm5VH9+UjM/QEWyhpuFt8JJk0cbOH2bDWdsvY94sZEJkBtaRHePeVzTHMNUJyaLIBa+9/SGXfy1JuTy7cK7IX+BdqU25qaW+fCHn5g0BJQR6sQSDXsVGEMRP944saEsELy4szSAFgJzAea4kL1mUls0FiAXzfJqxN7d/dGSCio363Juvk/ZI8u0M4Jmc8kO9q9NAu7JvFe6M3bZiAoRHsirGdcyh/3NplcdL2Q+4GWzrdgwAzPWjZ9gwmegTar2++eZSNkH0AwZZK5vSpVr5RA6nJio1+cn+SB6ODQXg5NIPer44Zvgxir2MAcr0V8zxJ2qRfiG6T2sjc4AQlUAktQTLaXWNUkrOEED4O9LVgoDYYgoaJmLouDRPw5gojYNK/+r+yhPp2OixsrJT40FCCoM3zJ71UCva28Q/JfFMPFu3Bu6cjpYWalbjdXY2AeHSv03JvQDvf474I5Djpd6z11OuxUGThvsdhNZObxO+E3FK66Ku3uZxmU8Cm3Rqzdv96D1OEzqgOPxqUJ26jaSlQhhyDhRvBl5DSfxsREZ+Yz747Uaz5l0HrRkzWsb5M=,iv:TXM14MZeb8eOHjADy6yjvuRhRM73UxrhZM1AX02FW2Y=,tag:aC9caiSIU//P1yfxARYEkw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZEFPV1VsTWNJOTdsSUwr
            V2hyMGZnUWgvR1ljaGY1eE1zVlIrdC9EdVJBCnlEekdHZUZGU2FHU0VVV2N3TktU
            K3RVcHNmRmVaelZLdGVGb0FGK1JPNmcKLS0tIEJGM05ERkpvYVBCbnZqa0pRQnFD
            UTdEcDlMK2pzYlB5TWtkaUVyQzQyQTgKoCLDxJarB1687Gb+mjgzSoU9WVehqdsA
            UT0Go1r+9wHPnSO7HYyj9KakioOEhUA0BMZREYxzQWu/Z/66iYUXHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBdTNJc05r
            bFVRbHBuYUxsU1dIOW13NTNjVDVMZDBncGJHcjA2ZFgwaWE5Ywo1cms0UGRYcWNv
            ejVUVVhESno1MHJZa0pJR1E0QWZBa3lNT3hTN0RwN0g0Ci0tLSBEUGZrcnJpMFp0
            WTNVNFBoWWJYb1N2VDd2SjEyN0hOQXZjdTZXTXlLZy80CuNjmTqMx7Y/ZZwZ+1j4
            vQpet3Ao1gBWUMaz7PuWwUATaiiqlMj7WEBNBt7mqAQfuPD1Eh+vbGsJ2tCkMG+N
            nq4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBcVNxYWtt
            aGtnVWVWT0ZWUFdSMlYxVDJmVHN1bmdKTS8xZndlbkRvTEt2MwpNakZvYzdUK2U0
            Q1I5eUZhaStVL1gyNUJ3QW5MNHFoc2R0V200NUtJMG5BCi0tLSB2TkNEM0lNNUkw
            eld1YUNFL3RuV3pCRDlNc2dOdDR2alBjdUE4RHBCT0kwCr6cD6zaSSKqq4bMcnEa
            Ki/oatj7TqFG/KRKQM2I6deLPnnClOuTV6yUub7cqEVitKazSdI8m5Dfqmby6v7B
            I54=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:jUlKPmSobMuwKDZO4kKyhhTc4ggjju+q869Rw9HWEvvJaeoAloY5L9yihGYjBSxWOALcRoJ/Kho0eQ1Cql1+7McBhUcv0BUXKVYOIIUj0KGTAlRMW9rYZ0blcRPETEY/TyW0xphFGKH5TsuNBxadQdzMPHPO9j2SgGAXQufE2T8=,iv:WoyEbxG5ITiHfHfVFtdtL5HhrZ002MPk8Dn5bzbxkOY=,tag:+OirlI3dQCbMV8y+caPLOw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:28:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAx5trvg2JmHDZ7d4Sq5wIgqfUfxt7kYJjkUcG12SONOqf
            ecqa4URKaIFKo6U6jGY47reQYRLluRr+CdaavPVpenZzUiL7jIpJQQdIDkJSNMta
            Pi8mo0SiAZpbiPFlwriJQjxQhV4Snoqv4XGEF6l0cbi2MnurvDp7NYXrk4gx6Bip
            TiYfqDOQT8RvOF/9ggMCN3m8bFjNSeBYl3ID3jAovK++drC0Sv6od0Zv7pss0MK1
            igEYyf1KWRCAsr87AW6you/ku4KnLBUWfozJgYjno1TNSi1/U3+1C49rFT2bPeTp
            Id5YfZHvM/y6wmEN6y5V+z4kW12+mxF1z4D2TqGPwVxINOpLJzYoz/Yy5ST1qVFN
            c1PWJf/KWtIqQf/qJYEyiGfhMsHjW9iMZ8pHg9i0l8PyUENgzuSyvA1PWY0GHOpo
            eNmx1IM480BSPqFYe4jZLmE2I8+ZO1y1ku6PFuGuNgxdqkYBBhhHmj0VQpOQqcPX
            2Wn27FglUY34qXg205b/CS17ZQVZoczCmbXZ8IaFlgJTOFD9utfVqOwf1d11sIYj
            Doq+YxvXqKh9x/2T4sAj/QeTeRLeMR4jbnjE6EcFkIg2/JltEi8UGfDQoPC3fc2t
            7+AF/qIYxxAfsiahW35nJ6l3SpcFarmA9FUjD2cq+FnlW3XSGXFJsN1/9yDkdxDS
            XAGAAYCBJL4RjihHSE9SncQMeXtZnAD+ku6R7Niipsc6BnTM9komw9kgSk61HL5m
            s+ephLf1vb0m6+9pkND1J1bM5gSkfweenkJMCxFdO28NkzXBdrmgdCSmYn3x
            =QSep
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
