apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-s3-driver
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:R+QYVZB5dzPidt1+68OvQEexuUcFleJCDQbfihGJdnLuCfk4oxDTYRgNJHJOojyHg6KVpS6tP3qi2pLh3zYly2Ou6NSzJl7sjK751kgbdMjpCOSE3cZqroAryezHf2Apb3bRTEnfsLsUBlv9BEhxWR86SBXPC+PqMnputyVZZ8sMTKpt0/kdaFryEmzGlQmpQOSZy1nNbPNHnJwKMVjMsOylv1ZMl+AEX3f9/uze4pfJypGVV7SA4MDXGTPezmNgCP38UXkHTCTldcP+EPs7jfZ9GWKL7zYM6NyA2RJYQnF6K0TMCQQ75PprL0yfj1P7zeGrGemwLJtzHQ328YaG7Ww3kW+V+KySJbx0KzcDDBpntvsqUTWla/QQ1+tKpdYHGP97n9AVMsDYUauNuVIXdSEq5cvGse9EPV1z9vTwoT+7GPE5KmxjHuQPKcUP1mH4Cyuv8qVZO/skhKZakI8A8bGKXPFiAhWxy70KSo1bQe6/7nEE8+4KU3j6JOCaDijgZ4AI1//orUULEmhFpBAZSbaroa39StNP00E6PlN9e7yDh7XgwTFhoVVV3+jXd1MMGTPfSTLY+XgA/kyf7AwsYrhRLIZHc7/nYVi1L/5hRforkeBzlrQiBfWrvz8vm8husqOAhNSrZxCJIpzn87kCcXZimRwMVc2hpBTIXubXSOrKGFP0m8itwMM8yM/+Xvdl3eujR+iWGMMyVika3V/2DTgQvUaI/wpUy+Tc5IqAyHd+VBdu0BM+8o3ESZvjJL9OZCoxiZpuq3SLX8EpZrugD0Mfv+nuih/c+vwK61du34AHJ5NrUl0CozFzWWBJjIhLA1GboDPb1DeQkbyiCR0Bby0doaw4YkWtxqfv/DeZe1Z6wdcAv/fVIFwEuWJM0OgLeDjiwVRQ8VcTiJGNw3IXdxMiLu3gyeGfOwh5AT/XaDDI8VW4VY37AEDHndBmldxb0utyR/dTjukc6M2XfYw2dA+t1fLzpZ0ONtjqZKVpB25VMyAerIeSX25HKnR35Gn23rgfo3O7F6NXeSCUZymXpPcbpIoLUfRq/VEZ5+77SVrnmuZE7N6Fh45hJIaNohQx2HhbGliJGvkEPdKDB7fM87ESlaRlCheHrPNTjY6uf13POdTwpg0UqJDa8J/fyhIedpZjEZq5Fq2o+S0R61eO+4zlnswlKYTiYBVcHfJdcQPoHQZ/m30xnzwywHqHHVzCsGtpiXyTLl3zg7FxwIGl74XPxjUFHAChMKqJTNAUB1VTNV9Vt/TVmXMvtuGcXcfFuxXTe/ZLiaikWzYCiP7osMr586BuSEVe1VXy7RJRmPjTOsn3GjTqWTHx1K2RAhf+9Bm5OolnM7PWKM9rsBRZ6bSxMzi9ggLsDA98C7PdDTsnMyK/JmsPLyInb1Vdx0O+Minis/wB2ZRbAnnvQxQSSd12tobhYrFdAE81Ehl4zRufZFmmMmk2XEpcBT5uXFxYtBB1kdsFxeJWovJIVvAHWYWE07FkSr2phSVtEj7cj75hguJL5hk2a8chAw1XQkl7UBudclEUeG7bnkQqYSsSBX5kbw36A+lfyfn7DeZw5OU2ZDnvr1cN1o9sy/xDhaiBj4zLt4w/xXqzm+IaNqBeYzSV7t38N2DrKNW8/uLPta0TyeYHziHwKXRpeoh9X3ukppuCRS4nsODyGEeQLYoLcKnV6NL3dKa3NSDJQpeBwpEoKNtahd6ON8JmPaOmErLQKGXQ3OnidcYdmruqy6jVNxIkZeRz6ESLiqu+cyu+Ts7OEWGGm0WVrw5Tr9f2APOJz8O+w1bl0vte8PcY65aI/S5QfEilwW5Ct2A4j2H5f/O+/hYwEIU8/qTzz2TFKJ1YiijO1eWqaK4NEmz48hXt1yQzTmKtlOlF/ciKOBJJDVnEs248UUqV0GtVuxIldExeqcsPS6A4HWgycHeGgRUSjny29l3uP7mN2v9a0C+LeD1nIvBk9jzdzKP89EBOi5Qu8z9F19aD2qPUGwgG3POWoLE7xFcawaha+4OpX+o+dHGSKzpL6FQ03QKhnCL3wjq77O7yDSmknCbvvXu3Im1Hhh7mLcSKabzKuBkPcR7F+Gjmt2GGcimKg5ZLOnRLG8JACP6eNLDOJK6JeYLTKugwNIobdfynhtu3GfYrIQIRzC+SN8HXWWQ4JDDgo2BY+GXGkHai3ERrQk3UaCTJZfQydw0lrK8nWHrtdWSzoND1G/ChrRGuaNNaPMwqlyQlKWlBwfREar4W7EEJdhRO1doe5R173fmSVm6q4DjKzLZ9sXpfAp6wJS3Sn402q4D0mgDeSHDMuyCWOHOexWvIJUhVgnKAVKCTAiDTLnddfFysm2u0XYXneb9HTlIukR+l8oCKhMGSwBJiXHCeyc4Xk8HMIE8HXM1+6K4qhYWP+iyegOANXcFstn3bdr0Iq30VDkh8TIVqKoi5XSHgFCqQDWB6jaMuuPE/7GsJRQ2dhUJXvLA6lgm2Dqd8vfvi9u9wRK6lXdIhVovjqH4TBC4wNGfrNc9XwEgHQlzvyLKeFHP7yp+06ZqaIWwUcskhHXtuYtxm4ODZ1VAe1n1S7auWqPIe/DVZVsE=,iv:zO1IkJ/EnU512PGIWIJn2OfcCUVxLw23lU6ErZMv3cs=,tag:z79Xrl2aP+J3slKL3sZrWA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbjBvdSswdjcxOFhxN3I3
            T2lGK200R2JLQlpmZ0lFTVJkWktVN3VqVXdFCnVCRy9nM1NlcGlHWDJYbFZHUWhl
            SW1GemI4NG1aT0d3aFpkZkxjRU1mWUEKLS0tIHRQaExMR3ZHaklrcU5XcVVZaGY1
            OUI0a2dOL1NDWDVxOERSMjBtWTI4ekkKxgpj7ZeTwoV9MEmeJTQt//AaUQaSSg2l
            HuOQ4ncEbbNQ4d7KRI1cAFs7Rkuw7VAyyV4G28JOC7+6tX4fwafvFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBNWk0aTZC
            eUgzbDNUbzFlNW40bWNkYkhxb2QvaUNyRWpyUzJyZkJYbWdEYgoydFFHZGQ3RVl5
            MzdSUkpZTmNKNUYrODdpV3gyRlZlTlRXVjNtUFEyV1A0Ci0tLSByelYwNHo4alNj
            b3A0WkVGWlJ3RWQvWHhDMzl3NHdNM2pkTTlXYkUwbXFZCluImUkPVR6ii83/Xsv8
            NsKZJlMJlGqBKHRARYUZBr7WtzkcVVBKHdvFU44DVe0SX8b1P63MgcZli3tpLzDR
            7uI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBalRCckpn
            aG5vbWlHdndKdEVuN3l3MG95czdCQkNjcVhhUFhoM3pJWVhhYQozSVN3R013WDJO
            S2wzYnZGZm1YUjZBSUJjSkZ3SDk5Znl4blpwb21Xa0kwCi0tLSB4U1QxNDBNbnhv
            Mzl4UUhwSENHb3ZVQmFRM2tCY3V6TXN6S1dqTGk4aUlVCjdTzpr968bb4NhNCUmA
            2PR5o8pi1NL8ERlkR990xxupyMb70B9dFRtjCE8lSkOVcjy6GWstcaf35hq+IhQT
            rfs=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:HMbciiQyhEzsr6oAPFPCDWPuHg1wxKVf/14yDbM9wWnZ0k8cSiEuugufLlTkO/UK5H+1e+rvEocWXtNzd7Q2AJ2eN975u6uTHXXBr0s2kGcF4puq0PWry+rYWj+SZXUuGljT9NZyQmDzUd4UNxBrREiIDRglKJ/x2KIcSBrNB4M=,iv:Amr77iCvIOyzAHZUwCkL0gXQ/4NdyxLGFJd2wGXDO+M=,tag:LJzifFB8uGVCQBHU6k90Pg==,type:str]
    pgp:
        - created_at: "2026-03-30T23:28:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+IcvuNjSxyVMZEW5pfIzNrCha1XUTLF7TtErNWchYlcsa
            Pe55NSblb+nPqiGbcCOwBfZmS8XH0LBegcOQ+ZpCEVTW4tdKBG9MK5DJERzbbZg1
            rmi/aNtpwmCF8njB3azjEoC9ZBeEVnSF8n8V+zHVj9sHWagbWuZwsh/669Wp1V8W
            ufsVWw3I3DcLBsJTjJiNGui9Bc3+kCJ48gPyjLtcOGBAbxOW0LqAnQGhZ3AbxvLa
            MhfzKM57J6kXE2SRKSgO3Qm8+nVkXGtBXUsCBdp3Kqmdd9Dfd4IeuZuG6PkycnL0
            angOr+9gR56C3T3JkGJRzjn9ckQgHvln592BQ/q5yzCW/ZeDTYZybPi0vo/1yhnJ
            fps7K0fyKHprLY+7cblBRddU4qt7eca2MnFnghFkkouFZQ2REqZxZ2Y/BdsKJEV7
            5LV+Yx/Ov9mWNqvxK+JwuT2Q3c0/VNA5Esj0XkJ1D6xRlhLdMYhQ0WAvLb/3V9U7
            dPWZk278jNKfh8cFoLWh/+v1Kgnc99/brISpqdxtO2M1loQ8pw3fQIuoFCJ8cT++
            moLhK3MjbPmykCLvOpuYKdaSScchUSXOneDlkUqptt1RGDSC+Pc0tcd6iAqY9p0e
            //iZ2DMaANbnqg1RYJc4VK3NNdJq7VT1c6j+rlk4GjQ2QRRmnJvDN6hsbkSRXwbS
            XAHb7KriILFSll3DPz0+0AWdk0nFGnDaJ7RrpYxixZjAy8kpSDLmUQblU+dCsFbj
            KeKUQd+I+G/G7Jax3CamRnRijUWpu9PB8oBLrwsN5jNlR+bslG4YdsT7MztB
            =brfh
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
