apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-smb-driver
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:AzcWJBYFlaJPeW7Ql43/j+EA9lec101VdQ6jmlaMullpVPDM7+WnWMO4zJzp+IyAGsiL3byi5GAcUzTd3iCXnPKp+8779VXY2uelpnh43gERkbh1vbofisySO08zlp5bK4wah3UeE2xqi9I7DnZB5Zrhs91efmeXlXeEm4fY2FQCYrWY20y7ixiJjzW3CRVHJZ+KLG5LwNRG8AFrCmwUBHx6G4OnPvbpucRuwISMUskCLKrGcrRt5Ez8T2PL7A6/8f+r/nN0GRFMNuscL6UvjM1ZWBrFobfazW7ltiRqJseQ3NUgUrzKP2UBCO3AsqFTqfQUMRYe2q7cfhumWGeR9wOsjPzC5f21jBvX3xTE67B5qHrIr1l2zI22UOEvKapy+0wOd3dgS6D+PpetCxMOHMFWDr6IV0EdyMEYyivMkBG6WQj87HVTERT8D0L1cvP1UjRMKbsvClhZC4s5BSWpjXPi797UNEXX05S52kQG6wFXUQUL5bucgrRfmcvvGQRlKtbb7v/wGk4ZUmyHufMop+v+jktajdMkUuc+tvOwd0WXjB2T6uErobSZNccd1bJWvLr0RkX//PwvTpuGw+EhUzDRjZXBbwbDc+BBp6N8bBcCvYMULxXypJwwEnS8x3nTb5tUTcFbTbuVVB3jSWUuDoXucC0yzQHRHOXRjjldiLyz9lupWlyLqv5gzFsrZGoiusnP9DvCLdmJdMsapXiQput8WhBsyHGuLpsFEI0zCG2daX0vP2DwKyuHNeKybrjBw5seGZQ3MVvc/MK99wwnaJCraB4xcESu2SSBBjTG43YzPGlXVsdl8cHevTQGBFTLpmzFBFP77iYOY00Ttb6YLQzWlqIO6hC8/if1UxHn6pvVdqNImzD6p8LU0A3FmP4fjO3aepMDWriWfKlIenph8XXkaEBcZXRUXBgMdHyZ8flkcPZe9p4y4eO7reomApHO8LxYwmC/jf883/0D/AvT3kRXuyvxrzq38g8BFY/QxwvYsrpXcASsdUDRv2/xRYm/vxEYiKRDAffc9/X1zASWFJkj2a6+CP5V0mbM74tIuMiEBMZa39nm2tZD8+r8qKW9N62doV+4gLG2b4oYZ6zn/5ROSjTllMKm6xP6ddALjYuH1jRje9T8A9/fLLlRuf9a+c9HMrlZrb87jLjwp4M8LgS6tHXzyGPDgmJfUs6aVHicapQf9sB8j4QPozCeneGdWIPhZEAhYKV0P2HOj/MyRzgWaGzIS4GwX5GllvXc/ecD0ckbiBaNFWnZcCJdcErFAiL8UrXiOTL5G7qeqkh5DqGV70bbpnAu1h2kerC4XTnrGHUAQjWbZxaR535PPAUO6RsmiKxGRxHS1NZ/e/8n/r7+Yk3JTcMdrneBip0aZPVDJ4u8rTrFGfV7C56SI7h2hlw8i5h8a5NZNgUw7ovr/KqUksHOQWtAEPPGqIddph6lsSSrqTvrcEiYMK2Qx7P5EBCdIctq9oqieZ0wd0ztaVETPuzmkIO89nfhJcd20lzFJuyiOd5Zfb4QXrLN5H62IjavfZBlza8jhbTMabPwD6Clz5mpDee1HeojlAKX5FmR3t2uaxbsu/tln2YAMC963OO12KEr3bilvszIi6vEH2j3mhMqTxS71rwJB2I8NY4UwqRGuYZuVHFWITAnDOWZF5uRLLD7y8Osoc3xyth8ji0CuQJpjqrB0+Be8mI/UFSk/wi6X7eSMeKw7dcxIAjeiVUwsi5Q1tcmCVlG8h3qWpHvnTDkxPYAm1mn/B3mTpyVZiz9Hg==,iv:kEdoHbcgAccltUijQsA15GnucwFXVKZiNShQkXThz5s=,tag:NYd2Yud8qVtxVoC8szmRZA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRWpxNVVla0JxaWhtMG5Z
            Z2l4UWZHTGtXdlVHaStXbEY1L3B6dEU0L0I4Ck0yeFM2amo0cnI2MXdOY0lGQUdZ
            TnRsMTF6TTNoUzJJS0JWbGc5NkRQRm8KLS0tIGp1VWFpUjd5MlpYQkp4T1dPalhh
            b09iTlZ2a3NNZ0krZllsS2wxQ05xZ2sKwRi31CMa/lOTzY66d+IycobPpqVO//5F
            yyrGru7Ho/2KTvWRhZmuyZ/sGXIwCS+MMBWcA1ic62tqmYAhJFQIlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBOEhBSVJX
            T25zbUIvSkYrUzBvM2ZMUHNHUGpSZWNFRVJHWk5nRlRqcDRVRQppNDJqVHRGdm1i
            bFF4d1hKVlNsakt6aTJkYWYvNW5mR3YvcmxHbnliTGlrCi0tLSBDN0ZWRDU5ZjVm
            RnBlZ2p4QlMvL1JnN3FLckM4N3JzUGlZSEV1WmZvUiswCqlFB/lmfNxIb1bNwbSv
            umJoHRt33RFKvqaGW88BZxj3q+mjo6VsFfPxZUxon8G8RQq9hDOBeQuurw3w3eXp
            X7E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBMlpIYlNK
            OVduRzBCWHo4MWt6N1QvWS9YQXpvczYwcUxOUmxQTkRLR1dGaQpXTlR3TUIvY1hF
            QWFzVHlJbk5qQlp1N00wK0Y4VmNXcHp3Tjh2cFhXcmFvCi0tLSB1dlVrY25jL0c1
            Uk9vVUM0R09qVlBnMGFrQWJzVElNL1JJOGx6N2JIZlRvChgylaHR++ykRf0NI7Tl
            uJkxKT2SBN7qo2wHtIj3cARDY664dLQLrVWMea87SQjm5s04nv2OgPxWE0Yoa2MM
            vZQ=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:4Uwq3KGDY1rLSk91+gw+Ym/yNfvT1gn8GJINN2BdLvNLebDxUyP0IqareibgZ6Wft1cHFr88kM4Awl4tYpc5e0YNOwe07PUkYMjRssTdoDt3vpXVAv1FXuxd/t/iNVOwvvUkZaC7eUvgNAG/v8OUe7GQxBxS9rEJV6tZ5AhJZC8=,iv:uhWNqv9rdsey3vEOakzxZIyx3TTwyuwB8897VRp7ZRc=,tag:mUVhw9lh4rRPPhimrGjIKw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:28:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAl6J6eUyrjzKv/V/vawGunq8dCJoD2J/jeIY4Hcu1l1n5
            9JNz/mts8ROT7CIb5SZOXXWVAoFkzAb5JLPXEYkzEfZRzHZ/KpgJRA4nf2wCWRC3
            z9iY4Rn+Ur8Zx04O+zgEg2Z7ZSX8N8f7hOphh/s/eg0hR8GfilKxFs6KvmEv05v3
            oJt3/8A1LgxQzsuyyo1sWLq16OLIpFzM+t/7dywMkhw8dbk10S3sVpzHsfHmdkzV
            sqC6tfZT1CXc+jM/BG39YlTKoXmXUEGTK4woQD062HN8sQXlmO5PpQY+OIunCC0g
            zW7AtFRIXDKeeKSDCf3JrkJtr2qGwTB2OFcp74KjKruUTm7xAQ5goO0TpQ5o8Qrg
            uwzAQcswSKhXArR7i6gdqMxUq/h4uP5Uw2Sc66/1cW3A/s9WT/BT19WfV405pdBV
            sjpd5YGFHR4niv9UJ7mshmcC/EfM7IX6zucGNJoaFToiC1x29bSQCi6pGcWnSEKD
            jh0XI7H+c761aNfbmwi2BgpRoqif4VT4qL7/VNwe41yWwheJqnixvB/mWwyhPz5P
            8KdGWyjTiLjO2Ii61mLYkAb83wbIgahXhqudiGfdZuMX54hFlhv3pwHtLKxb6nwj
            P7/+pqLqKu2Kq2n9/nH42P/nk96MvdRiRNknPWTKV/71awnZDmijRws3ieCZWDTS
            XgFDRNPD2bjZu2hinxTyam6mC/1pjRhJXI+7ec5lE9v8lWXzXZIS692V4wp4Dmwu
            xhcCwjCax5FwRdmXV8RTjqkSFaAMhSJxy+C+r4c1j1Zb5wMVdifHhpVcf18xMSk=
            =YsPH
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
