apiVersion: v1
kind: Secret
metadata:
    name: gitea-actions
    namespace: gitea
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:0aTJ+HwcW79x0G5a5R3muEwU8JRk5qPOzmAqI1Zq55pm7+CYETGG8Q==,iv:+rRbZMGDdgEfyBuINcU64tVFeo+Ra8pGS7DwCnYwXRA=,tag:Zxr95fuqRWUQzyF7qT5bGg==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb2lNWE5HM0xhRjlzODAw
            WVIzUURtemx5SXQwUlM5VFRxM0ovell5VEh3ClJaYmw4QkJzaUVndDBudURUSG5W
            STh2Um0yTnNUZ2RGcDBmRmh6azdELzgKLS0tIE4rVzd5dlJoZDVvYUFqUGpua1Zw
            UW5rdGl0NFJjVldCYXdvY2NhNUlnOE0KhS2tZf0YTsXDBpl+58+psCkc1ork//li
            A2iFFYbBQzAQDlFrhYQFl3CTCkQTk8qY7uWlTSfIgxKd1YAaLWIP4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBOVFpSXFZ
            QjZDQ3A5bXBsd0l2Q2FLMFRBSUNDb3dzV3M2NkRPUmZBMXg4Qwo4S0ova3lBYXFJ
            MGs2SWlSSUYxSTkxbUViM3pFYkU4NEJNUFlrQlFjKytVCi0tLSBqZHc4MlptRE1V
            bFRDT0trc0l0bTEwMm9PWVB5TkM5bHFmcTRwV0RrREs4Co/QqNJqA2RTZFBw5AjB
            k6fw7RzoNJXFeQ5/VhsdcrrWgHqLG6t654ezQCv43xh3fbLFbCiuj34AzAM24UP6
            CEE=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBL0FnWStR
            NktFRkZWc3hrQkNBVW0wOGxKMDFqazh6dzVnOS92SUgvQUJCWgpaeVI2Q0VUeFgx
            SkdscjFNazJlKzJkYlhITHRKWEt3aDY0aERKZlNBcWk0Ci0tLSBTa0dhdEV2Qktz
            aDQ1RUJzMnAvekhnc1pncFBjZDJSSWRjUjlnVmRUeUZBCpKQL5Xef304W9Z/4fwC
            x7E8cFvBlchJlClidTuG+KPJijAD5y1LCzjNfeKFGpgAgEKarqkxAGjxfQZLs56X
            98o=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T04:54:04Z"
    mac: ENC[AES256_GCM,data:XEQPVj7qVmxrNqR8mQnFglMTGAHdreix/EJztv3UIIUgYYi+z/lFmFeNgmg6AvzZlbnkrhFA2JpQHCDdCmXDneeq1eV7SfHfSD4JVIgbydPouBdgbZfz3WrvjKvyDLRWP7WagXN3E8OUv1+RldpRPWO4Im+uqCOoBAz7ac6lqns=,iv:Y17vY1zHNrfivlG6X672d8V4OVcXY8msHHLzsL9251U=,tag:2vLMPGhzmIrD5mLGf2+viQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+PvBrX0tkNJj9klD/ISsWp9hLdKX1MrIEPKzEGsEsU4+P
            1GqZKT93qBBSGIAeBhWTLSgHOmzMcy+il39Qs1C7djOEly0+wF6NwufcMr1dyN/P
            wTzC8EnjiLDaubAUat4BJntWqaQtKDdKTPZkOEkknXrwfLQG2TDsGXo+mnU4nVFJ
            VpDKRg4ewX7AlWc3keLzZc7w73MNWTcxFJdAVYcyPjNCweYGWWp8WUOUr+O9Zp+Y
            mfvn1qvi6SS8QH9RCD8vAzhMprZi0Y/tkdHMH6Bm/qhqexfg6CgUZz3mkOQdPI23
            ow0nLftHD2mdc4LA4b6tEeJIMF8KLhT8s0jP2c7sJpKxF53c1FghBms7i3hnWmNA
            Pn1IyTIjc/116mRbl1BoYiFZ8T6v60GoLAtHA6sgJjwm5CcEveJ1Tjfnv3ilZooi
            PMlC1b5crTwb91RFaH9fhZDm8/edNv+FKFg9zGdTawELleExL0lN9tFGsEc1wwnN
            cCQbuIrJ/zRk4myDLyD/3vwhfdjwGPtp0tsdSYPEeZJcWFnLUU+A3OtlL7mQRNjQ
            t+grTPhJIgyY4McH3zduY/mRxuFW2mFDnWx5CoBX9I57P7BYijVxavLy226BJNQ2
            F1+zt7kFCRZfZF8ECrcyoGNqarYYM7bDJCs9navdYD9vMDf6sjnwiUCsrTtPTIPS
            XgG+Lv43dlfBS7ntVKe/KvipLv4PeaUiZCprOcsXl4VpFBSaZ1DigrSw3rBq2D/9
            b2DKiMldcBBtNxdZdPwePvCUukTVaX/NjrELQbg874ZWM9y8rheYI+4+aLn7qes=
            =QKia
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
