apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: gitea
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:pUxvOuFr8ejq0EVxKIxOBvmbFCpCA9Vxs0NQKTJRr9AT4e1sl7nB/w==,iv:U1UOLTR7tgsFFIe7ngpAHWlNKPHIhvidK2i7r+5wFZI=,tag:CXEtJPVrXyrmDnpkcZg29w==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:FTcV/cwwZFUYidVgceWMLuV8RhYns9KY/XzYrxFs9i+WYzCFQu8TzH1Vfo7E+OJ4UaIrQimux1QReqej0i5wPHhE81KPgOvKpajlQyeEd3CwIZPFujKMUKTiX/3A,iv:WO4zC16/CYEDssUsICdUKddTj4i61EBN8id+aRDGiIs=,tag:1tLnwga2Lk37j5DSpoqAew==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNXIzcC91eTZBaUlsWFNk
            dFBraHpVdUxuOGs1c0lCd0pKNS9lNk00WmpBCkw3WGc5TUFhUTdYVEwzbkF2MmIr
            dVhJeU1lT2o1MFVkWnZ0MkpJMHIxeDAKLS0tIGtZVG9WWTN1ZlNRKzBKbTZ6bWls
            YmU0T3k2OWsrU3R2aTZpZGpmeWlna2sKqSzDBLqpvgzxq9+v98vAFhqm9PM43lvp
            FVkIzz5Z74cKxR8IhQPEzN4PtNdfgQXgc1dd4l6X786cFJ+UhZPipQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBeXFKZE9h
            ZGg3bTNLNnFDK3BHa2g4TU5pMUo4Q0lmQ0ZJekdTa0JFZ3NFegpSZmkxWWZqZndJ
            VnB3MHRZTy9vNFNWeDdjZzhGTEQvc0k4dENhWTQ2N2FvCi0tLSBPSkVGZ1J3Y0Qx
            NDJDV09CU3FCa2ZXbkZRK1V4eU1USTdQTHB2NlNmRzg0CmlSHsBXMYRzZVtmOJLR
            XdujNXHtGxZPmxIYUipmp8WJ02oGrbP/q3NpkGQIUvbf6p39i3yNjqOQhSPYdwWE
            +Mg=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBbytEQ0JH
            Z251U0xWTkdUY0JIYnFJWmtCODhuZ2pUWXRYK3BQbEVQRGVHQwpEOFk4QlVuSmFh
            VW5Ub09ZcHhaVjd5aDMzVkxjRjY4b25tczFKK21pTUhJCi0tLSBVWlJNNXJjb2ov
            b3hUSlE4WlhPTzRucmZzWnp4dGNITStZNXFnVEQyaGRjCrT+ZWzPhasOBoI3civG
            ZWse5Vf2hZ+Zy5SPlGfwe+aLX4aOX08EN+b+tBHCthMHTd+6si2m7P9DDIBkndOu
            oTU=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T22:51:31Z"
    mac: ENC[AES256_GCM,data:j0Slgcndm9k9gu4Pf8x+JQK/K4Acmo87cnXJ6VC9PKJ9PqgdlMRjMs4bgITJe8iIQOEYPbUJzuULKKvoWrs16vGm3emrsf4pgyqXG01DMxCW7dlx7WDhMkzg34CSVmf/x+anv/WWn7LFDbLPTrxK9QSvJnGdvDyqP8nWFpKeJXo=,iv:R/Su2x9YvqMc5bTJPwwdsqkZjaq28BXJ5jHB2HAJ2L8=,tag:wMCGUdS/HITV90kkaBvO+w==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAArGA1bdFG+m1CVz44GPn+nYmoUkD607u+/W5D9sPOZqVs
            ba4r6aB8PzCmamwoFpOCJmB/8VRb/H0jmrJaIfC8xlFQPy6DyE5rAHrOC7GNqd02
            0t1k6O2lyfHDieKYnE/P097V4e01M644ynj6ePgUrwcy2E1rZ7rzOyLCdLPc6iKj
            N+DWsWz9QMr6dYUPUPFq/GoSYiwUgCwr7my4BVhFW4Z+LXkkn7aUofUL7WuoCtGo
            EIoG2a3kAUVHXURnWTZg1jvxKlCa91OAY439DQJUkVJacUkCvWU9ov/5xUJCbFHh
            LplhFqpISiOrDnB8lmWNxotvpOQl4MP4BeEamXm/WFPsJT1oc0rF7g17FqXGv5iA
            8ZZrtZQqPZ2Aj4YNZ+Aj/+pNSsPbiQN5jX5FDjNkQibBTJoZAF461eprKOXWdUD2
            eNhR6cQnFDUBJCCLr8NNIojiCmdW9AOig6IFIgkFAlQWHslWdXiI058/Fhxnii95
            Bh5v7Q+l3wm3siymE653sEvg6cTYzwlgcV10k8udw5pQ1SKQ5aQPspZqRz6m8BLM
            c0eTSzmDD7czXPXuBLrR8nr6PDYWUNLG9vnu4BxwLICYPFaAKRp2TAdsfjxzcN3y
            ASlQwIzXhbSQGims5lZRWap+AygcLunrx10fTf1+ohVTw9IO+0C8e5wdLj9VQhDS
            XgG4EcqriNZilA9K7rgi2KqxHtU/BMBh5OX0OClOm2ZkyAq1/IbYwcMOnJtFZvKa
            Wzk2RJdzotMH9RBboG5755DWBFxM7tGvnUhzgOpkXKVA4f2+dknyi3kyUUjMH7g=
            =JtVl
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
