# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/apiextensions.crossplane.io/compositeresourcedefinition_v2.json
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: edgegateways.crossplane.emnt.dev
spec:
  scope: Namespaced
  group: crossplane.emnt.dev
  names:
    kind: XEdgeGateway
    plural: edgegateways
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              #required: []
              #properties: {}

