# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/apiextensions.crossplane.io/composition_v1.json
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: edgegateways
spec:
  compositeTypeRef:
    apiVersion: crossplane.emnt.dev/v1alpha1
    kind: XEdgeGateway
  mode: Pipeline
  pipeline:
    - step: ssh-key
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            # vim:ft=yaml
            {{ $compositeName := .observed.composite.resource.metadata.name }}
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: SSHKey
            metadata:
              name: {{ $compositeName }}-ssh-key
              namespace: edge-gateways
              annotations:
                {{ setResourceNameAnnotation "ssh-key-generator" }}
            ---
            apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: {{ $compositeName }}-ssh-key
              namespace: edge-gateways
              annotations:
                {{ setResourceNameAnnotation "ssh-key-external-secret" }}
            spec:
              refreshInterval: "30m0s"
              refreshPolicy: OnChange
              target:
                name: {{ $compositeName }}-ssh-key
              dataFrom:
                - sourceRef:
                    generatorRef:
                      apiVersion: generators.external-secrets.io/v1alpha1
                      kind: SSHKey
                      name: {{ $compositeName }}-ssh-key
    - step: digitalocean
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            # vim:ft=yaml
            {{ $compositeName := .observed.composite.resource.metadata.name }}
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: ExtraResources
            requirements:
              sshKey:
                apiVersion: v1
                kind: Secret
                matchName: {{ $compositeName }}-ssh-key
                namespace: edge-gateways
            ---
            apiVersion: sshkey.digitalocean.m.crossplane.io/v1alpha1
            kind: Key
            metadata:
              name: {{ $compositeName }}-ssh-key
                namespace: edge-gateways
              annotations:
                {{ setResourceNameAnnotation "ssh-key-digitalocean" }}
            spec:
              forProvider:
                name: {{ $compositeName }}-ssh-key
                publicKey: {{ (index .requiredResources "sshKey").data.publicKey | b64dec }}
              providerConfigRef:
                kind: ProviderConfig
                name: digitalocean
    - step: detect-readiness
      functionRef:
        name: function-auto-ready
