# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/apiextensions.crossplane.io/compositeresourcedefinition_v2.json
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: edgegateways.crossplane.emnt.dev
spec:
  scope: Namespaced
  group: crossplane.emnt.dev
  names:
    kind: EdgeGateway
    plural: edgegateways
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["cloud"]
              properties:
                cloud:
                  type: string
                  enum:
                    - nocloud
                    - digitalocean
                digitaloceanConfig:
                  type: object
                  required: ["region"]
                  properties:
                    name:
                      type: string
                      description: Name of the droplet. Affects PTR record for droplet IP, set accordingly for mail server to not get flagged.
                      default: mail.${CLUSTER_DOMAIN}
                    image:
                      type: string
                      description: Either a slug or an ID of a droplet image. Defaults to minimal nixos image
                      default: "231071368"
                    region:
                      type: string
                      enum: ["nyc1", "nyc2", "nyc3", "sfo1", "sfo2", "sfo3", "ams2", "ams3", "sgp1", "lon1", "fra1", "tor1", "blr1", "syd1", "atl1", "ric1"]
                    size:
                      type: string
                      default: s-1vcpu-512mb-10gb
                    importReservedIPv4:
                      type: string
                      description: Use already preexisting Reserved IPv4 address
                nocloudConfig:
                  type: object
                  required: ["ip"]
                  properties:
                    ip:
                      type: string
            status:
              type: object
              properties:
                publicIP:
                  type: string
