apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.k8s.yaml
  - argo-sa.k8s.yaml
  - composite-resource-definition.k8s.yaml
  - composition.k8s.yaml
  - digitalocean-config.k8s.yaml
  - digitalocean-creds.sops.yaml
  - ssh-key-generator.k8s.yaml
