apiVersion: generators.external-secrets.io/v1alpha1
kind: SSHKey
metadata:
  name: ssh-key-generator
  namespace: edge-gateways
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
  namespace: edge-gateways
spec:
  length: 32
  allowRepeat: true
  noUpper: false
  encoding: base64
