ports:
  dns: 53
  http: 4000
upstreams:
  groups:
    default:
      - ${SVC_UNBOUND_ADDR}
customDNS:
  mapping:
    ${CLUSTER_DOMAIN}: ${SVC_INGRESS_INTERNAL_ADDR}
blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    gambling:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts
  allowlists:
    ads:
      - https://raw.githubusercontent.com/GoodnessJSON/PiHole-Whitelist/master/lists/whitelist.txt
      - https://raw.githubusercontent.com/GoodnessJSON/PiHole-Whitelist/master/lists/referral-sites.txt
      - https://raw.githubusercontent.com/GoodnessJSON/PiHole-Whitelist/master/lists/optional-list.txt
  clientGroupsBlock:
    default:
      - ads
      - gambling
