apiVersion: v1
kind: Secret
metadata:
    name: telegram-creds
stringData:
    token: ENC[AES256_GCM,data:itEy0tTDclDquBkjp9dSNQ8l2sp50QSgryoQuYqmiR8CYbrf4rE+dgZELVQq3Q==,iv:UF2DtmHZezET++9TodcB4x/TDx0WgtTNtj33MddhILI=,tag:V5Qm9Yhpg7dinplZGw75PQ==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYVRENkh4VG50S2JoUGlr
            dVZsYWZPV2xzMzk1V3NNdTFXblE5SnRPaDJ3CjVBLytVR245bkxGeVNKbTRXcU16
            dkRYUzNwcm9GbER6MlE5cG1rRmtwTlUKLS0tIEpobEpBVnU5ZDJBRVRJanZtWnU0
            N1l2dkR6UlorL2duOW5HZThCTXFLZGsKhCam26gfTneoG59TlOztJhYPYJi0OZcp
            naDK/U9KtR/sOZA0M97CgxJmLei7XecNzZRetGaC8Sz0RM6QE20eIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBamRxQ0x2
            UE1YNzRwZzR6ekwrKzhmNUwyZmFBemo4Ynh3TEJ6UHRZMXVBUgo5bC9ZR0JzZkRS
            aEw0UDJaRTM0eHVqajB2d3lkamhRTG9LRUZRZDJZNUJBCi0tLSByRm1ndk5YTUc5
            dmt4ODVWYnNzNWI1cTA3L2xIamhvVE9TTG5ScGdETGRFCsoQRKv5Q8Fx0CLg9fKr
            hsnicIene/lKdbM8Jm00F9AmGHhRVAhd0wzFeHmuzDeBIS6fGHV1iTJhj1CV6/KN
            quM=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBbGl2YWRK
            UEZMQjNySHNEb1NCR3RldzdOTWpOODdRc1o0V0w2UWFIeGZtMApqd1VxVWd3anR0
            eEN3MlRjOWc0ZGhmdWlOQkdLVE1YNytnYlpGY2ZKMW1FCi0tLSAraTVHSHdJUmgr
            Zk5zalEzc3VneHdSSnJpQ3k1TEFhYUtQRElBK0xEbHBjCoPcPrgp2tlUjfAwe6nW
            msbykbfqz3oVhRU1iQZNt0enciucQIM1UfsYvDrbZ/M+g4+JKGVNRBNAkWK7sEep
            JEA=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:XKwnxVwmt9is/+QWS+1AoU1SxCVCmc2f867+Egokrbn85poLez3CyUILaBIZailJuiXlymzOzeZGw6JrX7LmPyjawjcOuzwIBnJI8BNtILyxd36RxC9ripBE/dDmtYIO/d32rIw8rFmuNB1GTpjrtLRvQU6BL13Wk6MpiUDIycc=,iv:suHAuOt+jUSZ6YJmgIwjsJRQlQtfRBVvT8EbkORCukc=,tag:UBaMMd4ZKWgBy80AuaLF+A==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAuEXWQ6mea8hwrE8dXVxt7CLLCwmWhelJ9BtU+AIb+l2r
            zlcld3pwcAFgxESEg0RWLRmwKdVYpDBJfw6SNvK3eHKMQ91WLWlVKUApztWUFzQB
            KEDsiTYWF/BGdxvwB/gIdTTZFNsJivVmRm1ZbFpK8DXCZjVGg1KNj3f9K1MFJjfD
            c7csBJ4TpbLCInSeXebMXo28GY5FhuHFavK42SemJf8mV5m5avSjLKk8C0e3v6wz
            tVUGryhBPhbQ/mf51xY84AKo8pLAyRhTvLzrVwg5rxINZrX8g0dXIf+Qeg1rIRfp
            lNa0UDjUUcna0K9fyRV+Af9Fb/iTC0gHhwkK3g+qZm92l1VaEgW3zSbjdLx9/X6l
            GF8h55OGeLam4KFyP2ZUaUeF96Qa6oZ2NmgwvhQw8oJ9fiQJ5YI3Z7OvtTNi1Ie+
            5fQVyxGs+SJkhJJqLzqgizA1WCNULkfDPmRTUJumDuRxQyuhQZHwaPKXZs2iBqSc
            a289zLeaext9nyn3JppGl7dICmoTKKzTlM7l1Wz5TlwZeKzXuSempE/5X0iwa1wy
            aav0J2qustk1gl/II1Vf+GNUoBGTFLSNAyGhTFoVWJsD7GrC2lh7w2uBGseJoYfi
            OV/wFDeBN6OaZM/neO13N86+2hv5Ym+B4uWjXmJwI3mU+pD/tzbTxo1BmlWPUcjS
            XgHt19+ksH23k9N/MvHvBO7RdIWMkUbESlyjZqU+Yj140WQJuZ/uIx9Csxqumw6o
            49mPUxRGOc6zLkpMFBk0K1+ErHzScMLqtrQLfxu7yZYNl4MAgITYO1ZleXreby8=
            =CIvT
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
