apiVersion: v1
kind: Secret
metadata:
    name: secrets-authentik
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:y/VMEGbcP+KKBzIbxXIzcQilauAXbwUa+IwGlUlFsfNVYub5,iv:RnAhGLeqrHmmdlhT2wNbWwcJzwi5LSdBwfRFF0JCaDw=,tag:47rsQ4mMYMEfO57f8FNURw==,type:str]
    email_password: ENC[AES256_GCM,data:TaWeXE6aZyVkIS4+bqoqa3IZyxPna/c9+mtyfxULo20y3hbxj7FB1wlvZPhdDLcpz8S1ebyInR15Gk5h,iv:J3RtEpS5ZuPp4soam9peMqKsPuLk/sn6BgCFLbPNL0I=,tag:EfN36gLcqvpk1LmTKFFTRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK045VXBoWjVEY3ZDU3g0
            MVpWSEJnZFppZVJhVU54R2F6SzJic3JLWXhVClBnckhmd1p2d05takVGSFcrb2hE
            SXZyTzdFM2pxRHhxWEFmMEU3N29qNWcKLS0tIEdUWjVIZjdWVDNqWmdDMUZKc3lV
            NUNMcmhIVHhXN2pnM0xzK3U2a3IxcGsKe5fzVBl76qIKj+vbDQniDC2yaViCQp92
            Ug3BfkMaLKEgYj31ZruqxNKsa2L8UBcRhx94tPMuKyNx6E4YWrczqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBbGVJYUpB
            SW5rWFp1eC9RcjRlUG5ycUl3WXlRR0ZUeGZEY1h0QlFSSm14OQpwc1dESEZQVkdE
            a2xuM2ZaM1RJL1pJZmUyYzFTWXAxUGtCbEJkNitlODBZCi0tLSBkQnJZc3RYdlRs
            SmxIeE1xRmVhU1JleWVERVVoVm5QRDROdEVBUDFoek9VCi1Eqo9Qc9KLk+6j8qX+
            nFW3HMrbGxNT0+uUh8CjPtJYmkJXvtRV/uUyiDWpsDzcbVKVw05CdaVyzjDeuZl5
            cs0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBcnhNUXpG
            ckxCcWx5Y1MzZ0ttTWJKcWRNeGwwcGc4RHF5NVJYRFprcTdpdgovUEF5Yk1QMVds
            TDdRTGlDdU9FN0xkK3M0TW5ZVWR2YTI0ajlVb2VhTHBNCi0tLSAvck9FNDBNbHUr
            c1NZblhVSzA3MCtia0ltSTU3Y2NUK2FFU1hvK2Z0aURZCo8c6Q8/7QhBw+AI7iST
            yjBpeI7vkJQ5VZQxuJGjPj12xHzILfm2TkwctKLv7MiqzFlvFJb9zDs5c/8t9Dlo
            ftw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-15T01:27:19Z"
    mac: ENC[AES256_GCM,data:6B67YeqyjiAVI/7fT+t+cOjZT4NOx8qE5yesKV3xgANgIdX2uOnVIUum1xbxjYmh9L9rUlV8ipUEvvDYOq2+2LcuBrPju7wJZNCFd2pE+DdsC3JFckuZpF+BoRljvgffVDfX8QU8xwcjWtatuscUk1t89hWa/9v6CfLvB4zaBAk=,iv:88CLeOpb+QiV9gcygSjSufOqw9L/JCBMpe9IJRWRd+s=,tag:SFcZ3aU2jb9Rba6e9ndsvw==,type:str]
    pgp:
        - created_at: "2026-06-15T01:27:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//XuFu/f7UD9Z9TJLE4dtnz+UWMdx36sYfsCS52K4BPV92
            /shaKBzhnxHDd1rFiO6R0ZOysTA0lOmE+ZxRwlbeoVaKyjj6t55omN0hpvUfm/fm
            dnpkGVioku4IPr32QR3R6oeM9vtJYyxtQGWOsZE809XQR0jvmT6bsu6a03xmmvYN
            OA48kcRPtONpYTAeuMD0UaUGmSzgTzyE0NduCUS6SQ0Ug4ITO44AS2fwQphz957s
            SDS4RW7xBM7yk4KG/flqOXNW1IMJyuG1oYoi0s6uwz0vmTRYOV0IGycRdpWJ5X65
            QPqhwMXc7CfFZwuA9oNW80Pv5JznR2wTdgoWOU05R8c/3lgajUaRu9k6qsCulJCg
            jVzkDxUyiTuh4Anrd9PhAB4T/ZnfyV6pzuIwqGvxldxzlLoD7hXWitKdNccEGmSH
            7EMqHF3JLrRbqhWHtEye/371hP3xkI7XhCpuwxAmG6N/TJ/cgJ703+qMPwFhPeQK
            EOtTjbPPxd7LcFYHnuy8wGGpl6u3rxxDcHgPrttAw+Uyz26i84pdojpQwO2xy8Q2
            HT9ujlCVQRmF6wBs4gm+HWZxPdoUHeswtMxb9IkwDklokCPNbWdHufOJNJddN66e
            OpGWTguijvrIcv9ds00bsCC9xodhdNSIWc6MH6zWwXU0QbMJnpmHkyeGv94J2erS
            XgEfsdnTfPmwM5Hm/1AE1ihv+eqjaIHHZgVdChAwU3pYCfTRxgM9lWGAEAgLZBhv
            YlcUGKACEkzt8aZbj9BEz+eSNyCcAharB/xFwzA/3kvwlml742ivXzZtNZRVdqE=
            =dcPE
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
