apiVersion: v1
kind: Secret
metadata:
    name: secrets-authentik
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:VVTV6zWOlP58d+nHHAr22nDeOv5zo0Bz+y5qHc7pC9Wu/gZ8,iv:yBLis3gkga7HJri/eCkilOHxu+T+/p39jHKHGfTatkU=,tag:l9R+oAGFcoNVRUHxbWq0Ng==,type:str]
    email_password: ENC[AES256_GCM,data:vGG97ZoY1QJtsUNpze7BUnozyhsqLFTIpQ==,iv:fQUvi1DK+6oshtk5w3KcgxMyxKyicR2+w5DE8/yfasM=,tag:qgadZHzScPha0upuu/2Pzw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQXhCYzJqQzhOdStjaTJr
            b1JMT2xiSm8rbTI4dWlGbHYwc1VPbGZiWFEwCjdPMXMwRTVTRnQxMlVXaytaV1Jo
            eFpNbWpNRDVBaS9SeW5ta0xSdGpFWjgKLS0tIFpGdG1nN3dKQURPQ0VkeUZ2QUNS
            MU9XR2FST3VKcUNZNVZOUWs5VmRlOU0KLQ/kupgcot95zZpAL1Y6eBJhO0vdPVJa
            Tr0jVx0QMr2Ny8R65kyW+l9FetJPeGvv4fqUyldi4NYnbTtdLtMgcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBbEE4ODFo
            dFZHMXVCQ1hNTkdkaUg4WlRhd2NiQ3lzNDcybjdXdWg3dG1JSApXc3NhQmFhMDFx
            RE9PUWlXaWhTOW5wbWxBVWpaTHg1aXBmMGFZVERpOEVnCi0tLSBPUHRrUVk5bU5I
            UW56QnhUbVBiSHZHZUVsRzA2THlzeGRtNlZ3K1R3SDMwCmE863jljF6jdHfF9+Na
            2IcUKAnts0dJRt9kC4ojTThbdOq+8kblq51UBt/s6c7RRMyvPv1+kdMg8yJtp3OA
            tcA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBaFlycUtv
            NGFsWGh2ako5bWtJWisrYlBpRVVyMnV5SG5VdWxzbGVSbk52TQpsQlorWmRuZUJV
            Q21FemV2ekpMa2JZUWUycmFhRmM3eUc4dGlDUGQzYWpJCi0tLSBMd1BJTjRpMkY3
            WXN4L3pSNFVDRU5QamZrdEpIQ3JUb2t3SXliQjRvUXJVCgSec8IPvMeAZSq1mon+
            G24zERCsy1pT8ODKXO1v8hiC/Un4mte0BhnxeMnbfTn9KZy+JXVnQygdefMxfeEr
            E0I=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:56Z"
    mac: ENC[AES256_GCM,data:/xdbaAhf207Ztwz1UCSlkbZP7iOQT7Ur4pfAbe3gL2ERcHoEuNv2lQIBpdcUIPGmo9m/x3KQ78wMfqApEgzH9nnVWYze+lLONJe3XNVHBVRkS8SnMeZ0TZKlmqdJ/StKuKm5m6fJFfvAfgLowPUdbmHVZ/fupuH8VlwuWfpWqEk=,iv:m1HXoDwXbHX5S4M9VudSLUtX8hcLnNbEYkMaQxgeUNs=,tag:KPSSI9muBPDLfQstiDlCew==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//fARf6lBxNpmjXI7TYMVV0hcZ31q5zXQVxLF16rSbyHdX
            V5vNfCYP8B8RvilFigBZns8HTl7o2oLDLmjmcIA0f/yl2m+ZxcFX0fkgdsH0jhxT
            +lbMX2dN2daEzCVT2BYcUK1nWj8oIVXJDNXjic/csMLYDNoEc+u2C3IvL9ojCJB0
            EqgK0VNvWyffuXhD2HqS34PCTzim7vN6l+eY2Akvx/P3Fuox+pLAOrinIMJ07oUJ
            GGfJtH3j0SxaV6WyCMSlysA9lGNQyU1bchjiSMA2p7YnepVDuk0MQOr+39bTQBi5
            K3/KyHdow5dsvpBcKOQvs74PZ2dj4sI/2Kiez3h8Nb+XWDkEVKyNJb74tk3+H+Nf
            Q3fPCm6ARtxWksLI61Wru8dbFi5accoDQKiX5YgFCi6WzbzZbWbCsnuQDNzgOGKr
            AFPUE66XA/hRWtlJyn15SxNbkkUePk2UmivVEdlGP5D9cenXJBU+WtdntV0X0EYq
            PKDt6OPaAmSKrd8VWhKR+iX+/cYb2/pGz0QGydz9ZYeEiBP/C2seY7YdUIw2CZyQ
            2MYuK/YtMKt2ZVcNv92ZxeWwaXQHliTKoKJP/4Q6mwrf8bC0YqQg9xiynvmZEiuz
            ePQAZhcuGuqPwbmUO453OUh8StisXdfDhA7R3gxLkswaeaIufB4GHsSW1ILlUuvS
            XgHqvWP0HfvT5LvFea0B56jR6K+KY32kdBepFDnku6kkRC/Ht0qdc9w+ukbF2sMs
            oH3e7FtxX+ghBHixxprYLlldE/2W+Fm+n2pmQs39rYOAr8h7hEcAlNRDi6FpVkc=
            =Z/Ck
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
