apiVersion: v1
kind: Secret
metadata:
    name: b2-creds
    namespace: local-backup-s3
stringData:
    MC_HOST_b2-pgbackrest: ENC[AES256_GCM,data:90QNyxbLDZnWCjZhou26KxMKtEDKlw6jnwKEe697Hcvvq3OksXUVuuzDwzH4832X/i3XMUPJBptYtD9xK2a24rUHLseqYamfJuGj1zr5CaV/kU789tbQydA0TIUKiLD7,iv:3q/u5MbfI0UjDp/9XoYPq2NC7atD0ouXD4FL4cu+Y9o=,tag:4MyyKv5yUJoo81OIs9SVWg==,type:str]
    MC_HOST_b2-velero: ENC[AES256_GCM,data:9EOsr/TBf7bBhUEIxy4A3VAWrZODC3jpOGcoJ80UVUJIYeCtokj2tZxXbuKpbUO+Prl+LGiwhZgIxDPF7BWnsA8wHmimJPwACk7O0JvVEEq0OxcFGD3yJtkT9fCkmZrQ,iv:teb1AWfFYwP4i/ibAPBfbXpqoeHR6X0wLS9uE+wrD8w=,tag:6vmcmrjvnDmFJ/QGLnZqfQ==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dVJWdXErWU5kNitXaXN3
            QWxUb20wdG1ib0ltMWw4ODdOZmVLZVA2TEhvCmhYNFpSQkZObUdWd29jQzBZeDE5
            RFVNenBTU0NDMXFJMEtycE0zZE1ZOGMKLS0tIHNBYU9uOFRzZFpveEpYWVZjYnRL
            RlNaOE04UTdlL0NoZk53SnBMZmg2NkEKccANkreqrWfwwLNbOV9YXfmUpBFSUkCH
            59kgzWi80oSVkCYvNRtKmEPCPesUJdFOdifpaanwARbjEXfOKCZ1oA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBa0ZaMHpu
            aHRiamRieVcrQnlHcGw3YTF4RUhRU2dCUzFNL2kvdGN2V1NLNwpFM2hyY25QcHVO
            SFgzV3hTeGQwaFhaNDdTK2VEWUtCWlEvTGJSQlRlTXlzCi0tLSAyZ2Npc3ZvVFk0
            akhaTFJVeHFLL2dVdVN6VCszUWdSYjRLUDY4UFZsNTZBCr0J6NEc0WoA92yVmC9E
            wYToaMp4Y9iKIWDZjmkPyenVOncuPBwrGXM7dKkB/SHJhH0sJawlGsW8YTz9YVA4
            /fs=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBNjAreEVu
            c2NmTDZyaE5vNnNCMnVwMmtYRENDT3RWSzFRaWZZMzVtOVVJegpEdGg0RGRoUTRZ
            Ym5WalNmYjhXSjlsdlpwcXpqd2F4SlpaYS9JWEJ4UEZZCi0tLSBiaDRIU1U4bnZ0
            OG9RVXhUZmx1MDN1Y1dlQmxKSU1KNURxT2ZhK0xYT0drCudi3XtheW+Ub69iUZSL
            wsrA3UItntgDzgaHyt9m8Vkd3IOfr8QHfUBWO6to1WGzjY8yCOug1c9ebGmZKbNT
            KiI=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:TsM2yMUQXDpf4ODEbXyTJvAhY1/9EeJSm+8RldTOGynYUJN2fze24o5KOMj5NDD1z4O3dLmALK1ZFgUH4404d13nRTECUUCiUk2FVcl/3XewMKdKbCumoGFlz1JMMAbf3MNWYhs35UYhoPMk6jtkZCxo2sPFJSsTgGWUFVimiEU=,iv:rs81NKtPcBj7PaZ4neJCrQGVoLR3HoDdzJmAPs6Epjo=,tag:x+HCQOJI5OSLD2n/ISDQbQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:28:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//eUFfng/ly/QK+n1d7mieZA8pv+1gGcpVcKEOHTH2xsZy
            WoS9S1zukRIh//QT9bQ6CyK5THQnBIntRialof+Y8R3sBCiAvrgbaFzh1klIifDH
            R1zBGr2NdYMNRlgQZn6AJ0q78FjJbSf05XTT0GmKfI842lnqQXPD3eysjAjgZYWA
            9+IC5MzdTS6+cDP6OybGMmQhgXj4tqpQQ+pO3NsVpg1pqSyA1Snl9+U+PBfUpTzK
            2VT1Ey1j2pIO67+Ymcn42xbr1itUTyYn1EzgNY2Ae1prNBwRxFZDIHRaJnwNzllj
            RGz2U3Y33Tq3mfSksXt3YBZQfZWb9BWpY8m05YwDuvd8iGCQXkQDOeaMBbA5Hy+o
            rjoX8ge9/oGZe0BV7r7jRztlTqhINPfkahWE0gxGpapIZ3nqyuSgWdLRlsqGluvL
            tBW6aKdu4mOPeR1mgXlF/46GTcx44CbI+9gvPnFT6JeN55B07+EZhUPGcnfI6bJR
            huELwsJGNno0zHhxybIQMgxNf6rMc3Y+grOmRy91jAYwKXe49oLOXszDE+N2MxCP
            7A1cfGS2unVp9UYjr7Hi2vZoIDDciFVVadDC8oIQBg5nTqboxiL/FBEnK3ZbX0Ha
            B5FYBw+hpwvMfbJhBkn61ez781QTzxdi3+zTAhrVZoOcXK+wbEZ/mErwQcnrYmLS
            XAGH040PZs8n32yDIl8Dm2yH/QujjOXNK5wijS9cs2yA2ZXEK4lRkP61vcByWG9k
            AjkagdHX7tBxZ62G+UuCs7yu1KR0lMLJU8VnlDvHRQg2TDouUE0ZwUxN3Nrf
            =tKS3
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
