apiVersion: v1
kind: Secret
metadata:
    name: b2-crossplane-creds
    namespace: local-backup-s3
stringData:
    accessKey: ENC[AES256_GCM,data:D3sArJ3A8FL9ipf1mtPA7BR0hdcvT++kRw==,iv:UICjsy/au7bbv/YJq1j1ysiVOPo2YNWCgTayjQ0jph4=,tag:dKzks/tpxj9V1TzKO9txZQ==,type:str]
    secretKey: ENC[AES256_GCM,data:02n2Sop6JawT3EiobGrH6Bi//0ulYw3d1IJfXjfiaA==,iv:LYsnjoy1pv2sk2wbzxxHmy6ZiRhhDsU5tNY8oYWdWJA=,tag:O/gvAx3PfCFF8dvNpApxbA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN2RIZklmWkZKZXU3cSs2
            cm1KSnFlNHpieUpiNUIxQXpFdFB3bnQ4Z1ZJCkdTaVVNd3NDdmJ1UGRiR0dabDRL
            czQybDd1bGV2aWhyVlArejJGMTNCcGcKLS0tIDV0WHg3cGwxQVR4WDJXUmo3RGhz
            YkJ2OVVSM254Si82ajVxU2ZNNUdOZFkKUleqbGNFJ9JotKfB/QZ7IgQTDDzOuSrb
            cdk0seS9kmmDkNzbWKSqt+Y81DWQYfDxevhwKnlGz0gWslYh/zhVWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBK3U3dUhs
            Nk1IQ1pQQzFiT2JYUlBWZGlJVjAxc0NvQjZRVW5xV1k3enQ4MgpOWHVjQ25FYWg4
            TUl1S3FOTmtnK1VmRkcwSWRkcTYwRDZFSnQzMVBpRElZCi0tLSBWOG5SVDRFVll1
            WTd5Ym5Hc3ZKOGFLQ296NHB6VVEzZDJwb1dyMzIvQWgwCgrJfCZzEK8Gueq6PEFV
            fkP9SmqtdG3MMay0W38poHFFI9ZsSO3ynBL+qP9DNdlHD2ILK2Q0764/0hUDom/Q
            N7o=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBdmR1cVpx
            bDR5cSs1R3dSSy9oKzZ6T3BwSGpmbDF3VFU4MHIvTzRQUDVJdApsbmt6OS9sTVZV
            eCtkcWt5N0E2ZVJXVDdQWVRBSVYxbEtaWkFGeWFGNkNRCi0tLSBWNDlvSFBDWUxq
            UWVJZFlWbzIzd2s4SXlZK3lHZ0d6VXpoY04vNDN6V05nCrJw3bAAmCH5bFexwtSW
            REItmin62UsfnuFqbxlVLvE93z/ErEyir8uMnWr0b8LgXljgO/NNHVtaBnyu/EIE
            vfk=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:q/1tWOZF+0kjjtdS9Dc8YDTemH5gZd7QcVCx8J09/FwZjtIQ/xU1NMR+Jata746c46CYvCDAFaeD24eXHB4ecCHStXYl+GhyuN3q80Yi90uWxgxhjirZuevdy88jM3O833BCVeQucDxuByxIT0itHJhhYILK9jMTGVNqx4vFZ90=,iv:X8chiU2KM3+SNhMDO3zdUR+YOlCCLBHML85vJm/xQVo=,tag:WGwcvlTc+ShcGck906oGWw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:28:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+KXaBicdmzlNsGJjrQz+UwOJx5dHDOLUtEJxZAlgyg3V2
            u+MJvKGMuyCe5HkRoPeDc44KlERJmKs7qzXFN1HHHNqh0hIAmHE0ns9HhF+xeA/9
            5KtPAzASIsjdvEE3s3lQ6idb+bNhA345uPxd152jNs9j/BArg0U9QxrdSeTdD3RJ
            Qi3VvfANAkQnD/ma3ERFx0A+zXqkFzXZhx3NN/Qhb+njLhxy/oz/zHa2X1BlHrNJ
            Ep9SGoq4jhcBzCnFru+zX9sKA+B2gWXMiysVC8HhROrE9YRPs5MUy2hjseqtS9A2
            nY7fPYV6LdgHXQ5lBJ/ndu9bx/R4bhiVu8I+kvtgAjCiZLjQxkvPN5Y1VXc+eyYn
            pJYZ3Q5RwLM0kDnDBl2mngrRHYHyA5pyzD/IM87ALp6LPsoxL2CylC3brovZIyym
            NgBIFib0iFMy3xttkaElWdhw5Rfo86XiBNNMCW+SJa4+GaJhmqmjhH0lwkTyWc6l
            6swJ7VfwQv5PIfo8lTPWAHqfHnQM/6TQtn8a9YHQv9RzEpbc/OkzXllOCe9GFeD8
            uBgBCagaGRXmiowTKFDfMuV/9Y0wfRq91Csj0L6XjJ9hsngbdNRrFcOz+MGA0YmU
            lwBoHEz0hsjytsdUPatQe20OZUjOiEssogZl4RpyXnee/gbkhqLqq07bA9yE0l/S
            XgHZQrAhVAQ/24oV+WoAS48nt3tIvfCzmIXOZjDFuz8TmIZFPsALK8YamsF+hT7/
            S4uf59lWHZeFB4Lc0U7oMmDPdxywsBenAyxwZ4RM4ChUbxYvHl13kHJ4TGY9QM0=
            =rth7
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
