apiVersion: v1
kind: Secret
metadata:
    name: minio-root-creds
    namespace: local-backup-s3
stringData:
    accessKey: ENC[AES256_GCM,data:VImJIg==,iv:oTQv+cGEHMmn3bC7wq8AmTD1oa6yrluZyunrsjBpS8k=,tag:oDD+g9qqC4WC+uB/9IyCNQ==,type:str]
    secretKey: ENC[AES256_GCM,data:rH68bgRtNt5hr2Ro5Bif4xW4Gdd9CD9tnNOM3r8zAzY=,iv:YCJF+v26CZ5m1YdIX30ueG8mdENJcwZipcM5IOK1Qfo=,tag:x8J3y6ZCyCZbEyhdkvYSNA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VWFNUFdTY1pEem9rZVkv
            WXZZcEpGdlpiaEJQZ05nT1RPa3pOcnpjREZNCkFqeFZBYm04aVNpaHo4dUhzTjNu
            R2ZsOTBUZWhIYVNEZE5xdlAwR1E3ckkKLS0tIHhaNmg5dUswSEhZaU9VYUprSTFp
            U050d3BBb3ljK3dKNmRNVTFNRnRWeWMKtpql/nQlWiB9y35MbXFZiu0rXEgk4HqV
            dnC4uPMl+GWXg6ph1hnWmhPGwApv3mV2Pcnaq3yX8AmI0UAI3kcQ+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBeUF4bkxB
            eDhvNWVBenVBeGZKeC9BMzlnU0tQS09OYTM3WFhZNGE5cS9WYgp4SjZ0Z1c4WWxp
            c0dnVyttYVFDSUFGckQ2VE9oMERaR1ZCSXpraHlBOEY0Ci0tLSBxWlNsQXFoR29K
            Wkx5VEtMTnovWG1hMFR1VjVoLzF4dXJYUzFZaTlVdlYwCpz+wQkKCbN1Y8jvwUhT
            mLK3CPFpLoZ5S3IvXYeKsp2jujxO25rvtRNBT2RIQYl1ZGBvZ/f9F/TQkFbxsspK
            8i8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBaFZZY2pq
            M3RQWjRMWlpXVjVBeUJ6YkNrM0ozZ080ZlhhUVl6T3M0NzZWVgpDa2J3MHBPaHhs
            TzVXK2FtWnF5L3l0STMyTGtlemtqZHIvNU92blEvcTRnCi0tLSBJZUZEay82MThL
            alU2WFN4NmRhenNLYXhzVGtiNU9RSk5HU0lRN1ZJdXZvCngloC+pRsizk54KaN7L
            6q6bKZnZiBSvyIhej9VSJW/Axnvo46mMSvC0HjXxPyVcwQYk91bbOQ7CDAtDTbQP
            9cw=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:cdL9rzJzuqa6bNBe1JBdl+yLRpOsIIbzY6NvSXwd7jD05XpY0vu+Qrrw1RXfEnWt5EcfP5N9XBOShjlv+tmDeSBR87Vm3EqwHbUNfV89D8auVcFSSf+OsHV/MKTUGXAaQ7chXxLVWg1QIuEMS0dglzYgbCscK3twAoSCfuglasM=,iv:O0yEnDwofycA9q7HhWGed5gG99tVGd23E+CcgFjZlBU=,tag:JeIoy95am+Rw9irRPMQbbw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:28:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//RFBrgGUhvbk5Q/u3Gn8dflWHS3Aw/UtZNkKS8VsvwppE
            mvCqc5MclTv2jmc+1CCPOI/zcOMqrvRt9YXjLJwPHvZeaVTzhy0ItKbr0otBk0r6
            t/munyeUTk4+jVHaupsq9KugcYI++Iflg+AxF30lYugsz1x+QCkm1s1VXmc8XLlU
            aOE2HK6R9hLehVyhrByjZJ1FTGWu+qiZQ8+T8Az1AJApuqaZVZkItrIcqKtqkfIz
            g7ktssfzOo4IFBijQeBh2vjK2EDXD0YyazIm7JG82+SQpoBSKxuVjahF9OBQ+04K
            n9Di2cnxycHyBTJvq2G/Ny7IEd++YxG72gDBCV7dfVC6tA6ZvKeZaOOfyWnqStLW
            Zgk9CjEMGLul7E4CHfBRAolxtMkOm01Sc9TOUI2wf6ytq7vUvrofv6zq4ibHkH1C
            yU3gibexn9bA4mPxAghnVxT3qa32fghyRFqQzBfQv1mZ8LKA0cN7K6OhoKchOsc/
            c6e0Q2aXFCjmoBOlHWtolmMyLeSkwmGZ0FPFFQYQ6MjCNvwWVDfTwsrOKah7pRMT
            VSV7bKJxk2aGVnMGwnHSTFv9Jt3VlmEu8Iuix6UzJu5fGDfw2WEZ5AhoXyqM22eD
            crNioR+tVpumRWBJcDXx2ndLywOqVgNd/IWv5+TxHCe6UuZhyleaHVsZ2AlYs1TS
            XgFPp0hnGpMY65M76ojhT7TnJXd1XNw2M0mMbJVjG6ANzxV9LS2tIwEzIiMZOlUB
            dZyxLiS+YifQNNnJdZyuW3OgJkZaIGMjlzBLMEHoS44ktWX1C0kDUnPzSlkOCaw=
            =gzPz
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
