apiVersion: v1
kind: Secret
metadata:
    name: radarr-apikey
    namespace: radarr
stringData:
    key: ENC[AES256_GCM,data:9k58/S4btpbYC/0//H3rd1hQw1kHaHxY8QAO6Z7yNhQ=,iv:1eshxfI2yayQAAKIvT6AQ0u7R4HLCGMt3M6X75d0O4w=,tag:PSwczGEgDsUo7pXs3vKx+w==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZFY0eURxVW5sMzYrUCtj
            N0JTNEJuK1hDQTJlcWFRQmNTQWNTVlg2NFdnCmd1Z1NUV2hTajZpSWhQL2d4V0N3
            dCs3QkVBQm5TMDBJK215Y2xYQTFnVzQKLS0tIG5SY0F5TXhZayt5SmRxOEtHQ3py
            VWw4bzZMakMxaC9ycE5WS1J6TE5mOTAK1fogwICGtLz4OyFDib6XhnRVjw1nibKd
            Ao58ip2DHk9VoPH09nyOugRATXOBCdIgsgeX8yjB1nME67YfhW1OxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBaHFZS0tV
            dFhpVjVhVmdHUHBON1ppdUNXdC9OT0ZCRkFBYUV2dlhxcVpnWgpkYU1EQVNjc0U1
            YmRIU1lWYXc0b1VMQWh2ZGpaeWVwak96UlRPbkJCUm80Ci0tLSBsOS9RYnlOdUpz
            R1E3c09NV3c4d3gyOGlCSXRFWVBSeUF2WXg4blJvWEh3Cib3KWdEyLSwIy2Cbv4N
            vN/nv55FN0NGK8Uyc+ffPdKRLnTU6ZZnxLSPjaPumaYRqbeqj4gsiqjFOEqZUJQY
            KkY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBb05ZOG8w
            R3pUTnhTR3Bqdm9HbDJnRjd1UXlnc21wWGE3MWlRZHZUdmo5SApOUlZUTFgrT2p4
            VjZGK0xuc2tONGk1OTBscSsvQXc5M0pnKzB0Mmd5TUlnCi0tLSByQVRpeXhJeTVS
            UkZnRGtxTW12K0dBekhrdmJRempTVDFvZnNvWXFOR3E0Ctk2xHBZ8mEixBSYvU4l
            cWXaD8korjJ8Fl68PNC1i9bg/mF3aTyYvWSF4Pv4LsUdmzKJenyN2JlOcM4RIXjs
            3DA=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:56Z"
    mac: ENC[AES256_GCM,data:+lJ07uN6c27ANXkNIcI5P/73x6HRmyI3CpLEEK3dBgTK63rfM9f2c6qZEPMlFokKtx6wNx+NeZidQgj+ZDvYpLcdPkk+O9bc8D5tEKQamCMYj+OOqdqDVxg2fgp4wl4Y2HPdAhHP0cJDOBLSLI4aMeF0SvnzF3GtUFbY/YsCZt0=,iv:5+dnsFatNaqNy/hXvzALbIOo5I8lpDuegekIzkpmzyU=,tag:JDYEVzVGXfMC+i0R9a+ksA==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/7B/xe9z/teAUoUdV+jdChLPX1fS9ZaH8C+FJOqOHs/ivX
            tA6NMeH4+6xmd0jwjiM4x9kNAZViWJkCTL/CNYpYG5vvPCO5VdJ8ZIB3UsMKq3Bt
            RvLBvtXlKjMm9bMLWRDatpu73Hy/AwqRFo0PZ5W8zzqCd/QYYLxvUph1ifoEoKyA
            wR+2RvWf+eth03emKpnroQTHnOAOYoKed8dI30QktTDU7oLaDxecJfxjru8dTm9g
            5R58GpvHQMGZ6lh3DLJUeoAmXXKZXnZvXTa2lqlLKqruzs2yLZkmUv0jDvskubp8
            vh1783PQjY3i5B2P3ljlT5Teq723OnemfFqQ8GPr/csvZs1QKAW+9mSRysFqvxQt
            nubfZQOyi933hXRbBakCJp1bLbwvt0XJrCl0Ky+Taz1U/gaSzZm10Gv8roGUpcs6
            YoxbgdDKtzuOgLDRlNCosTZl43V0J2jbAcBkbz5SMmoUfe8xmAwtE0M3IWSRIJGp
            0wKlP0F17N72orA8Kc+uUb+ZPFAG2k6EnJnIasYXWQQ1/9ka3O2EOIsvGm7Ftzus
            ozQpO8zh8hRTrS69hwlLVNR+nxkfx6ZQdes/jdK2M3a+9gMGJ1+guCIrWJrC0gaz
            a+K7Pq2CEx9rgOpRXL3key8TEQoxY8uOWzq+CY1CIbS2VJSmuZEp9nCpbpWq5gXS
            XgE2y4Vy6OCpkIE+tpU9wgBBayI2WEUX016fY4vwyUM4xy1AzK9i+e4NPxF1bc88
            z6wXds1V++QEBB6jMDb8WiSMLSTjyC2gjG17DdztyeujwTzJgzYrYyVNohFLX/U=
            =BO0y
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
