customization:
  bootloader: sd-boot
  extraKernelArgs:
    - cpufreq.default_governor=performance
    - intel_idle.max_cstate=0
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/iscsi-tools
      - siderolabs/nut-client
