apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.k8s.yaml
  - helmrelease.k8s.yaml
  - alertmanager-global-config.k8s.yaml
  - telegram-creds.sops.yaml
  - prometheus-ingress.k8s.yaml
  - grafana-datasource.k8s.yaml
