apiVersion: v1
kind: Secret
metadata:
    name: truenas-ca
    namespace: truenas
stringData:
    ca.crt: ENC[AES256_GCM,data:lucqEObVZ8e+0GY354bTXS8Iw/pR8bULXztH2LR5UVchk0+VRdLqcFVFwEiYRuMUWnn29NHYcN6VDkMoFTCrKHNA37Q2wL23A37rj6GBjW/q6zXACHQ9ceRBkS5HigOZYiI3Ft6SZwkjgmENbpxWNDCP4SbXBInfLnVjRKZDzj+lxSymzF1wjUZ4O39zHHbTja23QD3OTf7PZq+a5OnvYBaG8uixAPv1WyepZBmWCghqcm5oiQdPtWSoUf9w2hDhw6PevHAvzeBqLUALAlyrbh8CQpop+J7UMHtwHkF1DZiNFbkKPqFwborK2Zjftg8O64d1x+RHhw9fdjRrBNguu0vB1IgCf7+5W/dugw6W5crdeo2UMgHOz0/w62wku0HDkJ377LC0rTSIqP9NRpDqFrYhdFWYBQid6EXpI8TmmZa3UO+TCJDjKIAxUYI+qiY5g/GCHfkaaUTAkHPxY0rcm4Sbfi7jQkVd5ILUxHDmQrUzYNo4oEcMX9FIzhcoJJFrUdTP9kAI1GX8eTqUXNDIxqfzfc24APt/ccQ9mZJ/CBtq1tbjhlKq1S57RItE/eTFKGcI2JTLKq+NFfTTTlVQFvFVcEX44wiv82eYCwTv6x+UQ7Z3cpgh40cCNIz63TzmuKzF91jeleiLCi5yvZTnD+v30AcGrLHZV9coorVpROos44XxLgJYKXiBjfJCpUs9HYnbQMv/1cqIh1wg8nXK4sT1QB8XpQCuK603VleSkDHfO2kzUhVzBBKkVjYSqhURANZOwpqUFo6c7Hgw866tm11REQ7vxHvedAscBqUUo0f/SPgfBJtkuaPJol48ufbKcV85EFh6JPqeIhwTb0vswGpqIjakudymoRGvAGGu5vMOJY8pDhfazqoeJtyeVuRHlCiW7BMaDfFCYUJYlOFxOzAo1pVrMamkKcNycwg4w7yjptX8JfdknbTLq3Xe4VCafNACiZBae+7GY3jnrRtgkzusGai7VOlKNEiB1eVGAbHmBp8TfzwP18WXHvC4OvPswo91HChPLmexxEQQlrotoin7cCFoJlvc+0fMdc6wEfa0nWubtuTDIJAw3d2thM3PEzh1QP7uKxrVmDgORTx2v41kdzP4MXTifaTZEQyw5lKf2Fm1nZ8tgPif4RAGzH5AlUUwjhOm/SApGJNbSttA3t/5ddsIpXO/43wPEj4yuV2z2ey2Kc5X/FB+RhqKtUNRpLlaB06ryyFtSK527KPzgsV/I2aV+jNCcbasWtOecNa9RMAUp6NwkuWsaIh+jZG0xsZTbL0CmWD1ukJUn3XNF5dquaYSJQUfvQSmZarA0dGjv/vo0Sks3kzNIgnSfr/hS8xlJO1req3O4hlHlaL9PIf8d9j0/dddn3Kb6SqWvhVBwOmted5FFWm9PlD6F9ZfyalpTf0cUCKhn4IEQhPT51TF+y3P0sBzNjpW9YRzqUOBCSIpqDwN0uzkGHJ1fd1jb2w6EFH1NhkJ02iQAeUmpr7I8DpKWshBp6orJokg8gQ6B1IDIxm80ujQuS2JzjMJvEklWDDIhvuJ0zSg8erEcC449WD3/SIIJvbdz6En2a5wiKifNRb1lIFMeHltIHr6Dnw9Fl9Kcpq5liA0wFldBIEhaRcJh0/ZPt+QobU5B8+LSmcJX7Q2Kl09/Lq9DffKl6b5FrP0yU1B489B6LYx+vCobaZT2//C9cE9BucgBNQ1vNmih5BL69hlQzkTN61KDd7CCTEio2vqQQOQSETh3w1QUndc8FQKXGhjFJS8M5T7giWG9+mnN7qcYxk9KxFWpTTguP6XFinsIlfWByxKMGrOG5mFpWtRcHHCtQEYzHw/4R7X8DW0jqKl/w==,iv:JfA4yeirilJ8JEkcZFldyGv4xw/9W12ZxRuMTzl1wIk=,tag:/HOMEKakpc0lE1b+gi1KJg==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnF6SGU5YUt3OXI3NE9N
            ZlJ5OGlCWERQWTVvWmRmUHdad0RFaVJmWDJJCkpLZEN2V1RGUFlqSERyQzgzdGNk
            V2VFNEVMNFhVaUhMd3FWU1IyZDhPTTAKLS0tIDlqa20vQ0J5bzN6d3Jqb25icGov
            ZmFlMkpqTStndFRiTHpRZHJzU09YWE0KRQswLfxeoEbkG4sGqYnKoPypxtQWtcB4
            042eGg3Am5YybslCsU+ZQhe9v4L4CflHMv3/z6VxC4GYoZ56FbuNHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBaGZhOGZh
            Z0VnY2E5TlJKaERnVmhnbmRLQ0d5bUNiaGdPdVh5eHZ3SFBFTwptcDluVEcvZEht
            S3BabjNIak5KUHNGUEZwaUFwYmtzbkRzVHBSVkQ2UXI0Ci0tLSBrK0M4RitLSVI4
            UUl6OTFGUmdSNGtNNkpnRk50NUZ4ZzErVXVJUzFLRzVFCoHeeYENgGio8X0llvkv
            8SrcrqTdTpBi37QKSqskM8qPivoaJTS4rd5RgnItbIZRRKXroJmmCsrtw/rqcXs7
            cUQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBNEl6TFRa
            cjFva2ZLUGNUSkZIWUxlZVk0SEU5UW5KODR3YUJPVVdJcEMySApjQk5hWlVjNGlj
            L2d1ZFl5RCtRUHYwS2hlMzlpNWl0QTJ1eWNkc0ZwUFFVCi0tLSBBa1U1TnhFRFJ2
            T1Q0cnVSSHQ0blNlUHBuVzVVa1N3ODF3VVQvVmJNOTQ0CsCdEj5d6l4sjDZ3pILD
            C95P7VoHh3DvHtvMxzHlxI6Iouz8bCqr5wqt/c3KvPlfDOlZo+GCd1UbhQxhRlCS
            F3U=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:55Z"
    mac: ENC[AES256_GCM,data:uGcTbfq/Tk2a4UI3NlwzV65sEdTsVKrOyMTJyXbC1sz0MRcSVlIEnuke6nQLs4NGgYQjqgTty9RaCCMCba1LD0LpxH93YOnIJ6Xv2KVSrcnhMuzEz273IeHFgkdUprkkkngLsFcaLlDwIMxSUprc7hC5+slFxeXvg3QyemBgnhw=,iv:1NzRFMh18tvCklBYSIkNjIYNx86CjDolRn2u0OmEYKA=,tag:IzY4Lsi2ETJnVJp5PPnCzA==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//SWkLpuF547TkpKgEUEoQNOzK/i0DoPAKlH5QNc/oBu7d
            EwfmgGK9mbpkCLLQS27rikPZKL0PiPNRXGqIvActS0hl8lT9Rny03OXL8C8qbXEJ
            d1UijBryIVYmhWN8L7RMpAnN87LeRIakQwcvsXOhD2/XoOYNtifFjxU0KAVKNAHL
            71TDMyAZB9/KPdpRyOrQpyA1Pq4slFa5u4EwpqVl2MUtlK+e8RBQ451WNvUbKRJq
            5yceqKOk0vXMaix2EBdP85qZ8jefJ9oCh6nyV8HB6/VWMxtH8ImtsLZUJGXZ2MY3
            Jq1i41N78GikpdaDkZ3vM8KZbY5vMtIXEvvy/Op/NTh31w9dn+4pmoY86MnP+Fk5
            IecDUDy0KLkPcDl1G4l+WpJ/wjJx2ujyogmmAJmVVwGhxT8hppgd51b8ZL8faYvl
            LX90GJGAE1BE+1H6ddv9A0V4v4h8KvNqJWnc2pqrssN40qty3MZA/NscMNPwBMLs
            c/Ajz8D6cXtwgUvVOn0jj1HnNrd2Z098e9fBO1g8ofejwj3hy4uyyAdaDytsiXgH
            I01CoImACCvIMYiNYesfx7CUiGVkh4R2s0H4I4Wvf901cGmZDuntqDPn09zag7RC
            TuGBFZBFVNrVJyCKW2FyPuaJA7bvoIMk1SBNsN6PFoB7DrPwSwfQKFFJaRI9GDLS
            XAEIeSIjie1ikCeK1U8MC7Jc9PRShAHvbxAPU3vZKlq1V5Q8e7pH57PJ5/94BzCA
            EWRxUkSUSWm+IT9zdnLDd2uRBsIAG1p++8VTQq8LuoDLM5kSHQV0EZWN8aQt
            =SXD/
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
