{
 "title": "PostgreSQL Details",
 "tags": [
  "postgres",
  "db"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{job=\"crunchy-operator/postgres-clusters\"},namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"crunchy-operator/postgres-clusters\", namespace=\"$namespace\"},postgres_operator_crunchydata_com_cluster)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(ccp_database_size_bytes{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"},dbname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections - Total % Max",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccp_connection_stats_total{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"} / ccp_connection_stats_max_connections{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active % of Open Conn",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (ccp_connection_stats_idle{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"} / ccp_connection_stats_total{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Idle In Txn Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccp_connection_stats_max_idle_in_txn_time{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "% Toward Wraparound",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccp_transaction_wraparound_percent_towards_wraparound{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ccp_stat_database_blks_hit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"})  / sum( ccp_stat_database_blks_hit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"} + ccp_stat_database_blks_read{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}) * 100"
    }
   ]
  },
  {
   "title": "Streaming Byte Lag",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ccp_replication_lag_size_bytes{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_connection_stats_max_connections{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "ccp_connection_stats_active{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ccp_connection_stats_idle_in_txn{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "IdleTxn"
    },
    {
     "expr": "ccp_connection_stats_idle{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (cluster, job, replica) (ccp_replication_lag_size_bytes{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"})",
     "legendFormat": "Bytes {{replica}}"
    },
    {
     "expr": "ccp_replication_lag_replay_time{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "Time $cluster"
    }
   ]
  },
  {
   "title": "Database Size - $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(ccp_database_size_bytes{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"})",
     "legendFormat": "total size"
    },
    {
     "expr": "ccp_database_size_bytes{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Transactions Per Second (TPS) - $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m])) + sum(irate(ccp_stat_database_xact_rollback{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "irate(ccp_stat_database_xact_commit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]) + irate(ccp_stat_database_xact_rollback{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m])",
     "legendFormat": "{{ dbname }}"
    }
   ]
  },
  {
   "title": "% Toward Wraparound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ccp_transaction_wraparound_percent_towards_wraparound{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "% Towards Emergency Vacuum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ccp_transaction_wraparound_percent_towards_emergency_autovac{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CRUD - $database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_tup_fetched{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_inserted{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_updated{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_deleted{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_returned{namespace=\"$namespace\", pod=\"$pod\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks - $database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"accessexclusivelock\", dbname=~\"$database\"})",
     "legendFormat": "accessexclusive"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"accesssharelock\", dbname=~\"$database\"})",
     "legendFormat": "accessshare"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"exclusivelock\", dbname=~\"$database\"})",
     "legendFormat": "exclusive"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"rowexclusivelock\", dbname=~\"$database\"})",
     "legendFormat": "rowexclusive"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"rowsharelock\", dbname=~\"$database\"})",
     "legendFormat": "rowshare"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"sharelock\", dbname=~\"$database\"})",
     "legendFormat": "share"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"sharerowexclusivelock\", dbname=~\"$database\"})",
     "legendFormat": "sharerowexclusive"
    },
    {
     "expr": "sum(ccp_locks_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", mode=\"shareupdateexclusivelock\", dbname=~\"$database\"})",
     "legendFormat": "shareupdateexclusive"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio - $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ccp_stat_database_blks_hit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}  / ( ccp_stat_database_blks_hit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"} + ccp_stat_database_blks_read{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}) * 100",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Commit vs Rollback - $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(irate(ccp_stat_database_xact_rollback{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "WAL Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ccp_wal_activity_total_size_bytes{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}",
     "legendFormat": "Total Size"
    },
    {
     "expr": "idelta(ccp_archive_command_status_archived_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "Archive Rate"
    },
    {
     "expr": "idelta(ccp_archive_command_status_failed_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "Fail Rate"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_alloc{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "Allocated"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_backend{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "Backend"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_backend_fsync{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "FSync"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_checkpoint{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "CheckPoint"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_clean{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m])",
     "legendFormat": "Clean"
    }
   ]
  },
  {
   "title": "Conflicts/DeadLocks - $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ccp_stat_database_deadlocks{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "sum(rate(ccp_stat_database_conflicts{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "DeadLocks"
    }
   ]
  },
  {
   "title": "Vacuum/Analyze Activity Rate - $database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ccp_stat_user_tables_autovacuum_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "AutoVacuum"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_autoanalyze_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\", dbname=~\"$database\"}[5m]))",
     "legendFormat": "AutoAnalyze"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_vacuum_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Vacuum"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_analyze_count{namespace=\"$namespace\", postgres_operator_crunchydata_com_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Analyze"
    }
   ]
  }
 ]
}