{
  inputs,
  lib,
  self,
  ...
}: {
  flake.nixosModules.sops = {
    modulesPath,
    pkgs,
    config,
    ...
  }: {
    imports = [
      inputs.sops-nix.nixosModules.sops
    ];

    sops = {
      # Should be auto-generated by CI
      defaultSopsFile = ../secrets.sops.yaml;
      age.sshKeyPaths = ["/etc/ssh/ssh_host_ed25519_key"];
    };

    sops.secrets."ssh/root/authorizedKeys" = {
      mode = "0400";
      owner = config.users.users.root.name;
      group = config.users.users.root.group;
      path = "${config.users.users.root.home}/.ssh/authorized_keys";
    };
  };
}
