apiVersion: v1
kind: Secret
metadata:
    name: flask-secret
    namespace: gramps-web
stringData:
    GRAMPSWEB_SECRET_KEY: ENC[AES256_GCM,data:qalfGmxo6SE1KT51PlIinePENFjL1q3bThZ5b1b+suq3JMpeXoYRvxvdMMhSnUv3+SY1M4CspFD35OdfYxpgxA==,iv:1BhYG8IvFyLVzoYpVSkd6K8brKfqG3YID9zWDY2jmd8=,tag:MdG3H1FiumrLK63406whCw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SWlEWnRSa25uaEVsVVRi
            eFZtYjN1YUp4a29BS0o5Ynppd1N1aVVlam0wCk5ESHQwOTdrK3h3UWZ6cVEzbGYz
            bmh5R3lUSmFySHZGUzQyQWkrVDhNTTQKLS0tIDJDK0tidnF3amhwc2RSL2pxNGpC
            VFdtYi9LWmoxLzJOZ2hsSTN3b1d6eWcKl5uD9PDfA7Hs6/RqtHpsFmiWxCS7DHMO
            /5doKUOW0N9h4NvvEGChKqOxXO/6mdB5pUb9Vo1LGbZmwO4lboD9NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBOWpTSkVW
            RFY2SHE1aW5DZ2RyTHBHdGloVTJKWDRZclluN1VZTWNmc1lldwptNytDamc0Uk9F
            TmdJUnpUV1Flb0pZSy9DYkpwc3ZYOFVJQnBWNmJvNnNzCi0tLSBCTkV4UVM4SElT
            Z1JIckcxNWhvbXNvM1VJcU12MWdmeVpzVEc2dUgvakFRCuwNRZzWM8sDVv1xF0S/
            QSZBFvCEVEzw5Dk9717w3ddK0rDm5JI51GJEwA+rHUU9tjKWwQ47aQIWjwzv5Ux9
            zsk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBemo2QjN0
            dmlGOEJqMXkzbVZlbEZmRnFGTnNwUGd6L1Z2dnhVYUw2WlAzVgpWZWYrUlJ2V3R3
            bzB1ejlmTk1qUkc0bUp0TXkrUHpNOTRCQjJYWjlHNGhVCi0tLSBTUktaYUd2Z2tw
            RU9CZE1yRlhJSDFDYzB5U3NucWZ3c2VhVHpJWDEzOEVZCk8Z45BpdmvNwboN80yj
            i0pkfwYX3C5zVnJAwXtvmCkTW7IiDVILtU6aQsKB3ub52SR0LjyaUm2DNMzs2KzL
            WRE=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T23:17:07Z"
    mac: ENC[AES256_GCM,data:G/DN04XgOItd7pQGSTjxC89RbzihW/xY9S/RjPuF4TJSeW/xkdfZ9lgkGGo2tIrxPaBLDApN5j3ADLmKksOhDhl6+pzdr+1BiKM823sPvS+ksr2ZXairvSMqJYMv/GFVBDm/bvvf+xcUxZFS9HN046SRPc9OV2aLyuwJeK6mXWg=,iv:mMSppQp8Exbq9jhuBvOH7OjLwdaLG2ay0YzYig+iBxU=,tag:a9OnaofKN40UP+8hgQdZIg==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAl7jEXTkzDUOnlUs5yK0ujHNW6YPX+RlzMIc2zDEPegoE
            ZLLSpHXap2pFU3BYds5ikO7Ib+EGoxoKSR/1QKkeEGFID+Uv0Wta3zZSuw6Veg9U
            +8VecFqyWDHFxA79JDk4WlYqPk/o9z6ViuEpgDl58TsGApxBURHaYA2xvnvV/YYy
            9wXtiym5s9sPI3P0QI9hofRqOsaXjJKSBTSoZdKeWe/YiPleTS9w2Ww0c2OxExm6
            hMlNsFcMhEvvQkJ8mD8vjTPnx57jDVDQHDLXXvpw1SWCxVNFaGKyufeH/UMEH90o
            43auiJAHD3qbrqhH6UP6aSE2ZevPskOyEIKFSzzzmuEEZWnCM9tqvTqZ5eaQpJX9
            avM04VxndosiLdyvQ9kFCLQ9b4xZnd5I4m6JTaORjW4yqvt9RpSLZBv5YJFlgCW1
            /epXFAX4KxnaqV9Sn4N5C5KhYuq3qqZ/sd17UUa85i4+z1qeTzZk96IRwASFO9+b
            Cjkhhsqs2y5TbaX/xBxFWCRLccGX/dmJfchQK6uTP9A24qINJxWZh2XfNI5wbnuR
            8XGUITQQEtiTRkyt7zcfaL8my2qQfEEUBFEZfKaN8DXKbNXqUTTfahXxs7pc7KIx
            mQJ1snWw9q30cR2tbZIBZuU1URr3RMAVqJhoyw6NPtE9GvG78Bk9CM9px3RcAwrS
            XAGC0l7Qiv5K55Q8jQlRZmPaqacdmid4fRE6lQLN1CbnYEZ2Lheci9f4BC2+0St8
            xfEjJuHD82AO1FUwtAKS7G8x2ebt5PtyuYPTfZyQ6QwSamMJIBbcAc5YOb/1
            =PTm4
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
