apiVersion: v1
kind: Secret
metadata:
    name: gramps-web-pg-gramps
    namespace: gramps-web
stringData:
    username: ENC[AES256_GCM,data:CE0uBD/M,iv:VxlrhWybPRiql4X8VJih6pNXGRFvbblGe9aK3SMnQE0=,tag:+Op9VQh1vt/jrBwcyVIF8w==,type:str]
    password: ENC[AES256_GCM,data:V5BssTrC67XDFdnt8Sk7s5eBmJ10ybiSUA+hiIkt4YSzuuGo4KCvLuuc1tonqNq2RQgrgH9iNimKDRCz00LZsw==,iv:PvGuR7ceQ4A1nzqvKxZhR2QJ773ZQHYsCBOlYtjKdf4=,tag:NJhmwYXhrfY0Vm/XBtA75g==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMFJKRURta0NCRDRmL1Y5
            aGFUczN4VTdkQVEweG9LNTlCZllMVldFem4wCmJYYk9wcVNpR3V2RzJrUEFEdVZx
            NjVVcTlqN3MvQ1o3RER5RldoSDdSS1UKLS0tIDFubDhya28xd3lYekNMaWpnRVN1
            M2lRWVQvZlgzdHdLc1BENmlaZ2RXUFUKtSG3GqpU+5m0WlRRh1wxVZUNMWV0zTpE
            y2iN0fP5h/3FVFEl135R9AzsFwDxrpNOo0ypNnMRzJn4sXcHwQMdxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBd1RhRkNG
            Nm9HNmxIQTBuK0lFSGdGbUk2RzRWSXBoNDRvZFBEaVg4SjU0WQoxNFBjdXdmeFF1
            cExYSVNxbGdiRFhFV1FZTE5wS1Y3RUoxNE9ub3ZDSllVCi0tLSBId0RBZFdjdGxy
            SWV3Nk81UnYxMDJrbkR1ZlVKRVAwdEVreTVtRWhVWFI0CvTm2fA3V6Rr1Kk8/Yv9
            Vkj+n6a913v28PvN15opbY5TN/JNtBxVS9r68gjawFlBWqlPockvN1Ux/FOQn8Jf
            EX4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBd1ZGQTJG
            dHIyWTM4YmNJVVlBenQrL1dUZml1TFpKNE54YkEwa0ZxSlpXbQpCRitYVHB2eU8r
            cFcreitlalZ1TWpkdVI3RjlsbEErK1RZekVHdFRvTjNjCi0tLSBuOFhhRnEvYzcz
            SzZEUmgwK3NNMlFOSVYwbnN2Y0FyQmZPK0F5SDRSd3FzCjk42Diy5beKC1oQqDr8
            BjtZbPqsEPrMXlH48k28WeS7BnhdmZcm5TEA45vXOAXlvBi4XTBs/0eOhRuh70jD
            1go=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T22:45:15Z"
    mac: ENC[AES256_GCM,data:vzToWcVSxxkQbje5HEodaf5ZAousDfCbXPxHGj/IO3KNYOUpKKX+M30A8zuRFnF6piGyTJYXmdMi/wEJw7KlNqbNHtSY+iHZnQAOtZ+omk969Kjh2+Gu/1XKvS7wtgNAig4GaIDvwceHk2Nk9PMgUO2LVdMTwgV2QlwABqA7bEA=,iv:ykuTZBx2K97u5HeObTY36nrzgOFaGqFV4MvZT4A8PfY=,tag:HIQGOjpVf2xDkC/lL4dAZA==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//dTJdUHJCtuG5kxRjw4M3JSI7qzeeneZxqOoUhJ4/Eac9
            EjScPl/kmcNmfbfGaER/TecMN3TIniSHMFUuSAL8jNxBorKolWcsUJv0smlozdc8
            MAl3D5sLnS8p0M4rliiR6GUNXQY9daDSxTK01nG3BCBJhl7NSvIFE5UsUxZb507Y
            LxyLwrA2vdMCJhtHVOi5m+UNhCJqYKXPyI5W9bs06kxeeTEO/7Q24tK0nq3mvNBM
            NG1GDcQ5c8Z85+EtJ637gSV6MgpJePfhdNmGVbinS/6wSVqOTP7+cv56FviKz6F5
            CFEWak9ORfGrAE3CU0SuxD7JjnLSpxcD1M1ikYlYMdPRUg7lHlqrvQK3j6a/Ob0b
            xIkAxrg4ctkVIFtbBg4i5TED8gR/5PYBzT1GbJdaujC4glBbut3tgeuLsb3uV6uM
            XNTAITatA+McXYNHi0Vf3ARIUt4eKUXlqKF+fdyR8z+cBKKdXYALWjJvIGwAxhD9
            F4+Pc/OZ36PjwHisBiU+7eOzbsi2tZyyK1ytvZJgIAoFlMs59fB+QH4FZfDrAH4T
            ZVnls4t+X0r2cgnB4GC8M51gwLH0sKqab2QVXXiRw5Z+9yZ16lEiYRZAS6rsSEYh
            afAhIB866Hu8q8tE/+RmNlb9UiIsoixNQjCusWTs/WBgGRmHCCrwr7KHremAah/S
            XgHMqBenv40ZIC8R0qS5oYqbaJt6w/oz8zJlIV4oIOcuK9XxXnKNsA/iRAmFc1Ze
            4iDWdAY27BqeOYEpvfeEvErzAffQ6/JeiZbyUF6yZA0ywaLozA1lv6JGZKPtGVA=
            =g1m/
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gramps-web-pg-grampswebuser
    namespace: gramps-web
stringData:
    username: ENC[AES256_GCM,data:I55ewUB7dGM5ilYxzg==,iv:cmsgXwPMV3M3M4QKVIqtV6YgJRTBo2Znf1Ng1yVXajA=,tag:glm9+t/BEB5///Ofl07zrQ==,type:str]
    password: ENC[AES256_GCM,data:QA1PgL7mJk5Nrz0L4wQCmZBT5ExyU3j1sSPtVK19RyGSbhjF1wmPsqWV4Dvube69NiBl092uN0nsSUQNAxbOHw==,iv:cnwthjJpOWdprUJpd+qT1IelNrWKm70IbVDUCrwWT6c=,tag:y/tHCKQEoDZEnjlo/gp0ew==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMFJKRURta0NCRDRmL1Y5
            aGFUczN4VTdkQVEweG9LNTlCZllMVldFem4wCmJYYk9wcVNpR3V2RzJrUEFEdVZx
            NjVVcTlqN3MvQ1o3RER5RldoSDdSS1UKLS0tIDFubDhya28xd3lYekNMaWpnRVN1
            M2lRWVQvZlgzdHdLc1BENmlaZ2RXUFUKtSG3GqpU+5m0WlRRh1wxVZUNMWV0zTpE
            y2iN0fP5h/3FVFEl135R9AzsFwDxrpNOo0ypNnMRzJn4sXcHwQMdxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBd1RhRkNG
            Nm9HNmxIQTBuK0lFSGdGbUk2RzRWSXBoNDRvZFBEaVg4SjU0WQoxNFBjdXdmeFF1
            cExYSVNxbGdiRFhFV1FZTE5wS1Y3RUoxNE9ub3ZDSllVCi0tLSBId0RBZFdjdGxy
            SWV3Nk81UnYxMDJrbkR1ZlVKRVAwdEVreTVtRWhVWFI0CvTm2fA3V6Rr1Kk8/Yv9
            Vkj+n6a913v28PvN15opbY5TN/JNtBxVS9r68gjawFlBWqlPockvN1Ux/FOQn8Jf
            EX4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBd1ZGQTJG
            dHIyWTM4YmNJVVlBenQrL1dUZml1TFpKNE54YkEwa0ZxSlpXbQpCRitYVHB2eU8r
            cFcreitlalZ1TWpkdVI3RjlsbEErK1RZekVHdFRvTjNjCi0tLSBuOFhhRnEvYzcz
            SzZEUmgwK3NNMlFOSVYwbnN2Y0FyQmZPK0F5SDRSd3FzCjk42Diy5beKC1oQqDr8
            BjtZbPqsEPrMXlH48k28WeS7BnhdmZcm5TEA45vXOAXlvBi4XTBs/0eOhRuh70jD
            1go=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T22:45:15Z"
    mac: ENC[AES256_GCM,data:vzToWcVSxxkQbje5HEodaf5ZAousDfCbXPxHGj/IO3KNYOUpKKX+M30A8zuRFnF6piGyTJYXmdMi/wEJw7KlNqbNHtSY+iHZnQAOtZ+omk969Kjh2+Gu/1XKvS7wtgNAig4GaIDvwceHk2Nk9PMgUO2LVdMTwgV2QlwABqA7bEA=,iv:ykuTZBx2K97u5HeObTY36nrzgOFaGqFV4MvZT4A8PfY=,tag:HIQGOjpVf2xDkC/lL4dAZA==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//dTJdUHJCtuG5kxRjw4M3JSI7qzeeneZxqOoUhJ4/Eac9
            EjScPl/kmcNmfbfGaER/TecMN3TIniSHMFUuSAL8jNxBorKolWcsUJv0smlozdc8
            MAl3D5sLnS8p0M4rliiR6GUNXQY9daDSxTK01nG3BCBJhl7NSvIFE5UsUxZb507Y
            LxyLwrA2vdMCJhtHVOi5m+UNhCJqYKXPyI5W9bs06kxeeTEO/7Q24tK0nq3mvNBM
            NG1GDcQ5c8Z85+EtJ637gSV6MgpJePfhdNmGVbinS/6wSVqOTP7+cv56FviKz6F5
            CFEWak9ORfGrAE3CU0SuxD7JjnLSpxcD1M1ikYlYMdPRUg7lHlqrvQK3j6a/Ob0b
            xIkAxrg4ctkVIFtbBg4i5TED8gR/5PYBzT1GbJdaujC4glBbut3tgeuLsb3uV6uM
            XNTAITatA+McXYNHi0Vf3ARIUt4eKUXlqKF+fdyR8z+cBKKdXYALWjJvIGwAxhD9
            F4+Pc/OZ36PjwHisBiU+7eOzbsi2tZyyK1ytvZJgIAoFlMs59fB+QH4FZfDrAH4T
            ZVnls4t+X0r2cgnB4GC8M51gwLH0sKqab2QVXXiRw5Z+9yZ16lEiYRZAS6rsSEYh
            afAhIB866Hu8q8tE/+RmNlb9UiIsoixNQjCusWTs/WBgGRmHCCrwr7KHremAah/S
            XgHMqBenv40ZIC8R0qS5oYqbaJt6w/oz8zJlIV4oIOcuK9XxXnKNsA/iRAmFc1Ze
            4iDWdAY27BqeOYEpvfeEvErzAffQ6/JeiZbyUF6yZA0ywaLozA1lv6JGZKPtGVA=
            =g1m/
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
