# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/cronworkflow_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: renovate-bot
  namespace: argo-workflows
spec:
  schedules:
    - "0 * * * *" # every hour
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: run-renovate
    serviceAccountName: argo-workflows
    volumes:
      - name: renovate-config
        configMap:
          name: renovate-config
      - name: renovate-cache
        persistentVolumeClaim:
          claimName: renovate-cache
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    templates:
      - name: run-renovate
        container:
          image: docker.io/renovate/renovate:43.190
          envFrom:
            - secretRef:
                name: renovate-secrets
          env:
            - name: RENOVATE_CONFIG_FILE
              value: /mnt/renovate-config/config.json
            - name: RENOVATE_BASE_DIR
              value: /mnt/renovate-cache
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
            - name: GIT_CONFIG_NOSYSTEM
              value: "1"
          volumeMounts:
            - name: renovate-config
              mountPath: /mnt/renovate-config
              readOnly: true
            - name: renovate-cache
              mountPath: /mnt/renovate-cache
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
