apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - cron-workflow.k8s.yaml
  - pvc.k8s.yaml
configMapGenerator:
  - name: renovate-config
    namespace: argo-workflows
    files:
      - config.json
    options:
      disableNameSuffixHash: true
