apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  namespace: argo-workflows
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-api-iscsi-csi
