apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: argo-workflows
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DVGg1Aa8zLRkubhOQkCV6jWO90ErSf5k+xl02IOqILfKD46VzuqxqA==,iv:Q4Kpk+cdlMfGYa6OCcNMlKKIDGkwAmTrF0tzw1v20l4=,tag:ycP3MnTFvZ/qSJljBuJaOA==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:w88nzI2FeZ1J9/MPWsLBg2Sau55YibPD4xSdvqsqH5GqM+i5+q2fUkAj3knMyWmazkHcHw9TPplFOp5Hz4p85E1SZB6Vrs6Z6CNPACiuFtjoO03gB5gz5qiNn25H,iv:zYc6UV2PJqtczY+M0/zs8s7TJ9uzxPHaCAJJFtQBI+Q=,tag:Yh0S/KtJyju5dc2wWmT9qQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UC9ZaU5jN2FvYnNWSUdj
            QmF1cDVHQndlQmpjdDkrYzl3UFc5aVRPcHcwCkpOV3JvcVJDYUEvbWFRd3FEV3Jk
            aC9WbmQrNTZkT2VjaGxjSmhScHBBZ3cKLS0tIDRzTVVJdjJWMVJHYWZ1MWJ0OXdI
            SS8wWlg2SjIzVzhFSlREVWY5WmdrNVUKZS9wuOQhVQ1Nua0u58JYMppL/fROT21N
            8Jnoohzw43leIv9egiQDSU0wpAxPZf4vecfbTIUX289+co6v0hE8oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBZ3ZUNW9k
            Q2RBZC9GRXRBMWVTdDdQbFFwZnQwdTdEU253bHlaeVJXZ1FrdwovL2RRenpYUUlM
            VEd1NmFYdlJkc3RGWjl3S2VjQUNtTXNCYktNcFZSWkY4Ci0tLSAvbUIycVJZUkNX
            WmhsVHRCdTNoNUp6aXVwQkNWQ1p4R1ZkYXlxNWhtQWlJConf3sqaNURhLGpzKc6p
            IUrmOSUSmEKbsL5Lq1lyRIhlZCOj+h0QzlGHyd5qrTm3Sx7Pm1NTyAo0alQ9Ghwr
            SCM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBaUN6NFFR
            NVlCY2lTUWdnVjNKcHdBb01MejMzb3hFQXVFNVhydDJlem5xWgphbVA0K2NDWnJU
            Q2Y5N3BMM0FYREV2TWt3YUFQdndvRTF1QW9VYXBLbmVJCi0tLSBVM282QnFEMHZG
            WmlYMXh3d1V4K2VWb3FINlFsQktNQ1M3Q1ZCYWkvSEZJCgN/s3phYbPSeIbxad7l
            4O5Phc7TKoMpnbpxlMyr83QDS2p6WD7Ggh+esPoVOIJ7DFZr2QfOmrjwEIhGJuEj
            cjc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-05-21T06:51:36Z"
    mac: ENC[AES256_GCM,data:qKP/Xdu702/fbXB0TNX5IsV1n8ePoVMXwXjcOe2dywbTAqPZ00TvtbiL1/VGWWJ9J+x1A8fTM3WAze1AR95R4k7fUA7HNdJpoU6Qx88NL/RZsS9uElmifM8ZbRhcqdQn858D4g8W1veTaoumbH7QGUmWSvU9QzeYU5RbeCDWVMo=,iv:aC5N+Fv1DZTIkaYnlrgxWmW44pNMsiUBMTvTm+/d11k=,tag:NzoDSVZb+uBbhitqDAEmSA==,type:str]
    pgp:
        - created_at: "2026-05-21T06:51:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//UDbopjb9IufvZkqyMpbfg5pqwPNntlGupw87q1rPs0qd
            eu9raQ1ey7RfYS6N0dheRsgMttZWrZVF2Vl1OAux7Wt0YXvMA+riGRKPxsm/mchM
            fo8yghEDlkcGrCBYSnQXqGZWShUv7GU8iGKMzvM+hv62S7Nl5xgrPbTV9bHDomCV
            M7h/c39R4rbW7GR8OAPOo5FJM27uo46jHa0iaki+QUVz7weYUvs7FApOTtZfNyCO
            GOriRr390d2Uzmh3EVLNWjTmhiW4iXdQR8NVI4tqgNKpKB6n/v/9Sr5ziMPt5tB0
            2iS+uEyJMF4nnbNEVV2FJfGIljnxJnUnVy4Skv7nj1HV3VrmRZwuhkEyLWLfJvOK
            vAMvmakArt6h4bVphVMWybJ9mkjqOtLi+gCNUQ1xDXab4Uhvbzzw91XxlxvaaOni
            6tj0VvlpRDgZkMh4Hg6X7VkbARtc3pdvXD4tQp6y1dcgB1JR2t+wDtYieUhEc6qB
            yxGnhDybjeiNfkYAuHjmJ3M9qSdbAyQgyLAdPXyWYhuMKPmYPR2kM7J+0NZon/j8
            nEvudpUTfLQbN5jkxVBihgW3mAfQHSGrUswGkKtNHIK9RIAc3P9pHBbE81iiul1a
            x4AmF4zGtO9CqXb91IEmBWuc4n01dmLbEhbMcP9ZBk5gY2d7/j77PiIqvtxAd0PS
            XgEdgiNynexnJORPhVMjBGrAkFOCiX7r04Wlfje9FyiXAmEXJ9mgGPPVFHXBb3Ho
            o9pnaOqXmxEz4D6fOBTSTZgkdEpYPi9yDP1HH/4HH1bCwwuZRDd2VcEHXqpaVSw=
            =mYKo
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.0
