apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/instance: forgejo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/instance: forgejo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forgejo
        app.kubernetes.io/instance: forgejo
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:15.0.2-rootless
          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 2222
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: forgejo-pg-app
            - name: FORGEJO__database__NAME
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: forgejo-pg-app
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: forgejo-pg-app
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: forgejo-pg-app
            - name: FORGEJO__service__ENABLE_INTERNAL_SIGNIN
              value: "true"
            - name: FORGEJO__service__ENABLE_BASIC_AUTHENTICATION
              value: "false"
            - name: FORGEJO__service__DISABLE_REGISTRATION
              value: "true"
            - name: FORGEJO__service__DEFAULT_USER_VISIBILITY
              value: limited
            - name: FORGEJO__openid__ENABLE_OPENID_SIGNIN
              value: "false"
            - name: FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION
              value: "true"
            - name: FORGEJO__oauth2_client__ACCOUNT_LINKING
              value: auto
            - name: FORGEJO__server__SSH_PORT
              value: "22"
            - name: FORGEJO__server__SSH_LISTEN_PORT
              value: "2222"
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
