apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:epff9hzDMa/Sz8Q6ofe4akZiamp/xKJv3xE7jxzyY5KqSrKJbzFwog==,iv:PaK3vLtdmHuNwXUwnFQjx7JLjXtGaoNf42bxKodwZL8=,tag:aDweKz+H8K/UEKiT6buLMA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:DQa894GT8nkEIapzdOQocDejwzXQbNYJ3nvpd+9dWi6q4BzWiA7AQgeC8XcLnjAGgNosFaOGVcVC7UrmqO1UJVTaSFV/45+Ptioyz/fg9T5/RRXgMkrkM+oqOb03p8Bj7SWDoOFxxJBx8U4WtaRDzL+SdtmjU2g+jELlwAnQYPA=,iv:X0LHKzbdEGAGQzQW+mexmBXmF6SQ1VDy2SZ6jAvaLPM=,tag:jk7bFJ2jLqB0iWBjxdijoQ==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:G2H0ChMcGtSXg3ckJdvt,iv:ysiOseDsK/VNpP40+vxvM2GMChrE+6dIsJLem8WIRXM=,tag:L8yFjjhMdL8wmBMrrfp/cw==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:OE/J6A/x1dxyYclYV/T8Yg==,iv:GhSjMn/AB7riBTTNA98mzPHy1AbO+9Az8o1rdrvcIq0=,tag:vsPzm17TuRYcvKMYo8IjPg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:v1bsO8sN7CjKgnLsJtZf,iv:+emuo1fTV6bZtdOG97STExQwLVXVyWVKWKjRj/vh7eQ=,tag:iEKMzQ9NQUylfNAj4PV76w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:QxIJwbssLSFfm3/tNPedvPAcDUH4IueyrQoKxsOBeRqVZcOi6t4VYGIU4/fRoztvXWrFwEV4GKYLdfxl,iv:DPTVjf0SZxGIbQLnSeJ97zycPn8LshWSxByonHQJW1s=,tag:////+GESTIqO77gV+mADCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabm9JRVJLdi9wbkV3d0JK
            RVVCU1Z4dVRGZk1PcnhmWEFYeW5HaVJGUWo4CnpOaGdpdnhxUU1SbDVoaUU0WE5Z
            cTVDWGJCTnBqK1pZcFlrbEh3b095MVkKLS0tIDFMeVBaUDBjMldQR3pKWUJ0VE8y
            UEFzZnVsWDQ0bXR2TEJJUjY5RTJiZ1kKrkbs+bW/vQa41G2B+Tc6NcctgrTwSr9M
            xl6TDmB6hQsdc7KJ9+JkQHIeNs3oGrOYxGuAqQHAuQdbTR4m0BweJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBcVdUa09X
            Z1hJVWs0bS9ySkdRWWVGLzZ2SVZkcEhKbXhlcDRId05sb2FBZgprSkFjQXF3WVRJ
            Z25qQi81NHh0TmRoQWhlNkVZQnhjdVU0ZSs5S1RvMlVnCi0tLSBzREZ0VzFTc3Nq
            UUUyTytNVjg0VXhEckJoZ2ZTaXNBOEdqMjg2U0pSYXlvCl7PMWDOGw2jLB9drFD1
            sFhDynVgi/Wyw0pIL6MfU8GXVFSMKEjZXItSgnzmkqmDYUdZ32v1jv/xFIuhNgzN
            xps=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBcm5Uc2Z6
            eUwzOThTODVWbjdaVEdNczdBSU8xYkIySmVhSnRNWjNMWnZCcQpndytwYnFxNlNq
            K2Z3enFLRlRkWVQ0Z3dWcjY0bit0OWdKaG8wOFJOOVpNCi0tLSBiRGhOeXpYdDVi
            UjNRNlRzdmhoeENVbFhvbG5jUTBsV1ZhU0syWHBOTnlzCnRdqVwMqMFCuFIwKuHb
            3Y7KHA8wSyyY5Az7CaAeMEkV4zbrrFdUcr5+xsYRTkHGsisKDLmZ1jJuVp1qcr5M
            J4Y=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-15T01:26:42Z"
    mac: ENC[AES256_GCM,data:NW8L5uzeCSFeCuAEKRaEUblPyLMINf1z/Mauk3wYdK7rre4D+bOkT7HoJZdZC9QEWRmmXDjAioz9IMIyhpkzgfs0notuEEt5TDgID7cWRxFUAHdrjbafrnFxy5GfYJW2rV1y549xVk7On6KNJnxK6BpEmPaXWqXMS2OzuyYDsRo=,iv:QutRW15AL5h8eRP3hF8xHHO7sXXKU4G6jEZeWI9B5MY=,tag:9axF5CinLZwfBtq69HcNDw==,type:str]
    pgp:
        - created_at: "2026-06-15T01:26:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAwTEfs5zKm3BAe4JAXd12J99d0Rv5FjJyryTANmrrzqT2
            +wT4Rjsil/zuEjM+nH5SGfFXukBplZy7vl612HkHdEwXIhTKOyQ2v7opw4KY8QG3
            buTR9zmDlCROvgpTxHau43bbdApweeED04sHdYqbOwjntpiZRbj9ZQ4InLaJqUFO
            klHvgkheAZ9Qw+Xz5iHO6YHdHeDCqOKZhhPSfBibN/YQD8bKJTpSBDQFtjhNKmkn
            1pKGjEHL2ewtMeGnngyWkyDkJRXZrdojMjs+sVMwlA3zYaEuqTO4Lw2GBfRJLx3H
            EfJK+MHYnA1eb4Nu2SivWNZ6pU3zNe8DxyDvPNSwEP8c9CyQPa3TMYxwZmOttco0
            /pV1K73Fvu8mkzLqqD9Kfb3Vjrjb0d5Muaosh0Nkk+eGl6VcepIfU5r+EQmReiNg
            ORJ7Ux9952+um7UJ6rx+DJShqLKcu1Q+J5BcsJkmZ84l0Y2c8A27aIKBLul3X99m
            4eyTAzd1dJTyfZdXFDofPi9+bDbEPTm2VOaD1a/xwi+aMsqKeivD2mwJh+eAlmYh
            350uV1FIxqE1ZKsSL6TfBnI0ZwQkW4tFc2nhTQM/ogqFZC5OjE/vcbp4O7kAQqLp
            RKgL0ALsDnDY3p0ZiAyOlxpRVicq0gwm+02AYenYczJyMp0kBm54OnDxKgZdPbPS
            XgH7IUWlOqWFVqzPlJuPvXzW+BaaAOtZQDIp/6tVdaRotTB86Aj5I7OuUF+/Vc8Q
            aTN9Aa56m3zWwzKz9TAJhoDMsauMVs0K0KcBoYSDda09pAKfFT/iyRHaVqVgNjQ=
            =gIZQ
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
