apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Ne5ZZZZA55DoYOx47bMr0J4n4/YhFJfYlhtbJRpYBuKQtjcc+YClWw==,iv:fYUV99mCKVaPo0LYDI7RAl7S/JeBCLq0xpeCp45Ic+M=,tag:JcgKXena4PDw6Jx8ZhbKuw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:yej+KBsXiz0zNGerQgCbTv4qSQyLGTtI0QGoz3Dxwlt2pZgGh5naZEzJKxjOLuH2GRaX/W2EZ3z8w0xSgV/dHbb7pHxBFP0ZNzO99sP3og2iDzqNoNriGwKOpAC4UYKuRUEFnvkX8Q7PTlFiNGgbajS3GRoI3Ef7jmnNkV3HVFc=,iv:sZYwM+c/i2Ks7ezNNwfoatMxyZjwtkn3nFol5y4rKO8=,tag:PX4N32BkdBp1xMQeE4vyag==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:Ast//yOkXDvMBvcNoGvc,iv:AqWaGrBw+p5F3EZPU4tlCT/nhHcMPh/zXJ/43bOLbVQ=,tag:QKf2Ht6i9YvE4WwNLb6I2A==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:MPy0emqO8LJsJfh7kh80gQ==,iv:yVcmsRhvwaKYkqXhTP0ET9Uwb1u6HeNJKGE7fkgbFyc=,tag:IAq1GH74QVmQfvA8W23v2A==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:97gVZ89awKBO/TBAtGP3,iv:QnefLwwPmE4eJ/0b2jmopV2ikzJ6iSRqm6hqitwVGDo=,tag:wYIv7gEsJ9eAeoM6b0Nf3A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xEcsxuOm4u184okCn4wct1NXpID2Sho5huVDQDdL5g9ZyHb28EX+rMSWoX+SmYxBGPU8DoQczOBYfYwy,iv:qWvTGqQarHdb4TfIkNHGc/iuK/lOS/RcGdTc9z+vs3o=,tag:zPuLYO52IltXRgHINaly9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZnpQamVOWVZnOUxzU0JO
            Y3BEdjE5MVRrcWxaRW9mNTVia1ErUzVmbzFrClBFQ0VZUnN6RWNpM3ZNdGJTRGhI
            RzlIdFpHc3lHOGsvdjFhaWg1TGRHQVkKLS0tIHlMbERXc3VXR0k4dUpzanhHYWVF
            YXJZVkhkcGFuMURnYnB2WVpQYWNIa0UK5truTwC29fpdivcWFhs4aTcYbWTq0PXl
            f6QS4wIL5HfUzugtFhtiKXJ8/ZHPu864SfAmnJBdSuQiPOX0bUPboA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBL0d4WitJ
            M2hTdTdSQTZGVStNcGZhWThwNFV5eHdFOW5XTDRDTmNrSzJ1QQpDLzhpS0ZkQWF3
            MDFmbWtjenA3cFVQVEFyR2NCU0FkNmFHTDUwb0RNSXo0Ci0tLSBraklUZEdPS3RU
            VjVTVTRtVS96YkVMbmU0TTBIazMydWs0ZmdWRUV5a004Ch6zwP0FmMTUnO+t/C7y
            C/Q6EpTwQsnIQjECbnPdnqaAFfq1b6M7qve0m77wmLlETmwQxSZEP51mkVa8kiSG
            oMs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBeThWNTd2
            QmJlUlJYMk5Dc292azBDZVhjZDl2dHBHY3VhY2lEdFl3VnF3egpSVjFLN2hqT1Nt
            UU05Z1NGejc1UEtESHJvaFEzUXpyLytoRWF5a2hoVitFCi0tLSBIRDUvYWVHL1c0
            enBzTUo5Qlh2RGd0MTU1WFJlM1FkVFlJSlQvV051OFpVCuOfjsHLHp7WtqSmeK5T
            //qYen6KyvPhM/zhBOIUgMtxha54d2/Gtb9bHmNItC+rcAgNGoQZOgKbTJASQdzm
            ugQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-17T21:26:44Z"
    mac: ENC[AES256_GCM,data:SSd6Er9vMZQNwWh1Rp8z7RnHhiE2LeaLGz4K4BiSvIJn4m0wQacjDXEFKBitJVer+TddHFvvXHldrhnL971M70+RrxhhWPwcMyN5OLCYzSIAD8A2bbt6XZuslCA3A59aerDd1utZBr4SzRPAAzFAuW56wiJB1RpTQUYSwlnw2oA=,iv:GFL6DtZD1oxPBYMSMAiII4K/qq2F/uhGbADYvDj15Ls=,tag:wfSpAanBvbmdN/Qaw7oWzQ==,type:str]
    pgp:
        - created_at: "2026-06-17T21:26:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAg4davApA8oyHp6qLrHurq2JSzsd06PHbSFTfqPdsAYo6
            kHW6CLCsqy4T1UyHRVqoXhSZYcNmE9UJxrvJqh/um7yhr2tc4dn5MtkxTIeT1Ayi
            1qHcWFSLRH9k85BuJk7ZVlz4iwu4uVJyiDZ/RGMARYAhFw17k2ANdrd7ToIm9/TJ
            QM7oFaZJpLcPWqfa6s/9f1wvdoVzzh95rerZKaQcq5esBe3i1NQenuYe6tfy1zhJ
            loEWR+ycYWNn9q+rEjaxu4rw3hTxCEHWUlfeOJrribYJ+Hyfh9uH1Zl4ajn8nYQh
            3MKUpkkOYWo8f4oCOP7PQRZG+Yz+muRo2dxutwx961nEK6qLfLvNXQ8v53sDxxxJ
            Gr4XhMy6HIopDaO2h/el4Kl6VfssrbsLyYny6HNO6H+AmTFDHbejfD3XNL5od/10
            0lp9JHtCiGCUtAQMDFUYPvDdKdf3pYYSlUpK0fbU9jYq6TVm/DZNUOGwL1k3oZOC
            LpA+GMjXwpSDoPCwEovqNglVRLiSV3BoLX8Zd6srAdV6Mhk1+PSgj8QlOaPfeAl9
            2TevHWCSWxn1U2uBQqoqXOMe4+mGwmhXe5zJjjdE0jb9fUTW0cRUvbRK2Uq4lKqu
            Mk1DHO58ZR+T4Pl1iEeEF1/WLRJJtXch2Qt8+XbCxHHWR7otiIdM2nibC3eJiXLS
            XgF/g8ayaz/ZbhshUAX1L2g4DsqBaHY6Cdhs9/1f9NKm+GcwNM8HqrwEWTyDgbZe
            bbGmXfpY3tWMfdrKLn3T1dDcK7ACKKfIvV0JVCyB/IIjzZ1zgn5LGIsVQlcgqv8=
            =1l/5
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ldap-account
    namespace: mealie
stringData:
    dn: ENC[AES256_GCM,data:ikUBL2hy22ytILGK64UTBUG7i8gVXg4dON0uc5YvgfKLe2Lf/VGjpnTPOWtF,iv:PDCI6u0UW4EjEoA3qTVhn0wwjxZFOo3z7xIOeeLvfkA=,tag:bUCkPDDHQP3dq1KuSfuE/w==,type:str]
    password: ENC[AES256_GCM,data:9B1WRyQJo1l7ujnsXH7j+HbCOih92U79+Q35Ftlc7Iqd70V8hZk9FgXadwlGHSoo0aPDewMwoHJk0Whl,iv:sio10J4Z99yEQGf8GTFn2ZD6NAJ0VssMxh/RY//44z0=,tag:U/qIAERqKUNy+if8v17kow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZnpQamVOWVZnOUxzU0JO
            Y3BEdjE5MVRrcWxaRW9mNTVia1ErUzVmbzFrClBFQ0VZUnN6RWNpM3ZNdGJTRGhI
            RzlIdFpHc3lHOGsvdjFhaWg1TGRHQVkKLS0tIHlMbERXc3VXR0k4dUpzanhHYWVF
            YXJZVkhkcGFuMURnYnB2WVpQYWNIa0UK5truTwC29fpdivcWFhs4aTcYbWTq0PXl
            f6QS4wIL5HfUzugtFhtiKXJ8/ZHPu864SfAmnJBdSuQiPOX0bUPboA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBL0d4WitJ
            M2hTdTdSQTZGVStNcGZhWThwNFV5eHdFOW5XTDRDTmNrSzJ1QQpDLzhpS0ZkQWF3
            MDFmbWtjenA3cFVQVEFyR2NCU0FkNmFHTDUwb0RNSXo0Ci0tLSBraklUZEdPS3RU
            VjVTVTRtVS96YkVMbmU0TTBIazMydWs0ZmdWRUV5a004Ch6zwP0FmMTUnO+t/C7y
            C/Q6EpTwQsnIQjECbnPdnqaAFfq1b6M7qve0m77wmLlETmwQxSZEP51mkVa8kiSG
            oMs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBeThWNTd2
            QmJlUlJYMk5Dc292azBDZVhjZDl2dHBHY3VhY2lEdFl3VnF3egpSVjFLN2hqT1Nt
            UU05Z1NGejc1UEtESHJvaFEzUXpyLytoRWF5a2hoVitFCi0tLSBIRDUvYWVHL1c0
            enBzTUo5Qlh2RGd0MTU1WFJlM1FkVFlJSlQvV051OFpVCuOfjsHLHp7WtqSmeK5T
            //qYen6KyvPhM/zhBOIUgMtxha54d2/Gtb9bHmNItC+rcAgNGoQZOgKbTJASQdzm
            ugQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-17T21:26:44Z"
    mac: ENC[AES256_GCM,data:SSd6Er9vMZQNwWh1Rp8z7RnHhiE2LeaLGz4K4BiSvIJn4m0wQacjDXEFKBitJVer+TddHFvvXHldrhnL971M70+RrxhhWPwcMyN5OLCYzSIAD8A2bbt6XZuslCA3A59aerDd1utZBr4SzRPAAzFAuW56wiJB1RpTQUYSwlnw2oA=,iv:GFL6DtZD1oxPBYMSMAiII4K/qq2F/uhGbADYvDj15Ls=,tag:wfSpAanBvbmdN/Qaw7oWzQ==,type:str]
    pgp:
        - created_at: "2026-06-17T21:26:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAg4davApA8oyHp6qLrHurq2JSzsd06PHbSFTfqPdsAYo6
            kHW6CLCsqy4T1UyHRVqoXhSZYcNmE9UJxrvJqh/um7yhr2tc4dn5MtkxTIeT1Ayi
            1qHcWFSLRH9k85BuJk7ZVlz4iwu4uVJyiDZ/RGMARYAhFw17k2ANdrd7ToIm9/TJ
            QM7oFaZJpLcPWqfa6s/9f1wvdoVzzh95rerZKaQcq5esBe3i1NQenuYe6tfy1zhJ
            loEWR+ycYWNn9q+rEjaxu4rw3hTxCEHWUlfeOJrribYJ+Hyfh9uH1Zl4ajn8nYQh
            3MKUpkkOYWo8f4oCOP7PQRZG+Yz+muRo2dxutwx961nEK6qLfLvNXQ8v53sDxxxJ
            Gr4XhMy6HIopDaO2h/el4Kl6VfssrbsLyYny6HNO6H+AmTFDHbejfD3XNL5od/10
            0lp9JHtCiGCUtAQMDFUYPvDdKdf3pYYSlUpK0fbU9jYq6TVm/DZNUOGwL1k3oZOC
            LpA+GMjXwpSDoPCwEovqNglVRLiSV3BoLX8Zd6srAdV6Mhk1+PSgj8QlOaPfeAl9
            2TevHWCSWxn1U2uBQqoqXOMe4+mGwmhXe5zJjjdE0jb9fUTW0cRUvbRK2Uq4lKqu
            Mk1DHO58ZR+T4Pl1iEeEF1/WLRJJtXch2Qt8+XbCxHHWR7otiIdM2nibC3eJiXLS
            XgF/g8ayaz/ZbhshUAX1L2g4DsqBaHY6Cdhs9/1f9NKm+GcwNM8HqrwEWTyDgbZe
            bbGmXfpY3tWMfdrKLn3T1dDcK7ACKKfIvV0JVCyB/IIjzZ1zgn5LGIsVQlcgqv8=
            =1l/5
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
