apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.11.1
