apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: flux-reconcile-on-push
  namespace: argo-events
spec:
  serviceAccountName: operate-workflow-sa
  eventBusName: bus
  dependencies:
    - name: push-event
      eventSourceName: github
      eventName: emnt
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - push
          - path: body.ref
            type: string
            value:
              - refs/heads/main
          - path: body.commits.#.modified.#
            type: string
            value:
              - "^k8s/.*"
  triggers:
    - template:
        name: patch-git-repository
        k8s:
          operation: patch
          patchType: merge
          source:
            resource:
              apiVersion: source.toolkit.fluxcd.io/v1
              kind: GitRepository
              metadata:
                name: emnt-ops
                namespace: flux-system
          parameters:
            - src:
                dependencyName: push-event
                dataKey: body.head_commit.timestamp
              dest: metadata.annotations.reconcile\.fluxcd\.io/requestedAt
      retryStrategy:
        steps: 3
        duration: 5s
    - template:
        name: patch-kustomization
        k8s:
          operation: patch
          patchType: merge
          source:
            resource:
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: apps
                namespace: flux-system
          parameters:
            - src:
                dependencyName: push-event
                dataKey: body.head_commit.timestamp
              dest: metadata.annotations.reconcile\.fluxcd\.io/requestedAt
      retryStrategy:
        steps: 3
        duration: 5s
