apiVersion: v1
kind: Secret
metadata:
    name: github-pat
    namespace: argo-events
stringData:
    token: ENC[AES256_GCM,data:nuyUkyTG0vK+Qg11453g4Dh3CGeMJiXSZEe+67PNLTAlxGpksS+pCGmSFuds6pleT5NtcK6Q06NQz0mEvHUSvPJ6Hl3JyYXI+GyMNfR2m++fZsoYgxAiJZyY9qV1,iv:yrTXQpfwKZC8ZFy1nl1Zshgq8KlRjJDJ7NL1jFrnczU=,tag:VvzfnwMp9JGtIFEuFaUu9g==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT2hudmx4d2E0YXJ3SzJT
            UEo5OUhpUHVhSzdpNGlXa0lBSXg5ZGx1R21zCi9SUGJwWkx4MFpqQmFqRHRvQ3Na
            OUdVTmE3cjFiY0o2QndLenZQaEJTUE0KLS0tIE1URERuVVArYVJNeUozZXR2bGh3
            U0IyYWtUK250c1h1V2xTVHZTVUFLblEKzKXcVBr8OTqPknpZBOBZvhETievGc1iO
            mQcuYKwEtTzJ9tsIYJqjc1AXMEHzsZhNcZHZdK4toBG8sOePMxKg+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBOHlkTGJh
            NHk4dUFIbVZDd0xXcWxIVkg4OWRxRzFZaS9STnhRTnlFSjczeAptWHZZMlhnNTl0
            QVJ3SmJSK3ZBSVNCOEtCamtEN0tMWnJBelI3dStvUEQwCi0tLSBLVlF4T01aMnZT
            VUptd0cyS2lRamtJa1p0MXREOEc3NFNCcHhPVEJBYS84ChF1lZYgR66iwgYfkoWQ
            U/npYgBML5vGrKNOq2j9imxfIP9C7XghUJAZf3D9HyJ4/lpgH8sEzL/A8D/CSTkE
            oJ8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBNXp0N1Iz
            ck5kNWRQYS9lUFE1dUtjcmt6RGVobWJGQ3ZJYTJaWEdxQUlzRgp5NEhKaFd1Qlow
            Wk12QWNsWHBuZWhmdDZoMmlYT1JWN3YwN3o5cEtpMzRBCi0tLSBpWTB5ZWNUMUZj
            N0lGbFNwYTk2UXJVdXlkaVllMHg2U1BFQjlFTkYyMVMwCj7qKEcjkbLrq3ki5gvV
            GzTdiA4CUQ6LGIFuobG1w0+aqQfynE0PFN65cqbR62bY1Glcyn2OV9gj9aDYL9xJ
            wKI=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T01:30:39Z"
    mac: ENC[AES256_GCM,data:OrLPQCsbWb5411SzigJ/IWSL/k78ggOZuG2Xd2e5RP6LapKzzsa6ScVe40U5Kgf6yxrtzvrr9go9jOAQDe/1WG4QBUJ2Tc1/L0vJYfjEGfXmV+8cL7qtt9vhEj+eR76JBw6CgCVtHjnq3kRkfgrTvvo2SJ0JL+lmVb3G5vFmhHA=,iv:7mhGtfeuU3SB6Hl2U1w84rk+PAOKfk9pMpn2qLSdLSw=,tag:+6ZWnx0rpplzvcGXz6H3Gw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAlCDpr+LbsOo7UtVoTQ85gq5IqnTPkFB9E5ixXTl0Fyjv
            guMxXrOfJY9kvGjFmY3BVOHQ8R9Mo3lvSReCG7Cyw+oi1NoC6ydywrU7TWHPMi1L
            WkKJ8TULMMhS/UDsjwJKP4jAM42S5+EBXf8/FZIdFgsRIhzPgSu2/EUqeNaOVhb6
            JWPRiulbkmpQIpHAKS6a+3CH5DEsDS+pY6ZPxq6zhUyyOW8DBjwH70KeeUi/nxLL
            RAFrRF6z7nvwkCmCYSv2JLjCTnrtZVOUN1qeb9w3ajAqgVY2Sas2XXIbgRGgxok5
            k54zYL4yX22ayPm9L9pekkXK3NVyFgx3gBgG3aksLgFMMWESWu0I2dCTFsoY+00G
            8QpR/NjueU1NboSUIjXOVuXaFoZz2Q7IAgBuio+DNPUYO8/IPGe4lMdEA7kC9b7R
            kEy+cs4W+5B//ICwUCE8wAL1xlcxa53k8rqAAclu7LmzABQrdkeDZzXwy1pRuiHb
            iv4R2Oyy0uhxmW85ZQ7i6ORT3gN2XyIEn4t480CfbsWJMgHaILLwZTlqhmsRg+ou
            CMw+zZt5nSPpjzZxsrATaKcdhsW+isO0dgnVlunPcqA4DUfAZFWXrscCFxQ70wo4
            B0tT/ytpMkZgHVelnYjnYEcv5UNYEAeDTDd40C56HRrYFOJhEYCzzfXF05Is+GnS
            XgFluXADQWq3FXX4trYb7Q6kQPypDhUTcMBh6vTkUJA5qBjCeVmve0BZRE36asaz
            igx5cuo6xHvUchI7OmeSP7/H0Pw5MiIftjNGqhQGZ9O5qUx9L6kXcswBENDYJBg=
            =Lcoz
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.1
