apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-seerr
  namespace: seerr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: freenas-api-iscsi-csi
