apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: recyclarr
stringData:
    SHOWS_API_KEY: ENC[AES256_GCM,data:JeWgwzTjWF95IWIKDGwxvkr85LGZw2WrCRolTRNOaP4=,iv:uOP5nTFBLVfRmlwbQ94AL9zBScRJRk5xrwhhQZ8Seqg=,tag:n8yLLCTeCateI1nhweUQbg==,type:str]
    ANIME_API_KEY: ENC[AES256_GCM,data:kyQpURcuaOQB/Uo7DrvkEN9eiajM8k2V3E7E52OjDNs=,iv:0CJmSHs+hV2Wt7jcimdb3fih/snpJXiMCxcqUj66exc=,tag:BrS1fyEwS25FtHDDmWAeTw==,type:str]
    MOVIES_API_KEY: ENC[AES256_GCM,data:u75sL6dqLtbs9k5Syz8ucOwl+fV1kYOkxZDlu1ScDR8=,iv:JsazYSvOZBbKpqM5dZradL+C985q+Qj31RRmujmzYIw=,tag:gDJhQSy+RzOx86PMsKHclw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUEE2ekt1ajIyOVFTYkdx
            d3NZZ01IbmdtNFJpYzBIS05nNXhKL1hLTEdZClZkZUpQMWhyRTV6V3pTaDMxVFRz
            SHhvNS9hUkc1RVU1TU5GZzIzeXl0aTQKLS0tIEZPdVdJcklNeFpHeCt0aHBGQXNF
            VnpocEJKeXdycGJIOUFIQVlCVWNjY3MKQm7gA8fxwPpXS3mehfbtJbzws+8UzRv4
            W8bpmBHU2YART/6tNRgWtgZBipYlhe8nFa03zDAeliU47txixOOZcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBc2syOTFB
            ek9PbUZMeGYyYi9iUVNoVFJEdStyYW0ySnJRVXpHN2tXOGVzNgpGdWZaRjhyY3oz
            Z1FUbjVYcytPaU0yT2FFczVGQ3FTQlVRZmRqWE1vOGtnCi0tLSA4RVhTZjJIV0ZU
            eUZ1THN6M1IxS1hBejBWM3JRbzkrVUFsZ2xLUnh6L0xjCna7mqUVTP9qXgV5sl9H
            CRneLj1r+ys9O7KQQ/ArORsf+RUnDsYAZ7hwCLyevsQlJG2KYriS3uPrIeG622ur
            PbY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBd2NhRStP
            Q2FoblNJdEk3Z0ZQUWN2aHVHS3JaODJYaFVaa1luNkNUcmJhSgoyTTBDeHFiUmhO
            S244ODhpN3h5SWg3Z1dSNnM1bDRZZzJJTUZtUzRkMGIwCi0tLSBvbEprNlNDRzh4
            N0daVXdqL2RIQXAvME5DamsyMkViWk81Q2VMUTZvZVFZCp0lObEJ5e0my5IYgGwu
            +0tIT7196VkdNRQ1vQQpl9ps92iVwROFLeQdwRhiW8KqTDDLOFMCGc8nmUofR8bb
            tlc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:56Z"
    mac: ENC[AES256_GCM,data:67SijQQHByFbwjX5or1Xc0mzQ4BNc1HkI0KrdpfkbEmD0XV4wm6r89ELHH/tFgG79WiSlyNBNU4hb0PDj//m/XrCD30983TiOj7cFmcmuS0gpjMdDwt3fQIJi9ymuQSYp5isY9bSFBNGslf13xhAoU6XeeOiSj2p0uplNs33TTw=,iv:bOIbrFDDOmkkOpbqvUw4VQ8Er4c+iyJtHJDQhgPnqrU=,tag:bNyfb6pTspzKVL96NbtlHg==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//d73zq2gBskvsDAoI8Uu9HzLCr8mv1Iev9GHcevFMzBBM
            5rMMpokCjFNLcjUBU2huRHBwVQLe0wq8iDaGp1I5r7GiNc7FZY+qfWsmM/3JnSxw
            ZZ53po1bbZLyOJ7MLyqrsyLHoflhzsdZZQr/ydLRpCmxMxu9/M7T4M9TaZIE9hjT
            fXTJJIVNsXorPOwbNvo7ih0kqKudccsCxcVHVchKpWI18xF0udsRINd3NKTkl7XJ
            f95oDyeW05eyCbPkEBIjvak7SQC+ZBk4H1hiw0DZ4r0BfiMLeTeyGdhQRMZ/yhnK
            W8Ad+XGZx5RrRi/FytAMw3zPHBOBD5WZ8g7wttA2NkOdCT+/JNbl3BKYBLOYWjfl
            GhS9z40DugBDO/lPGmNnhs3xVsWqx8Lq8M99YsSdvTZ7pYGAOR9M+jFQOCryMOJM
            S2ApeN3+teO2IMcWBcGsxmuvu6a5i0pozyrS+RKCeyQPNlhHy/ctGo1xpP1hErmo
            YvR0lYP3L+dDYwfvCmRzkjwnViwlEmkby7k++g5uoTOCLzuCuF6q4OI8SighXlyx
            cCSaDcP2mFKZSf3Sd/k7xhdm5GydqXlZjUI5f4rHYbjZVyyoAKkiWLZm1ao8l5GT
            1X/rNYgom12EO44RYQ+q96eUTmEUJ5jHfu35lggPwBiJDKBuPho/E/+bj1TUcKLS
            XgE9cs17TXMVlWKQvI0J9TDTL02KvSr2FDlK0evBr9Pf+N2Qdwwbazfcsdi5f0Nk
            Lgl5/5a761SBCvlYOLXgya1V9Ui1cQQU4S6VaWe4ufPqHUKmqw1N9NuDgGUk2x4=
            =VYt8
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
