apiVersion: v1
kind: Secret
metadata:
    name: headscale
    namespace: headscale
stringData:
    oidc_client_id: ENC[AES256_GCM,data:uTYakegHrxCrzIEb6VDcKZrZgh14P61pK6r9c2wX8gPTaUkOBk8J/A==,iv:j5ePfB7RTTcfLivhQsyT48xfWZa26++BWlJ9bK1fsTk=,tag:q5COsTVCF7ARwRIsel49xQ==,type:str]
    oidc_secret_key: ENC[AES256_GCM,data:/OU+Cf4exalwrHl61i51MnydD/hJA5c1/3x08uF6PvhU1MIq/DRrqyTKYJ8WT/MKcPgdg9DEN/bXcencLN7Y0e8vyww0cN9T7KcY0SjrAjF232Ts88T0XJDtyoS76YA/0Hs8JpTKb7Ut3+NTvKvcoevcdl+b5n9ZTPxe9hatWmQ=,iv:knZN4/p2BJPLakTOaTq1WkMqG7YYsr+L70k66mrpJbg=,tag:TWgSaNy0k8i5LVcjlB/N7A==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNnJZVGltVWl4S0VDanFo
            QmRTSWpINUxTOVVWRi9VMDV5bXBtcGgyYnljCmx2Sjd1SDlvdWFnMVFwby9oRW9i
            eFVQT0RhQjVxRWpuK3lhSHRoQmpyNkkKLS0tIHpMN2s3MlZZREJOSlhQbGdFeVVv
            WTliSFZRQjIwU0ZVa2JMY3l6N1J4b28KMuIt+rHG8mRrhmTcFxR++87d9uYEm7qv
            KLfmRh0E+VqVpGUKooUyemCvoY8ZH0ePwdSs6rP18dAo7nIbxdoTJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBZ25mcThv
            L211M29VSkFLU1VMT2tkdUMrVzY2K3dLWE5BS1pPN2hXR2g3QQo1NFhNNm5pYzZY
            ZXo5clpFTkd2NERlZjlGV29MVTRTaWNTM09TOXdJREx3Ci0tLSBYR1djNnVCcWYv
            QnhzR3F3UGJ5Vk9KelVpcUo3VlA5c2RGNTJvTm80ZGVjCuA274yAFMQDyakqDTD9
            TbuD6i1/TTXLhCY0jGdd3X6R9xhUgDhYzoH5rp9kWOMh7Iu5W3BIxzGZcetAEFhn
            kNY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBM2kvVU5u
            WDlrY2dZaUo2QW5ZYjJ0NVVtbWk1Z0d1TXpzN3REUUp4em9KUQp2Rmk3eXdIcy8z
            NlE2N0I1WW9sNzB4NXFYN1cyRmFnTlJVb2FzQkQxdm1JCi0tLSBQNTNTQlpUOSsy
            TlRLclVGUlhaUHE4c0lTRUVzQTNIUzhic0hhb2tJNkxRCqn8kSkD00CaF5Clm5Hx
            k2TZVoIgFxRm3XRWODw5uHjaE2svpo9Ig8k1/AE1YHcAegaXunw2Q4yc2QWAz+c0
            11w=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T21:21:50Z"
    mac: ENC[AES256_GCM,data:dKH61BIwXGkSRDgW4KcSWg9CyMqeEsG2LER5qHOSFH4gs0lD6p5KvicEjFcdajBJfP3Gq3a16i99nyVEwgin69IXYVNqY5hSIsKYOpmV/oMy8ILKgx2CReq1Tt7kZe07n0+CL5DSgqobdB1o6B1Vq0dGfYJd/vxh5130tv5iPv4=,iv:rr0ptiCBzRehEoTePL5c1V/W3cgWymKYpXj6QmUHJHk=,tag:Zvw0eLslCh6klNoHvG11Nw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+PRSSQaI1UPE9QWRK1FaucGJwbWhdCna3XpgF6UBG3hWe
            PF0Zz+PG1FKkEop53GUrKEp63UdBKmxwsO2tsp7oFHi2akyCGO2y58ZOjffzwyR0
            rkDkfLPHHniImmTmBp3jSKDWQiVn3VgsONFsLbcN7NU5TE1oRRLNj9yXJS2zpw1S
            wXLrnDZAu6WHxHDrj8aHs8YZZigDmJ+IYWY2qMnpf61ZN4hGNBQ4cdZZufOTbXCB
            EO2rkOj8BAPQOKZnldxNTeAsWS7PyqB8kngfED4Gyro5Ka/T75h2M/lhHRcAc6ij
            3/MlFdOWI6fwZ8d5BB2y2d3zkP4HJevZyR/k3TxyLMUg5nxG50SUD6+etC2fMuEP
            jjPuuvFQRhW59x5qqN2Y7nnRgoh9gnG72/j+XxYFlSgg/zthhwnRBparlkGN912z
            aNXKKOBHCus3ruM6Wyt7IkYtVLApLZnrW83ifvTksSrQVuL+adwsX5Tb+Y3STV6s
            BdICSy9HOY0Kg/d5jZ/cUOsNZQVelfPzPw8snulwKvenqsWJXZmVNjl61ag6za9N
            pJLBRjIsRp7yjZkZOOd86Q7ak4iiVQl9zYNTMshoFt22Oa0nDsA7zsSkp6ZGmnIt
            huXlZ2nHPcAtGNTA9mtTavvd880P4366mMDL1/u1Pal57Tok34SbB5hl98CpKVHS
            XgHBHBNxp3n4GrB78zP4bhG9ADsgpmYwLRpSW2IPVc7ekFJQSmx4UWgDvKY1evhX
            ok4Nmgb4juIQQxYZYyvlOnqf0l00LCKumIGHjiS1ijGDQ6/9dRd9xARlyqPzPbU=
            =kP7v
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: headplane
    namespace: headscale
stringData:
    headscale_api_key: ENC[AES256_GCM,data:t3z/mVFO8meAnFFVfCjnG3hvm1wbtGxzA6VtbkiAqcWf1AmVw8fEj/YkdT/7xTP9IyFwMTfvdMx+LentPSwMvOBCLVCxc57MNs3QkHRiszWOTvGvz0Se,iv:mmaFcfn7TupoCpmN3CiVGlBhWAEjRtpQtC5/LDTdUus=,tag:tRIPBZo8B8M3coupTa2N/Q==,type:str]
    headscale_preauth_key: ENC[AES256_GCM,data:qOHiVbKZUH+h6zwkug4x9M8y6ci5Y6E2tgg9X7B1bGRYL6HQUOiCAu32imFUd9r2eQRwGqy/+o5ddY/Yd1qRfqfk+qX9mGGmBy1hsTTKV6JrS1fsl7F+Mg==,iv:HKivaQPCqQK3oeUm/mnbeNHYEUAoVfos2NIx4Br84Hc=,tag:dNiHlF4mNlVHon/2qPNmqw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNnJZVGltVWl4S0VDanFo
            QmRTSWpINUxTOVVWRi9VMDV5bXBtcGgyYnljCmx2Sjd1SDlvdWFnMVFwby9oRW9i
            eFVQT0RhQjVxRWpuK3lhSHRoQmpyNkkKLS0tIHpMN2s3MlZZREJOSlhQbGdFeVVv
            WTliSFZRQjIwU0ZVa2JMY3l6N1J4b28KMuIt+rHG8mRrhmTcFxR++87d9uYEm7qv
            KLfmRh0E+VqVpGUKooUyemCvoY8ZH0ePwdSs6rP18dAo7nIbxdoTJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBZ25mcThv
            L211M29VSkFLU1VMT2tkdUMrVzY2K3dLWE5BS1pPN2hXR2g3QQo1NFhNNm5pYzZY
            ZXo5clpFTkd2NERlZjlGV29MVTRTaWNTM09TOXdJREx3Ci0tLSBYR1djNnVCcWYv
            QnhzR3F3UGJ5Vk9KelVpcUo3VlA5c2RGNTJvTm80ZGVjCuA274yAFMQDyakqDTD9
            TbuD6i1/TTXLhCY0jGdd3X6R9xhUgDhYzoH5rp9kWOMh7Iu5W3BIxzGZcetAEFhn
            kNY=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBM2kvVU5u
            WDlrY2dZaUo2QW5ZYjJ0NVVtbWk1Z0d1TXpzN3REUUp4em9KUQp2Rmk3eXdIcy8z
            NlE2N0I1WW9sNzB4NXFYN1cyRmFnTlJVb2FzQkQxdm1JCi0tLSBQNTNTQlpUOSsy
            TlRLclVGUlhaUHE4c0lTRUVzQTNIUzhic0hhb2tJNkxRCqn8kSkD00CaF5Clm5Hx
            k2TZVoIgFxRm3XRWODw5uHjaE2svpo9Ig8k1/AE1YHcAegaXunw2Q4yc2QWAz+c0
            11w=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T21:21:50Z"
    mac: ENC[AES256_GCM,data:dKH61BIwXGkSRDgW4KcSWg9CyMqeEsG2LER5qHOSFH4gs0lD6p5KvicEjFcdajBJfP3Gq3a16i99nyVEwgin69IXYVNqY5hSIsKYOpmV/oMy8ILKgx2CReq1Tt7kZe07n0+CL5DSgqobdB1o6B1Vq0dGfYJd/vxh5130tv5iPv4=,iv:rr0ptiCBzRehEoTePL5c1V/W3cgWymKYpXj6QmUHJHk=,tag:Zvw0eLslCh6klNoHvG11Nw==,type:str]
    pgp:
        - created_at: "2026-03-30T23:27:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+PRSSQaI1UPE9QWRK1FaucGJwbWhdCna3XpgF6UBG3hWe
            PF0Zz+PG1FKkEop53GUrKEp63UdBKmxwsO2tsp7oFHi2akyCGO2y58ZOjffzwyR0
            rkDkfLPHHniImmTmBp3jSKDWQiVn3VgsONFsLbcN7NU5TE1oRRLNj9yXJS2zpw1S
            wXLrnDZAu6WHxHDrj8aHs8YZZigDmJ+IYWY2qMnpf61ZN4hGNBQ4cdZZufOTbXCB
            EO2rkOj8BAPQOKZnldxNTeAsWS7PyqB8kngfED4Gyro5Ka/T75h2M/lhHRcAc6ij
            3/MlFdOWI6fwZ8d5BB2y2d3zkP4HJevZyR/k3TxyLMUg5nxG50SUD6+etC2fMuEP
            jjPuuvFQRhW59x5qqN2Y7nnRgoh9gnG72/j+XxYFlSgg/zthhwnRBparlkGN912z
            aNXKKOBHCus3ruM6Wyt7IkYtVLApLZnrW83ifvTksSrQVuL+adwsX5Tb+Y3STV6s
            BdICSy9HOY0Kg/d5jZ/cUOsNZQVelfPzPw8snulwKvenqsWJXZmVNjl61ag6za9N
            pJLBRjIsRp7yjZkZOOd86Q7ak4iiVQl9zYNTMshoFt22Oa0nDsA7zsSkp6ZGmnIt
            huXlZ2nHPcAtGNTA9mtTavvd880P4366mMDL1/u1Pal57Tok34SbB5hl98CpKVHS
            XgHBHBNxp3n4GrB78zP4bhG9ADsgpmYwLRpSW2IPVc7ekFJQSmx4UWgDvKY1evhX
            ok4Nmgb4juIQQxYZYyvlOnqf0l00LCKumIGHjiS1ijGDQ6/9dRd9xARlyqPzPbU=
            =kP7v
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
