apiVersion: v1
kind: Secret
metadata:
    name: authentik-creds
    namespace: argo-workflows
stringData:
    clientId: ENC[AES256_GCM,data:B0fRoPHQXSvHGeGGUhi603kGtA8WokK4SCk25sQ2dYq/We/PZSauow==,iv:3WSYUeks7jp7A1kXotM8C6IuQDRTe5VVqOk+t+C4eVU=,tag:PH4XZlDWjHrHAj/xXmrV5g==,type:str]
    clientSecretKey: ENC[AES256_GCM,data:/VptI9Aykl1n2CcDBT+rX8LMyPnmkKMMI3bBq+g+Dw671oseHpPk3d8GPbAXSiUiccB44s2NsdoG6bMUu7ZZzDPk6cE3hKQH6rM9xc5PP+5ACjaAXfShuWhSWURpAyKPKEZxrQLtjogkgefsrWa/TyXe2wGvql1gdr7YpCyEspI=,iv:MncrHONSYGEYYIO/RfUldzuPzz9xJn7bDEw3YqQ1neo=,tag:znPe1IjruQq4+O3atnpNEg==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd0l0cWRmOWJQNmo4YlA1
            dUhpOFRncVBMaHJTK09rM2VVeWN5aHJIQ0JVCkNlM3FkUjdDU2NSbmRkUHFQUWp4
            cVZFSHRDNE5uS2lISlg0cE9UTHhwckkKLS0tIHd0Y0QwZzdOM2YxcGhkLzlPUnBD
            eUVTSG5TQWIwS3AzbHlITzdpSWY1bk0Ksjvyi2BnWW9Pj1a07g7Oqxzcy2KpgnNU
            V6h+6XuvHoX5BG1AGjSL/QdpMhiPtSQO71RSCueuAAGgV+BmKeY++A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBd2VwU01T
            ekdZMU90enlPeU04c2RqWCs5MTh6S2ROWFFTR0JVTm9vSDBKQwpIVXFXQ2IwMnRQ
            UXF0ZVBLOGljem54b29xMkkreXh6Q3BTanhva1c5SFdJCi0tLSBuQXZMalZRbXBG
            Z1Y5YTAzdVJEM3ZwaEl0QlFJcmcvem96ajVZdFJiL2M0Co0Q9Vethd9UFxvtpmgO
            Monio2t4ZXASK7FQyia5Wp9R8Y+vyDSU8c+XMDqZDi2AvPxuJybtu3iMZw8IJ3Dc
            EGA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBNThXZmd1
            MFptMEpCazNoSnRFdEd3bWNFZjNydGh0cWluakcyK0kvNUxUZgpBNFZ2bTN0MDZ6
            R2NxQy9JWG8wQXc5d2ROWFdKUUFscGhWMWxubVY0NWtrCi0tLSBwT21QRFZtRjlq
            ZnkrdnhPV0ZleWlqT2lGaE5OOXFwcmNjRUhVQkNudVZNCoV7zX+HU1iII+8EgXL3
            n3WeJsytNxTXqwmOvCe1zb8qHFOZTPDLq8r/8+lQUu2A/ckMAnKN0UtZooExofvS
            bdc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T22:17:37Z"
    mac: ENC[AES256_GCM,data:8Ai5ZEX50LonS3EhYptDKMQ3Qp/2QgIEZXJYfy/kAkqToUBKp2jtBtjoGsbgmtrbmTWZVomP8jdQhCCiCgfaoB1BsvW2no06RFpKeClAb8Qzs5XBFlELORifoawSa6lgRo1iExbGpRcVzgE+ZmbB/d9Sc6QoLKIJrVabT5xq4Fg=,iv:2ncxU5MMAW5GnmNPx8TBH6VvlsPorqm589puWoFQot8=,tag:+dyB8db6d7m306OT/aFqKQ==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//d6CxLe94cS9zybXWh3CR8byb9PBGDC6qLK8SdHC4GWAx
            HxUsSEV0O/YrwoYJQfaMtEwMCwEY+U541zwwT71bA+ZWg1uJV2E6dzwXa1GPPf44
            1/KtH8idHJ75Zo4CUAV9cYxhVaHQluxRDtSMuiDmZd+KL0CdDKz7YdumIAhpcU+B
            GZdDWNUNgSQskkwYdhdpuhx6/q5p+gHSlHJ9mttQalTBDxZBozuosaxcIIFFYmC/
            ItWdg4o0dUGCRkaLtFb/c22GPXBJXA8S0Q4zSECm2oc1pZ2iC9/2ytEQ3A9wDOCF
            La3Li/bo83N+A7+VdaYxq5nxCE1XYVfR8BnTlWf5Kbe+TgIb5wHBgHC1UqCZzk1K
            cqJLNfvO4JP4en+x03V3FLJId8hEcLC0Vc++SfBVCDfPc0eCVhwkFQPkjB3zhTHS
            PLQXJd9Gt8aUiPXPqoMUtJ6xZMoXZ7nZAvrrPnCxB7sGXDhEAFZtoOIzOb2GAr5U
            XgNCbH7Q92tqrOEn/0Wy/oNHWP6h5H5h4cyhEs8mc1eDlbzim0NvJZ7i+P39NfXW
            gdQ4zOlWrqioRZPcq+ctLwyedkDxixE1FADSzEdb37qQGscpRLyCsSClqKtssc/E
            /58LJZ/CcaMsjEaH7+wCpxMAbEIiNw2o0W4dBVizL9CYKZ55chtRQZldjk0dBRXS
            XgGS5QxxBgBMqcRzIaDogN7t6ngFhjvohvgMNJT4vY9l+HUXAtXqmNgF0SwW0AlM
            wu+Wss6M/AiHH/6soUs3rn/5+LtGRR7zXue7ci11TlP1nRqgou0DLbM8+WUTLhM=
            =zXYD
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.1
