apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows
  namespace: argo-workflows
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-workflows
    namespace: argo-workflows
roleRef:
  kind: Role
  name: argo-workflows
  apiGroup: rbac.authorization.k8s.io
