apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: flood
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/instance: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
        app.kubernetes.io/instance: qbittorrent
    spec:
      tolerations:
        - key: emnt.dev/on-nas
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: emnt.dev/on-nas
                    operator: Exists
      hostname: qbittorrent
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false # FIXME: Linuxserver images require root for init
      initContainers:
        - name: gluetun
          # TODO: Return back to a tagged version when >v3.41.1 gets released
          image: docker.io/qmcgaw/gluetun:latest
          restartPolicy: Always
          securityContext:
            capabilities:
              allowPrivilegeEscalation: false
              drop:
                - ALL
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
              squat.ai/tun: 1
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - case "$(wget -q -O /dev/stdout https://airvpn.org/api/whatismyip/ | grep airvpn)" in *'true'*) exit 0;; *) exit 1;; esac
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp/gluetun
              name: gluetun-tmp
          env:
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: ${v="${TORRENT_PORT}"}
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8"
            - name: VERSION_INFORMATION
              value: "off"
            - name: VPN_SERVICE_PROVIDER
              value: airvpn
            - name: VPN_TYPE
              value: wireguard
            - name: SERVER_COUNTRIES
              value: Canada
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: airvpn-creds
                  key: privateKey
            - name: WIREGUARD_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: airvpn-creds
                  key: presharedKey
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: airvpn-creds
                  key: addresses
        - name: mousehole
          image: docker.io/tmmrtn/mousehole:0.2.0
          restartPolicy: Always
          volumeMounts:
            - mountPath: /srv/mousehole
              name: mam-cookie
      containers:
        - name: qbittorrent
          image: docker.io/linuxserver/qbittorrent:20.04.1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: TORRENTING_PORT
              value: ${v="${TORRENT_PORT}"}
          volumeMounts:
            - name: qbittorrent-data
              mountPath: /config
            - name: multimedia
              mountPath: /multimedia
      volumes:
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: qbittorrent
        - name: multimedia
          persistentVolumeClaim:
            claimName: multimedia
        - name: mam-cookie
          persistentVolumeClaim:
            claimName: mam-cookie
        - name: gluetun-tmp
          emptyDir: {}
