# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: gluetun-apikey
  namespace: flood
spec:
  length: 32
  allowRepeat: false
  noUpper: false
  encoding: base64
  secretKeys:
    - apiKey
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-apikey
  namespace: flood
spec:
  refreshPolicy: OnChange
  target:
    name: gluetun-apikey
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: gluetun-apikey
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-config
  namespace: flood
spec:
  secretStoreRef:
    kind: SecretStore
    name: flood-secrets
  target:
    name: gluetun-config
    template:
      engineVersion: v2
      data:
        config.toml: |-
          [[roles]]
          name = "gomplate"
          auth = "apikey"
          apikey = "{{ .apiKey }}"
          routes = ["GET /v1/publicip/ip", "GET /v1/portforward"]
  data:
    - secretKey: apiKey
      remoteRef:
        key: gluetun-apikey
        property: apiKey
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gomplate-config
  namespace: flood
spec:
  secretStoreRef:
    kind: SecretStore
    name: flood-secrets
  target:
    name: gomplate-config
    template:
      engineVersion: v2
      data:
        .gomplate.yaml: |-
          inputDir: /mnt/input
          outputDir: /mnt/output
          datasources:
            gluetun_ip:
              url: http://localhost:8000/v1/publicip/ip?type=application/json
              header:
                X-API-Key: ["{{ .apiKey }}"]
  data:
    - secretKey: apiKey
      remoteRef:
        key: gluetun-apikey
        property: apiKey
