# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  config:
    server:
      root_url: https://grafana.${CLUSTER_DOMAIN}/
    auth:
      signout_redirect_url: https://authentik.${CLUSTER_DOMAIN}/application/o/grafana/end-session/
      disable_signout_menu: "true"
    auth.basic:
      enabled: "true"
    auth.generic_oauth:
      enabled: "true"
      auto_login: "true"
      name: authentik
      scopes: openid profile email
      auth_url: https://authentik.${CLUSTER_DOMAIN}/application/o/authorize/
      token_url: https://authentik.${CLUSTER_DOMAIN}/application/o/token/
      api_url: https://authentik.${CLUSTER_DOMAIN}/application/o/userinfo/
      role_attribute_path: "contains(groups[*], 'authentik Admins') && 'Admin' || 'Viewer'"
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: secrets
              env:
                # Need to explicitly set those here, otherwise operator can't log in
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: secrets
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: secrets
              image: docker.io/grafana/grafana:11.6.15
  ingress:
    metadata:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    spec:
      ingressClassName: ingress-external-traefik
      rules:
        - host: grafana.${CLUSTER_DOMAIN}
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
