apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: grafana
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fBH98THWTRwRYOQSDsri5hkJwkBpdx101Ks3ePNkTtwGsw+gorwbDg==,iv:zdEJLmpbPVUOPLRadlccQ+bSUydp2dpFRnuqoUjqiKA=,tag:hlKdZuiQmixngAxOs8iVeQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+KCVM3Fn3QmMrXiwm3nUcnhddVDxMVPxYThroH9f90ugd8vvW16G62iS/TU2B1B23ZpsbYyGK1QtmT9D+LJRBfGKoIiBJQ8rklSTA4zVvsFJpZm9251ZmCBow3UWm0C69SYerQwNVPKuOIe/m61XpsAzrvXSMrUgqZUzEHDYDAk=,iv:sXNNerLr30Qt15riij+KiBkRfZawlLevxF2wGuijf54=,tag:AGUnBOU/IeVBa7WTf1NBfQ==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:3eEGgYs=,iv:i0hXyWE2WD1Vg14+9e3cnrZOu4VEY2D6Jem7U7PiI1c=,tag:rDFm4vB5aZ1shkug0KEwqg==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:SE3l/hrp3mHhyTvHreHF/ctJjapfnwksow==,iv:uU/XMl2B11L7SkAvxd4GaUGa1Hz4vQ/GmvmAQ+iHK1I=,tag:GTXFAENp0DP4F4yrAL+5AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZk5saTNQQmRuNDJ0TEJm
            RGlFcmh2R00raldJdmNFL3J0cEhDa1FxeGl3Cm5VNlpybFg3TE5XcW0rV042bWJk
            cmpOTmJlb3JSenhlSC9YRXh4T1RTZ00KLS0tIGV1KzNNOTl0dmw1RnZ6UGNLbTVN
            UWdYUGM4QW1PL3Z1VExHcnhWMHZ5ZzAKrkyXfxCYjH61htR1R4Tzw9TLgKXjofkW
            /yIN8TscX0GpZ58SDSfAi5rnnJehOvC4mzOI5oIwTrz597wEMjxEOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBMEsrN1pt
            cnY4U1ZucXBtU3RwSVV6VjlEeHA5ZGNlWmVOWXRXOGZyL3l0Rwp6NktSTGpqdVRS
            LzN0dG41WDZqQVN6VDZVeFJ3TW8zajdXdG1MUWFuOEt3Ci0tLSBJNm56eDhndlpG
            Y2VQRWNkSk5mSGlTeTQxcHJ1NUg1cVlCYzZIeUwzMWdnCnQWVu6uM6u0K1mEKGsA
            QfJ8/BFMGoWRPDD3R1WG/EnOR1lmXWR7CXI3V544UxOp3Ph0igjQwiZc0duJJT9j
            YqE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBOVR1Skpv
            U1l6TEZyUDBYYThsVnAwYVpScjFQSDhLeFUyS0NwSjdjbVYzdgp2R2xURkI1cUFC
            OG9UYVhDaU03ZUdTL0x5MXdpMk9XZzBKK1FQYlI5RW40Ci0tLSBZQzlyRXluNmpO
            Q3JLQjVyalM4SDhGOFBaRUFJVHpXdDVZbzUzZFN1U293CuBMXRkXqjSdO2xk8CKa
            LkwAe9wgTAtCR/WfdPAXPvWWBps0SnK1g5wWYVLu0LdcYGtSZ6jQDZ4rlRcUxuqX
            JNY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-21T23:59:42Z"
    mac: ENC[AES256_GCM,data:0WcykQxWi9V4+7JQzHpuw0kMiYP4CmiUbsLKZl/ghwHw7d6PB5rIR76hoYolXY7VY+YhTrFx/bzvWFgvCe5Qzwup8a3naA9TyiIXxhrmuegXIc43daq6atgeHFofprd3/dLOlCGDxYvsPA4ZP/YsjQeyq3mCCtuc565VultVdiQ=,iv:7XCQjt5LlwfY+pen71s8ZXcAOrco1JvfgpabxLZYFqU=,tag:DVQYpUI+meyAH3aen3YG8A==,type:str]
    pgp:
        - created_at: "2026-06-21T23:59:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+JdpVviJ2CateZEQKshaNwHBjbIdYkBSWFThuntiPS3ww
            hQi5SFEoNooOAutCAp+he40Hk7+vzqou8nahG3oOEMfUUVhO31ng94Gyk1hCvZ9l
            y29IHyJjEhuh8+8FA1zxHqMW7Ly2NhQE34mheibzKKaIg54nyVsO3c8UPy47OS93
            eXu/ELv3a/4JzPEAi1zFhFYTwf1RzZFb7tyiNPzg8LC4fL+PseahNa6DGaDfp2mz
            3whKfLxXRgRMQ3q+0lA4t3Qq5ir5YzEB3ZDUAeI+YE/Qak4NTEBoMiyfB8eljTy1
            81F24tbcXqYGay9/ftCOSKCHwdzRh09MvT0ZZOj+YRk4VqEJG6BUSqKZcW+gcRYP
            LWbOk6AUJxW5WRebjz32EwyLc+pSmc1LGMrFbdjWz+xlpM0HuHTQOv4yYEsSv/Mc
            aYsFo9ILk1f8xotTgblHPccCQG8FU9fiwqSdA6gegwR+vDNKproWM7y5xhRjj9Gp
            6FraCYj9tHYeZR6/b0ac9aW1nboo7p459QEI0UJLMhhXW5khU2AueAbfFgcuxTX8
            v3mCgslF1oBUKNp4XmryLdslci4UD104atzyn/mOoXM4ygoYdVtBhMzudPl3WMVq
            5/oAjuLUuW2h/Prw2A3nFjASmKgbJe8HsDRUqcLLMGldzFJ1J+kMaJPSMvXSSLnS
            XgEwdeQHsHZCHwbmDxabxXiHuJNBgDG7E38LVUl6XzxJ7enUqG93BO1f2jZkRl1b
            BjVai8hxDSHYlDNq0mZ5qrVsZKm6CaVoNShzBuQVrdhUbaX3+A/PWZP2IXttt8M=
            =O39e
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
