apiVersion: v1
kind: Secret
metadata:
    name: authentik-creds
    namespace: romm
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:9iTYL4dYOvUw+CvCwI4QgGeZyslCF7HvjL79G4W4VNQ4vARLrhpFtA==,iv:mjvnXkxSVdws3yh4yN08JohcGxCdx0jex2IWqqIBbrI=,tag:zGyIuCB1r+MUTDTASAY3vw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:4LKQjNSv+Rc3OHoaYAS7a7RUQG5ZBUzXY4zxB3AaNo9FTggqwMK+G2JifztymSlePjg4Q5Rn2EhFLCysBL7Z0aakYlMWP39qFQXhdhcck0bJ9VM35CWkzpm5q/0UbtxltY0wvK3UjuFvhOvIgsvb7VCljVqfLHG8BRBA9WJqTDY=,iv:AL7suQOlgddpEO1Z8vYnQjJXr1FXRT3DzjMusceErws=,tag:V3haM/R7ilDfZr45dsVryA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdEtYaHVLTVVRTm5UUk5j
            YTJGSEU4Y0NJM2xuSmNSczZqdEtPTkEvd1dZCktaalBBcnNsNXFEcXZYell2dDFF
            eWtkT0dtdmFERkVZM2FoRjFQZ1dIR0EKLS0tIFNNbWx0NUoxa2IvY20vcTYyak1T
            aFdHMFFNY2NiOTdEcExuczF4VTk1eGcKh1p7u2TFLH8TLlkEllXsE3780pqLLpJa
            ukYo7228mC6Q7qvNJEW9h+9HSqt9+vAwWRTUv3Doemp1SphPWQfMGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBc0Zqb1pM
            dTVoWUh6amlkbWVmbHQ4Q1Zlc1I2NzgrN3UrMlp3MlpseUxyawoxanFEV2p5Ukdz
            QVFwaXJlbjEyejZhSVpXUHFRdDFoVGVJMEk2N0tqc1dzCi0tLSBJb2U5M28yaEl5
            UFdLWlk2MEk5eVZuNG1QN0pvMmxKZWVPLzRRT1lmZGQ0Cs4UiqLxyE/jt92cgs4j
            NW4Kpb+ehOpMgvfBEBNlv2ZcT1br+nIALwpq23+H3YBrQqp6qAQ+eWbEgBLzYvxU
            gZc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBN2YxKzNW
            cUxQNVh3OXo1ZVJhUmN3WXFlK01QL1RLMzJNdkRuK2FCczhUMQpDVUZxaU5yL1dx
            b0NxSVhUUTRMOFYxVWFnT0FldFE1S05mNjMrQXNZdDNNCi0tLSB1Y2lzUnpTRmE3
            QXZONGlSelhLajZPdWFieVBIL041OWtiV0w4RVJuWDA4Cp/Eio5VEk2WMS71t4W7
            OpngDex5i7LLPPEqK0pET/EJ/uqBMsC7FYkcaHIpAiC56dFCD6l7qbIkMVjp/zlW
            /Bg=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T04:02:27Z"
    mac: ENC[AES256_GCM,data:CloD3NjB93CBkPoKNCQP83+ywDIPiLYrnSw2nM41H/Lz63iftEM+7qywG6szv0RxkeOhqvkaTej4uM+72JiiLDRDvAtbBLdV6vLOr1mNtRYh8byzBa5qVsFRf79yWVZ0u7meIobT0fiOv2eBWd5lkqsc9ZcIUyYrlXmWuMMXbqQ=,iv:7K2Cx8Zq+6bGsqqOLf4ou8UtTunpTnINJKHPBe0X2Go=,tag:8IrBqAKQtWQDaBiX5nlsug==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+PknpvY5gK6rAIdcPdm2YihMh9hKUpOAoKMHJoyS8Xzrz
            4dKuStHdoQJQTY0lerkwDk4nyRuFfrfR5F1wLl1gREiGMdGics4e698ezCpX++J5
            NbBaZI7pCpUTF802iZcUyfW9xcViYQjXkC42BvmQFSyu++7rGuamQu4PXTBF5X2V
            a2w6fvxdLqbaqyyjptWDKyLt+bI4ZLcK8SBaKjvulhbtrDkz53FWvjGHAzFDwW0G
            O4UqWp8jLl14TEfHxbDfg7T7c6duEJW6/pVp2iW+uOPRtiyuTEob2w+pnw0DDBC8
            QsonYeOLMH3jubrns2cf4sPsN8QeBduh1QypGHEbFHWI73IylCuVMVh3yKX/cgac
            ubY2UqnrdW8O/hQHl/94DPsO3zqufcinI+dFyZz0+gzIboXc4q+gwKUW4zc7Kkfv
            4QH4Iu8ql+6DzBfymhNosAM7/uQb46Gzap6ePoWRRhvD9NgIUYunpRvCEZF87Cnp
            XsqsJs7j2ZvxmqoP4iGoR2Z2HE8fHX4gYrCflz0MKvAv0nZ+2gtS9ONTJ6eZ1BcN
            bVQ7fSjdhb8LtJPDPOFwRNfXLgahANwJyVQcvnexhdvEsIl8fou7bb7BdS0XXpYF
            RCrQ9R8gsQX3Ng5yT6+VnH15WiyPZxwiP5i26ml5K2j+tmUFK5rrzRXGv8yKJjnS
            XgGWA5J/V3/Jiiiw7gAaBkS2yt7ge+0CUffrkK6V2SwUAC4dkIBPv9Zh9k9q+7j2
            uqFDBZMxZGnSuX483iGXnB2H24sehlhBIj9+pbLjD35QvlnAgN1NH1Ii3ARjalM=
            =dOpU
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.1
