# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: auth-secret
  namespace: romm
spec:
  length: 32
  allowRepeat: false
  noUpper: false
  encoding: hex
  secretKeys:
    - ROMM_AUTH_SECRET_KEY
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: romm
spec:
  refreshPolicy: OnChange
  target:
    name: auth-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: auth-secret
