apiVersion: v1
kind: Secret
metadata:
    name: igdb-creds
    namespace: romm
stringData:
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:xDT2b+do9xSFIATc/OAP3hqybPg5HXfQskslNkAz,iv:5UXQKiHN3zhywIP5X8IyIrXQLM6p45Gb2mHmeLJoMlc=,tag:vyc3UGbrrAQkAdnCQuXBPQ==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:WmGajIF9lNinlfveS2saK1pO+Lp/xjUj2zGqdhaz,iv:eUBhECdLHtC+SzVB3ED1cb7tbs7rpLV9P7wQw15vMAk=,tag:A7XgNZZWP+jOr54d59xJWw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYkJLSEFxaThHYnZQZXBW
            b2pBR1I3RnNFU0h4b3F4bU5WZlZGcXJOaFdBCjRFbUw4YnNyWkVlU3RUZVdYN3gx
            Zi9iRUlPNnZnMW5lQ3ZhanE2QXZKRTAKLS0tIEhOcnQwMk5adFN3UkpVaENRdDY2
            SzlGelpQTDE2SDlIbUVvc3NrcnFRWkUKVLeHorODeyu0foxE5msEyY4/K0yFODue
            ru/jOmMe5axODkG1nBMMe5PeeuukBaRaFfg7WQLLfQedIxAlVicQgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBMUNqLzl5
            VnBtTy9GcHR0NXIwaC8rMjR3RjdYZkhlc1JibzQ5cmZuVmgvNwpDUm9yNnV4U3hZ
            VW12MThzbUM4Y0E3U2FVL0NoTFJKSlZUNGdDUjdmeSswCi0tLSBkVXRWaTBUb3RI
            S1JzZm5DWExVblRSRWkxZ1h5MmRiWnBWVW1LaDVDcThFCm1msa6krRMaCZNdoYJc
            agS2n5wOVUWt/BRjLCPC+UR9VCp2nXUFHR1IgeEBf5EPjaPOwLh9vTFT2QPIWDAx
            d9g=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBbjZJcUVj
            RnBHYks0dVRuVVYreDArNDJ0bFZBdG5nM1NzMk9VS1p2dXpCagpYZ01QNkZHR3B5
            c3Z4ZkFNcUNmd2dLTk1LeFQxZFVCbGtNWkN4ZFVwZ3JvCi0tLSBmallkczlXeGt4
            MWJjdkVndFdGWU15T083R29pTTg3WG16TldOY1kxZzZrCs/03DrW6ghLrcCzYi5B
            0LBmKhLuAofEo7In1/EJue1fEjYlYVS6fZ+ukGqQE5Kghxx2FziXjUxeEtM1udOX
            xYc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T03:01:58Z"
    mac: ENC[AES256_GCM,data:1Uw7ymhoLpBFPlpPgh0YaZsmLVobgL8tdzXLmo97ExMjjnLVGbUAGXmNzxcFaIdVyvyjG47L3ncipGQovvLuYw3sbAYI1vH5hD0MOa4YL2GzYSjAud1kOYSG0LV6828PtT2bPrJ7+qmDraEbD+tRiMRwAkgPihRTkux2yQ46Qzs=,iv:NzRPorTOwOMwWwSQ6wao2Rc1P7z3nPedbG+t1l0DueE=,tag:+yz4L7ExwZ3ZQxXC12UJUg==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+OI/gOwT2slnr+V1h/pxSuJR4jzWo+KN2JYxwcbPY92JU
            bpc87EArdZdJxDPvUlLf7sVDwH0/EcXK0ceswH+GOFp+nMLicoCmdOK/bTnjEzdu
            5Vk9+24AmOwlWECIY9tK3EXKRZB/OtCOcaxFxgRIsqU1B2MogamJ7tMAtCeWY7vI
            04NGmLBjWbs3QEYUGhLimB7Od5AESI+vuy0csQSNMIrnKVmptzLSLA7HCAXL+klF
            eUXkGUdj2zBSeVGimUo3guK0xlAd9EVE+dxtAeQdCOEMPHNtl6RZmu7+j5dyvuga
            IjNHOkWuR/J47625gR91R7wFh5aspcuIbEoVJu4qRyWSdhI+PnmtWtearGI7S8gC
            5MFeInnE9qiseZn+szKdMv1ULXS2rweGfxAAfbVe7WaBTX24c666a/nibTZEdoZA
            qU3PFF8hQigJSMjWL/Dtx8U3lc0Dqj7Y46fXvCK8B8MpmyD6hN7iTXj/JtVeKdQZ
            AJx82Omestlkpe5CXi6AxMUAOO/nU83pMuHwFhbi1ZOOgAAzuXj87EiZs0FhyqU2
            qyj0h4aogboYZ05X4TkbGXJ7gHmMsGjtR56KZUVxTah4kQBDV0vMsTUoL8lQ1zdX
            v9EhFaaeQ7f0H33guPPuDmJoXg0nxUGZIpmFgeLtEG1hSqKd0Q/uPh6lAzcKA9HS
            XgFg4AMpkuvhf/FrHFdCk0Jj+l0rgzKOCMniVKKVuPfot+vIEWR0UhPJAIcKR8M5
            LUSOShfeaUXmgg7/uP41evcikXqyjEmNvVS2s1837xwkmw8z1QJGB6iLiyw7qy8=
            =1F3F
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: steamgriddb-creds
    namespace: romm
stringData:
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:vo0Ru+6v7cb4Z4tsp8kUt+3o8B2ZoncbRE9PtVgRy0Q=,iv:92rrlYec4yKhMIzWZC0lnfuUNv6d5pAHLxgDP9ak+H8=,tag:MbxxTLwGptzu3b4pK5/s1w==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYkJLSEFxaThHYnZQZXBW
            b2pBR1I3RnNFU0h4b3F4bU5WZlZGcXJOaFdBCjRFbUw4YnNyWkVlU3RUZVdYN3gx
            Zi9iRUlPNnZnMW5lQ3ZhanE2QXZKRTAKLS0tIEhOcnQwMk5adFN3UkpVaENRdDY2
            SzlGelpQTDE2SDlIbUVvc3NrcnFRWkUKVLeHorODeyu0foxE5msEyY4/K0yFODue
            ru/jOmMe5axODkG1nBMMe5PeeuukBaRaFfg7WQLLfQedIxAlVicQgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBMUNqLzl5
            VnBtTy9GcHR0NXIwaC8rMjR3RjdYZkhlc1JibzQ5cmZuVmgvNwpDUm9yNnV4U3hZ
            VW12MThzbUM4Y0E3U2FVL0NoTFJKSlZUNGdDUjdmeSswCi0tLSBkVXRWaTBUb3RI
            S1JzZm5DWExVblRSRWkxZ1h5MmRiWnBWVW1LaDVDcThFCm1msa6krRMaCZNdoYJc
            agS2n5wOVUWt/BRjLCPC+UR9VCp2nXUFHR1IgeEBf5EPjaPOwLh9vTFT2QPIWDAx
            d9g=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBbjZJcUVj
            RnBHYks0dVRuVVYreDArNDJ0bFZBdG5nM1NzMk9VS1p2dXpCagpYZ01QNkZHR3B5
            c3Z4ZkFNcUNmd2dLTk1LeFQxZFVCbGtNWkN4ZFVwZ3JvCi0tLSBmallkczlXeGt4
            MWJjdkVndFdGWU15T083R29pTTg3WG16TldOY1kxZzZrCs/03DrW6ghLrcCzYi5B
            0LBmKhLuAofEo7In1/EJue1fEjYlYVS6fZ+ukGqQE5Kghxx2FziXjUxeEtM1udOX
            xYc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T03:01:58Z"
    mac: ENC[AES256_GCM,data:1Uw7ymhoLpBFPlpPgh0YaZsmLVobgL8tdzXLmo97ExMjjnLVGbUAGXmNzxcFaIdVyvyjG47L3ncipGQovvLuYw3sbAYI1vH5hD0MOa4YL2GzYSjAud1kOYSG0LV6828PtT2bPrJ7+qmDraEbD+tRiMRwAkgPihRTkux2yQ46Qzs=,iv:NzRPorTOwOMwWwSQ6wao2Rc1P7z3nPedbG+t1l0DueE=,tag:+yz4L7ExwZ3ZQxXC12UJUg==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+OI/gOwT2slnr+V1h/pxSuJR4jzWo+KN2JYxwcbPY92JU
            bpc87EArdZdJxDPvUlLf7sVDwH0/EcXK0ceswH+GOFp+nMLicoCmdOK/bTnjEzdu
            5Vk9+24AmOwlWECIY9tK3EXKRZB/OtCOcaxFxgRIsqU1B2MogamJ7tMAtCeWY7vI
            04NGmLBjWbs3QEYUGhLimB7Od5AESI+vuy0csQSNMIrnKVmptzLSLA7HCAXL+klF
            eUXkGUdj2zBSeVGimUo3guK0xlAd9EVE+dxtAeQdCOEMPHNtl6RZmu7+j5dyvuga
            IjNHOkWuR/J47625gR91R7wFh5aspcuIbEoVJu4qRyWSdhI+PnmtWtearGI7S8gC
            5MFeInnE9qiseZn+szKdMv1ULXS2rweGfxAAfbVe7WaBTX24c666a/nibTZEdoZA
            qU3PFF8hQigJSMjWL/Dtx8U3lc0Dqj7Y46fXvCK8B8MpmyD6hN7iTXj/JtVeKdQZ
            AJx82Omestlkpe5CXi6AxMUAOO/nU83pMuHwFhbi1ZOOgAAzuXj87EiZs0FhyqU2
            qyj0h4aogboYZ05X4TkbGXJ7gHmMsGjtR56KZUVxTah4kQBDV0vMsTUoL8lQ1zdX
            v9EhFaaeQ7f0H33guPPuDmJoXg0nxUGZIpmFgeLtEG1hSqKd0Q/uPh6lAzcKA9HS
            XgFg4AMpkuvhf/FrHFdCk0Jj+l0rgzKOCMniVKKVuPfot+vIEWR0UhPJAIcKR8M5
            LUSOShfeaUXmgg7/uP41evcikXqyjEmNvVS2s1837xwkmw8z1QJGB6iLiyw7qy8=
            =1F3F
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: retroachievements-creds
    namespace: romm
stringData:
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:YpepbQiqks4l6qLp6AwQP7/hWxCGYVZmZv5LttYGc/M=,iv:uy2WV4d9gV50PG+q8IyjlwLIqzZuIcTOgVDhN2pvB/g=,tag:WO3ZQ0UE3LxFon01vEePWw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYkJLSEFxaThHYnZQZXBW
            b2pBR1I3RnNFU0h4b3F4bU5WZlZGcXJOaFdBCjRFbUw4YnNyWkVlU3RUZVdYN3gx
            Zi9iRUlPNnZnMW5lQ3ZhanE2QXZKRTAKLS0tIEhOcnQwMk5adFN3UkpVaENRdDY2
            SzlGelpQTDE2SDlIbUVvc3NrcnFRWkUKVLeHorODeyu0foxE5msEyY4/K0yFODue
            ru/jOmMe5axODkG1nBMMe5PeeuukBaRaFfg7WQLLfQedIxAlVicQgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBMUNqLzl5
            VnBtTy9GcHR0NXIwaC8rMjR3RjdYZkhlc1JibzQ5cmZuVmgvNwpDUm9yNnV4U3hZ
            VW12MThzbUM4Y0E3U2FVL0NoTFJKSlZUNGdDUjdmeSswCi0tLSBkVXRWaTBUb3RI
            S1JzZm5DWExVblRSRWkxZ1h5MmRiWnBWVW1LaDVDcThFCm1msa6krRMaCZNdoYJc
            agS2n5wOVUWt/BRjLCPC+UR9VCp2nXUFHR1IgeEBf5EPjaPOwLh9vTFT2QPIWDAx
            d9g=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBbjZJcUVj
            RnBHYks0dVRuVVYreDArNDJ0bFZBdG5nM1NzMk9VS1p2dXpCagpYZ01QNkZHR3B5
            c3Z4ZkFNcUNmd2dLTk1LeFQxZFVCbGtNWkN4ZFVwZ3JvCi0tLSBmallkczlXeGt4
            MWJjdkVndFdGWU15T083R29pTTg3WG16TldOY1kxZzZrCs/03DrW6ghLrcCzYi5B
            0LBmKhLuAofEo7In1/EJue1fEjYlYVS6fZ+ukGqQE5Kghxx2FziXjUxeEtM1udOX
            xYc=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T03:01:58Z"
    mac: ENC[AES256_GCM,data:1Uw7ymhoLpBFPlpPgh0YaZsmLVobgL8tdzXLmo97ExMjjnLVGbUAGXmNzxcFaIdVyvyjG47L3ncipGQovvLuYw3sbAYI1vH5hD0MOa4YL2GzYSjAud1kOYSG0LV6828PtT2bPrJ7+qmDraEbD+tRiMRwAkgPihRTkux2yQ46Qzs=,iv:NzRPorTOwOMwWwSQ6wao2Rc1P7z3nPedbG+t1l0DueE=,tag:+yz4L7ExwZ3ZQxXC12UJUg==,type:str]
    pgp:
        - created_at: "2026-03-30T23:26:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+OI/gOwT2slnr+V1h/pxSuJR4jzWo+KN2JYxwcbPY92JU
            bpc87EArdZdJxDPvUlLf7sVDwH0/EcXK0ceswH+GOFp+nMLicoCmdOK/bTnjEzdu
            5Vk9+24AmOwlWECIY9tK3EXKRZB/OtCOcaxFxgRIsqU1B2MogamJ7tMAtCeWY7vI
            04NGmLBjWbs3QEYUGhLimB7Od5AESI+vuy0csQSNMIrnKVmptzLSLA7HCAXL+klF
            eUXkGUdj2zBSeVGimUo3guK0xlAd9EVE+dxtAeQdCOEMPHNtl6RZmu7+j5dyvuga
            IjNHOkWuR/J47625gR91R7wFh5aspcuIbEoVJu4qRyWSdhI+PnmtWtearGI7S8gC
            5MFeInnE9qiseZn+szKdMv1ULXS2rweGfxAAfbVe7WaBTX24c666a/nibTZEdoZA
            qU3PFF8hQigJSMjWL/Dtx8U3lc0Dqj7Y46fXvCK8B8MpmyD6hN7iTXj/JtVeKdQZ
            AJx82Omestlkpe5CXi6AxMUAOO/nU83pMuHwFhbi1ZOOgAAzuXj87EiZs0FhyqU2
            qyj0h4aogboYZ05X4TkbGXJ7gHmMsGjtR56KZUVxTah4kQBDV0vMsTUoL8lQ1zdX
            v9EhFaaeQ7f0H33guPPuDmJoXg0nxUGZIpmFgeLtEG1hSqKd0Q/uPh6lAzcKA9HS
            XgFg4AMpkuvhf/FrHFdCk0Jj+l0rgzKOCMniVKKVuPfot+vIEWR0UhPJAIcKR8M5
            LUSOShfeaUXmgg7/uP41evcikXqyjEmNvVS2s1837xwkmw8z1QJGB6iLiyw7qy8=
            =1F3F
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.12.1
