apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: romm
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: freenas-api-iscsi-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets
  namespace: romm
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-api-iscsi-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources
  namespace: romm
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-api-iscsi-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: romm
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: freenas-api-iscsi-csi
