apiVersion: v1
kind: Secret
metadata:
    name: nix-containers-forgejo-creds
    namespace: argo-workflows
stringData:
    creds: ENC[AES256_GCM,data:DOH5+GicTTvHEt1GvGWeqLHepaSyzxOE0q2Ll7o/uKbjoi35pgJnaRKmktAZAnDoRqMZeMiOsQ==,iv:LteCU46p3JrZ9qK45oqB3kDbZH4Nk5UfCDoWgo9KTLw=,tag:SdkRsSKXtFUMdoj5ympW0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcmgrUXRqNWQySVZua2I1
            OGF5TDZTT3JJcnRESTBQOUtnenVNWG14VTAwCkl5MHJoUUJvMmtZUjJaVEVBZDRY
            NlRkUGFicGptK0NNbU5sODkrdWsxZFUKLS0tIE54aXVTQit0amFwM3FXaGY1S1pI
            TC9YdmlwUGQ1UytVOEZoMlZrbWNaWmMK4MvHXp6ZvaSmDVMrCcg+FMROtUIEWZ+F
            Rsq7TypaoAd2PusH4SqC0P/urtvJgZ6AqdgMv7artz5WVBYZHQGBiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBOGtBRUxn
            WXBZWit5YVJvUEFwY3g2Y2ZUaTZ4RjdEUjlMQUhpdVM4TCswagp6Vld4cHBzN1dl
            ZkVxaGp5cUVmbS9JME8rMjZMNXJUN1hSTGd5NHkrNFVJCi0tLSBUV0w5Tk5vU3pU
            RnVUN1FPcG1PK056WFl3cUZ0bnhRbWVGNmJZb05QdlFVCiQmVdR9zgXV51JG00/a
            RZVNt5vYPudzaliwqAtMj49ycwgrmClseCtReeXR7YwTtyjE6ZqXt+4ZPQcJ8Prh
            Bso=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBbThmM1RH
            SHJMbWQ3NXY0L0pzUGxFdVdLRDZLR29GTGgzSW1mNkRreWdGKwpQU3ZyMzJad3Z6
            R2ZqdGw2SUwxZWQ1YjhpWEpGUzczWEhnZVJmWENUcXE0Ci0tLSBORUlsU1QzWCtp
            eXFxY0l4UEM3YW5Ea1RybWpQMU1wbk4rSGJyTjVIdklVCtoKXYzYJr7QVrlXjYB4
            9QMjY/wMbVYRhx1QmMilGZ11ZCe/CyJ6IIZLG36Pr8U63I15AM9Ffq7yPC26XbnR
            J5E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-05-25T21:57:11Z"
    mac: ENC[AES256_GCM,data:cJ/OdgLV4ldYoqEkNeQiSLV9KP2t5lSOGmuZy4OwBagKh5eTzcDY2fEJJRclbGNmIb11FoOOVotnIW31wA5rDoe+w64j9QfFb1p5Pzs0lOu/CZIhIidg10T23gvNd1HaUKWF2hWP6FP1lbSuyaScNgaQ2keVrpWXPN/xrG4Vjhs=,iv:JOcDBRe54nRHc99lHez5StPIuE3i1OzMpx0OwfHKTrw=,tag:lk0PVxt9GI5tOmsL5Xu7sA==,type:str]
    pgp:
        - created_at: "2026-05-25T21:57:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAnRXriW1hl8z8Fgf8ffge2YRGVwsNNYf8CGglKscXVbA8
            KTINCy15Mt5whIaN9zTN9MVWZN9DsvvP4chy1fgYqpdFb5cLr0QSG5AKZHa9t7lc
            vqg3xupRikyDHpMHqOBPfFh9ztoFX9Hn62Q6NjaTtse3C41Mc1JKKpGXWsdLYU9j
            GHVIoLvRcq4ymUami0/cnG0bQg2wfuEQHb63u50Y/t8+KxE+f+fpaifKAYtDvqi7
            C//kq1TPuTOPfOBAlxMud1jositlYU6e3e8VkHoeql71OA3wWjW1WDzFhg2M8R88
            sScUhCSUlc9Kp5se07FJGyRsnd4YpLBAZgTrB0ebhh1VSJHTB11vrxHeRQwnzvFE
            otf1dVqs1uTLP3c+1LmZ7g3sFAuDeSs67S8F3zqUo3oRKCA3i8/biezE2o4YymR5
            mhBl5dR7aTN5tKOimXZbcA7WoaOIB/3JqivJ62GhmCMnGWi6tG/smboKZdyjWa2t
            0wAnQYGqWMNe5v22Au4yFxtjR53Xjm4Bo4llsQt6BoeJtp/48CCT9/BL0iMdOXCn
            RLmSUjHJ3YicRcCj0/l6FrM3D+COYB9dXekT6H0eSOaV9MYGs+D3qLr4+T7scyEE
            ssvoQHJe0VxMEynwIsrDcbzzysaC/Q5J5gdav+gafJJ6MlocUG4O3ejpfHdumDvS
            XAE5c0U8K/5XZrEObdo8AfYi90ZukBtGPM9E6uGjbBPgt3yrZvQK+mIUmunFFmBV
            ji9fwebnfShC8jS9qG0CH2BlKvBkKFag84ZVkaLS+Z8e88npeB45sbocb596
            =g3u+
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.0
