apiVersion: v1
kind: Secret
metadata:
    name: affine-secrets
    namespace: affine
stringData:
    MAILER_PASSWORD: ENC[AES256_GCM,data:hzQJncpAIhGGdfqYfs1XBpyoy6IuOMZK1Cf408UZGvWSC9oiI0FON60R69FprUVu/SoQnbh9av53us63,iv:sz7VLvBJ2YMCzDdPoDVHM2v5ANs9iNAZqFtG/Yih0Gs=,tag:TK+7XdfUcDD6T0MdWR0edg==,type:str]
    OAUTH_OIDC_CLIENT_ID: ENC[AES256_GCM,data:xc7p8M4jWSot/1bf7ElVPyZkpuVR4xBQ0S6VqV2TwYZKGjGSclwyJg==,iv:pZZLDYD7W857PFh+UqKi4qxkExefNJf6+KQKSTQI/wE=,tag:SK2Gl1U6tL65y8avQmGHrg==,type:str]
    OAUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5vxhk2GsWdi4Tv1HmR/NlHAUp+3UFVOMi8I6+Pbg8HRkzhWGgF/7237VcsdQRYreiINHkZMGl8FYFUHW6qh8z9/xOz4cJ54Uoe+bnE+INef39X6v76nuF1fG+EibFRbIIbQuU2ABBb/khmCVXWCj3U21+iXFWALZJachn0qlu6c=,iv:sBBw2j+LX2Ds5nsegjOSp1WhM4/o51fP/nlpmzGNdwk=,tag:iQ7RBksM+lDBYHxCmdCeDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UUQ0ajh4UnI2eXVnT1Aw
            UW1DOXArVW9NMTVXUU1uQk5YU2hBN0s0RGlNCjE0T01XZWlidWcxS2lmaC9vaGkw
            WmNuYy9laEFlbzdFblkvd0ZFT2JGSkkKLS0tIEY1RzAzTFJLdS9TRmJRZFR5M244
            YW54SUZaTUVBT3B3Mk55UGVxWFBRWTgKUnJ8U1k+6t1MFG9XdccymEzveYGNS98Z
            vBTchHlhWeCIcDvhspsUiHeLCOxu/rlxj2gYTb5ODz65EaxyPC0exg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBbTZiM0Nz
            MTJzenVpOGo1UXBkWk5pWjNDZnpDaVFGcXZVL3pxU2RaWHpzUApvTzN1UjU0azha
            cG5XZGVpZWxJZE54SlNoMUpMNkxweFI4dXFGMUVFWllFCi0tLSBra2tVWXc5R1NJ
            V0pSSmlNN0RidHRQTGZqSDFmSDVqa2cwOVR5TmlGNVBFCtI54GHJtX9+LkWuRgC1
            sjwMjDOQG+ZmDOu6/aeCzTK+Z38BL2TrxU0FMWWBRdw65TYLXJxtFGd5xrcD+ojU
            BnA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBMHpTVjJk
            V2MvK3pXcDJZTFgyQUh6dDJNSUZscGJrZ0dYY2E5SHNOQWVsaQpFWG1Fbit3dmI3
            ZXByaEh2cmJqZmlVRXA2WlVMVWVLS2FKWG9EWU9nUFk0Ci0tLSBuWUE0dUZMOGRQ
            SkZ2WEpSL010Tk9YR2x5S1JncklGZUNReGtFUlF2SmMwCm6RtKKWc9i+tmI+39d7
            T0DQZOfMZHDkXiGtyYESXws6oZNenBluqd66LzV5RCxkQ4qxsGgMLTEnTo/hw4Fa
            0Ss=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-15T01:23:11Z"
    mac: ENC[AES256_GCM,data:v4Od1xZczWGtHeFDjU+PuzlGRPh8Eo/G6LMFb+AaYpLCek0Mc/n/OMmCtmrleu2nAOcbBpkZX+iw6hlhxLuwoU8TnpDEkGW/copp0WtYhBOCkDtSkpPc0z2ZvRv5Qp1+ETwmdlvDmrjON0T8dn2uIxvZDV4SwZh0gBh+QyC8+yw=,iv:xrQ/UC4K584BemjEYNM6rf2+hhvVO0SK1rI0eI7ZNw8=,tag:guiM47MB0hJZWWdCKBG9lw==,type:str]
    pgp:
        - created_at: "2026-06-15T01:23:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAtuXCzumV6CCiEltOX0LV4xNlkycou/txr/qDa6s8eaii
            qZyJ9WdCZV+z19RCVL3YWvnMxj4ogdZnlH0YYSJhTx42pQan96Wtejro72mou9k5
            n5dwx00LiUHrZtrzTYt3BMIf6OL6osOwNMagI2jdWof9hx1GovoFUphHLJNkucee
            Kr0jvagTGZJYDD1hQN1Lk+k6rxmf4Hc/Nu8caCFbOTnxJDRMsdarDF/WlufD7kVS
            CpaeVpMA7ee7n6JmbSWYvuP518ryf9AVQ5DdD5hwJ71fsf4xEInQZRb2epdeBCF9
            Mi7q6HWArX8xRh1Kf608euFD7AP/uFvoWUJ6UAP2EpGoGWmrkb4pTMRxwxOu5nkv
            lZEJ0Ms+hDDWUsuNbWIJdGFBqYEwqcyRbihIK6YungjE9PFFaRBMu8GPKfAgtko0
            wR1qeX0cJ26WbyEECefz6oGwDjc6JMSwJkXFAn12JuVyHu+yqDWIJU2WbNkI1tJg
            F7gOh2naDGNiSvj0fVxmL6Y1rVAFdHFfjWAKb3PsQ9y46OzwMgRo23BotAZz82qj
            Vmo8O1/EBewNatWutXwW+XpHpPj2JpGcmdgy5Wv4ldRVGRq52JlK2jo9x0JxKL2w
            nQGlgJLyCp+59d16gtK9ruPfNCPeaB9hWwmJAX30lu9NyCcgfOIw6We4rNux92rS
            XgGEPEkJqOIluaZxMphjyu5VpXNxaNP3lD3fOD9yjvZC9sZdUf6liMcwDHrOHP7m
            3uXY0Nz8qrpNR2naTfEhsg6F2OdJTHwhcID6u09m2O7A5oaC3QDH2PQ7Jy/76hI=
            =tZmT
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keydb-creds
    namespace: affine
stringData:
    password: ENC[AES256_GCM,data:k07i1TI3OKop7nFhLs5FDjsQWBwyv4QZKESHBa+HcIQ=,iv:Jcr5MMGpAhwguyFFFqwwRA2AikmQQjYp/k/gvuOYt74=,tag:NhWDb9hTPthSIZ1/MospjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UUQ0ajh4UnI2eXVnT1Aw
            UW1DOXArVW9NMTVXUU1uQk5YU2hBN0s0RGlNCjE0T01XZWlidWcxS2lmaC9vaGkw
            WmNuYy9laEFlbzdFblkvd0ZFT2JGSkkKLS0tIEY1RzAzTFJLdS9TRmJRZFR5M244
            YW54SUZaTUVBT3B3Mk55UGVxWFBRWTgKUnJ8U1k+6t1MFG9XdccymEzveYGNS98Z
            vBTchHlhWeCIcDvhspsUiHeLCOxu/rlxj2gYTb5ODz65EaxyPC0exg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBbTZiM0Nz
            MTJzenVpOGo1UXBkWk5pWjNDZnpDaVFGcXZVL3pxU2RaWHpzUApvTzN1UjU0azha
            cG5XZGVpZWxJZE54SlNoMUpMNkxweFI4dXFGMUVFWllFCi0tLSBra2tVWXc5R1NJ
            V0pSSmlNN0RidHRQTGZqSDFmSDVqa2cwOVR5TmlGNVBFCtI54GHJtX9+LkWuRgC1
            sjwMjDOQG+ZmDOu6/aeCzTK+Z38BL2TrxU0FMWWBRdw65TYLXJxtFGd5xrcD+ojU
            BnA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBMHpTVjJk
            V2MvK3pXcDJZTFgyQUh6dDJNSUZscGJrZ0dYY2E5SHNOQWVsaQpFWG1Fbit3dmI3
            ZXByaEh2cmJqZmlVRXA2WlVMVWVLS2FKWG9EWU9nUFk0Ci0tLSBuWUE0dUZMOGRQ
            SkZ2WEpSL010Tk9YR2x5S1JncklGZUNReGtFUlF2SmMwCm6RtKKWc9i+tmI+39d7
            T0DQZOfMZHDkXiGtyYESXws6oZNenBluqd66LzV5RCxkQ4qxsGgMLTEnTo/hw4Fa
            0Ss=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    lastmodified: "2026-06-15T01:23:11Z"
    mac: ENC[AES256_GCM,data:v4Od1xZczWGtHeFDjU+PuzlGRPh8Eo/G6LMFb+AaYpLCek0Mc/n/OMmCtmrleu2nAOcbBpkZX+iw6hlhxLuwoU8TnpDEkGW/copp0WtYhBOCkDtSkpPc0z2ZvRv5Qp1+ETwmdlvDmrjON0T8dn2uIxvZDV4SwZh0gBh+QyC8+yw=,iv:xrQ/UC4K584BemjEYNM6rf2+hhvVO0SK1rI0eI7ZNw8=,tag:guiM47MB0hJZWWdCKBG9lw==,type:str]
    pgp:
        - created_at: "2026-06-15T01:23:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAtuXCzumV6CCiEltOX0LV4xNlkycou/txr/qDa6s8eaii
            qZyJ9WdCZV+z19RCVL3YWvnMxj4ogdZnlH0YYSJhTx42pQan96Wtejro72mou9k5
            n5dwx00LiUHrZtrzTYt3BMIf6OL6osOwNMagI2jdWof9hx1GovoFUphHLJNkucee
            Kr0jvagTGZJYDD1hQN1Lk+k6rxmf4Hc/Nu8caCFbOTnxJDRMsdarDF/WlufD7kVS
            CpaeVpMA7ee7n6JmbSWYvuP518ryf9AVQ5DdD5hwJ71fsf4xEInQZRb2epdeBCF9
            Mi7q6HWArX8xRh1Kf608euFD7AP/uFvoWUJ6UAP2EpGoGWmrkb4pTMRxwxOu5nkv
            lZEJ0Ms+hDDWUsuNbWIJdGFBqYEwqcyRbihIK6YungjE9PFFaRBMu8GPKfAgtko0
            wR1qeX0cJ26WbyEECefz6oGwDjc6JMSwJkXFAn12JuVyHu+yqDWIJU2WbNkI1tJg
            F7gOh2naDGNiSvj0fVxmL6Y1rVAFdHFfjWAKb3PsQ9y46OzwMgRo23BotAZz82qj
            Vmo8O1/EBewNatWutXwW+XpHpPj2JpGcmdgy5Wv4ldRVGRq52JlK2jo9x0JxKL2w
            nQGlgJLyCp+59d16gtK9ruPfNCPeaB9hWwmJAX30lu9NyCcgfOIw6We4rNux92rS
            XgGEPEkJqOIluaZxMphjyu5VpXNxaNP3lD3fOD9yjvZC9sZdUf6liMcwDHrOHP7m
            3uXY0Nz8qrpNR2naTfEhsg6F2OdJTHwhcID6u09m2O7A5oaC3QDH2PQ7Jy/76hI=
            =tZmT
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    version: 3.13.1
