apiVersion: v1
kind: Secret
metadata:
    name: affine-secrets
    namespace: affine
stringData:
    MAILER_PASSWORD: ENC[AES256_GCM,data:F1RFN0j+TZZ10Q5KEXVLtL3E79GeoslZgg==,iv:q72+esEtYt2nj5cO4ddSA0By695qfzegUGLehDPb45E=,tag:9P2YHl7pj3T+8bDcsvbbTQ==,type:str]
    OAUTH_OIDC_CLIENT_ID: ENC[AES256_GCM,data:7DrwK6T6QydXZrc+C8gNnM9Tn4F+vDq/K0OjqB0edIgXOUbgd5kTGw==,iv:FdT8KQmqcdh5Dh/QamPCyTholAYtn+PqE0BS8nru2xo=,tag:kHVZTDBVRMRtlo+HrpEXkQ==,type:str]
    OAUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:6I9TwVc1YHhjMg+MjexMfLNPxJehyJZ0u/3ZvTjv98GDb34mEJJML/j0YNpouCmsudrRimtxz78ZBT937h1AwxiL3K222sK1aFVnloMTs1Ih4rMq8PN5/hWAddnv2pPex8SYg/tZPq1UJ7OtaYyCAJJqXXJCcd3jt1cykum2y8w=,iv:UlovdS7TS3TYpaVig5YnOa+Ksn8idFC+iKZZVC60ZJk=,tag:9hd5hgoi9i1Ewlb7WH9BJA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK3QxQ1VsckVBSWs4ajhR
            REJQVjNDS2IyTEJUYmplZHVER1lUVjdtZWxVCmpoUXNqZTdnQnhIRk5Mai9Hd1F3
            WGRqM0lsSEMzMXk1VmFZR2R6aEFsVFkKLS0tIElCL2hTY054NjZUSENwbDBDSWlL
            STcvTkt6dzFReUdFa1hkS1lyQktKVDQKTzrXNfLsQD4dQCtPB0uqVJnkRQUgQpPE
            Zi17m+zMmfAtjJlsnM99t+cuNDISy+ykFCnF1MynOSu5quM1goefgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBN1dtZGZh
            eVRyVmx6VkNoakp1YXBFcnIxWk1tN2s3Z2VFa3JFak5rRzZKOQpnRmJacUJvQkg3
            ckdRc0hLUlJ2Kzg4aW81Y09wRVYrLzJhVml2L0VvNXE0Ci0tLSBFbVkyM1RIL2Ir
            enFTeFZ3UnIzWmR4OFJQeHp2RHFkVEQ4R200Y2kyU3hBCt7ttuKST7THay+GGskn
            wrVVhQgDuJP6sQZkIhZXjYegGVWPHVrzX3QTIzv/doojFabZzlhGFLJRamjfZrVJ
            gEQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBNWRBbkt0
            UUNCR1lMSUNjL1pINW4rTWZta1RJU3NQQXZuY3N2U1NDQVNUcApzcjhIWGxYbWVL
            VGVIZVVKaUYzZUs4VXZNemg5YTRGUmtSWHJKSTV0UDY4Ci0tLSArdllIVzZ3Z1hl
            UUVoSm4vemZkakpDZVlHYi9VNjdvK0NCMEtERDZsYTNBCmA8W4ikRV1sWxelCfuk
            k9nqMt6bXkUJs4V1XAuHumzxY5KtLwM+Goa13TFrw8kIxXQMw7FVcqSEG0kbP3xt
            dVU=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:56Z"
    mac: ENC[AES256_GCM,data:dH80Jzmf3nt9yvZMtGUDTEu03iL6yYTJx7At/3+nXQlahFGOwxkc5xUKJZmZdJ1q8tC6o3Yy2/BJU8kvHEpuxfrxKIGtePgdoYbDYPY2f+tEbKC1ys/uBpSCD5NlH/Y5Nfa1KyvU5BQnYIW2U+zYs8sLDTZNIMQVEHGVLSyH+10=,iv:sGQXkW1muMdGbBuAUhqsXRIQJbc/i624Z0AedpkKT0k=,tag:ukWv819ywzro7dekFYk67w==,type:str]
    pgp:
        - created_at: "2026-03-30T23:20:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAx/rA1+rU6o8Rp/32n9BC0kEKQ/H0w306yXmnHVqyAZxu
            QVAq6q2tkfOhyZYrbGtP4tRjT6grJrOS4LJmW7erg+rVTDZuOpf8n0oMqvIO6u7L
            QMUpD4u73XOo9S8z8wOU8TjCKn2lwsDgJJ0uUIK+fWuJe7uFdifgq1k+6fpZJgtZ
            kvEZUhafN8OFEvavj8q+VtfIsHjj0X4XcQ/o8xp3di4GcJfQXBcymYjFOQV2dzOj
            Y2e+H4c5psGGjHsdrsACEVkLW0vcLauxFvTvhp84fpOFzRVZzpBUw5YTdzcSbvla
            DUEi+slGpsMO+clvDDf32aGD0WLLI547znoL5DRvEBfyDh3uOB1M/tUEd2q08z4x
            zp4xNujLAB5okmcctTRJweELpOGfNgdirki5TIlKb4rLGymHfphZW2Z/yzAdNFoC
            uUofFrHGhNRrfLRQyKaRLW30ZK0cewwPQN349Zp4/I+O5NZANXRlcTWJtK3blriC
            jJY5f8vYG1+YI/j8uJgp0ePWwYSi4cjcrWVncyeSVKW4gz9cxk9RHpfbyfvGY3fL
            LNEhZiaHK+Amxr7vZiOMnMxC0hzFZ28eCcu5/0IjAVAMVV/pS0x6H4nymlo1cSGP
            xlSz7gQNS8E39Dej9Uk9xliNh79nlKR9iWKa4GScTNGGHWOB5OXRuaN9waA/S57S
            XgHRYm6NyvzOEh3yiX6/A+kYQONIHko2xCdrniBE4uhHSo36oxQL8qRAw9aKRLtT
            JqISGxiyDXH2Y7zeUGk4AnnPDRclyhgOPbyQEfCDsGcJvrnmxM03Ke2DwBRifcM=
            =Y4pQ
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keydb-creds
    namespace: affine
stringData:
    password: ENC[AES256_GCM,data:SOuR0p1g/YsxtimA2wvV4bAU3pcwHINyUGGUT+E44g4=,iv:AIATlWje3wna3ZAZR/7hgdglRjNxKeo58FZ2nV/dEPw=,tag:bP1/Tsyms7447IzKkKW2fw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK3QxQ1VsckVBSWs4ajhR
            REJQVjNDS2IyTEJUYmplZHVER1lUVjdtZWxVCmpoUXNqZTdnQnhIRk5Mai9Hd1F3
            WGRqM0lsSEMzMXk1VmFZR2R6aEFsVFkKLS0tIElCL2hTY054NjZUSENwbDBDSWlL
            STcvTkt6dzFReUdFa1hkS1lyQktKVDQKTzrXNfLsQD4dQCtPB0uqVJnkRQUgQpPE
            Zi17m+zMmfAtjJlsnM99t+cuNDISy+ykFCnF1MynOSu5quM1goefgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qg69ltc78unjzscxta280tvcn6dzanwx8vqgk22rlm04yvvkwmh922qs29a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEpPdE9aUSBBN1dtZGZh
            eVRyVmx6VkNoakp1YXBFcnIxWk1tN2s3Z2VFa3JFak5rRzZKOQpnRmJacUJvQkg3
            ckdRc0hLUlJ2Kzg4aW81Y09wRVYrLzJhVml2L0VvNXE0Ci0tLSBFbVkyM1RIL2Ir
            enFTeFZ3UnIzWmR4OFJQeHp2RHFkVEQ4R200Y2kyU3hBCt7ttuKST7THay+GGskn
            wrVVhQgDuJP6sQZkIhZXjYegGVWPHVrzX3QTIzv/doojFabZzlhGFLJRamjfZrVJ
            gEQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2rxawf5zugxah0lmfv59twj2n86gxqf5jksnf5vwu4axcx90crtqsfc74q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZOZldsdyBBNWRBbkt0
            UUNCR1lMSUNjL1pINW4rTWZta1RJU3NQQXZuY3N2U1NDQVNUcApzcjhIWGxYbWVL
            VGVIZVVKaUYzZUs4VXZNemg5YTRGUmtSWHJKSTV0UDY4Ci0tLSArdllIVzZ3Z1hl
            UUVoSm4vemZkakpDZVlHYi9VNjdvK0NCMEtERDZsYTNBCmA8W4ikRV1sWxelCfuk
            k9nqMt6bXkUJs4V1XAuHumzxY5KtLwM+Goa13TFrw8kIxXQMw7FVcqSEG0kbP3xt
            dVU=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-09T10:02:56Z"
    mac: ENC[AES256_GCM,data:dH80Jzmf3nt9yvZMtGUDTEu03iL6yYTJx7At/3+nXQlahFGOwxkc5xUKJZmZdJ1q8tC6o3Yy2/BJU8kvHEpuxfrxKIGtePgdoYbDYPY2f+tEbKC1ys/uBpSCD5NlH/Y5Nfa1KyvU5BQnYIW2U+zYs8sLDTZNIMQVEHGVLSyH+10=,iv:sGQXkW1muMdGbBuAUhqsXRIQJbc/i624Z0AedpkKT0k=,tag:ukWv819ywzro7dekFYk67w==,type:str]
    pgp:
        - created_at: "2026-03-30T23:20:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAx/rA1+rU6o8Rp/32n9BC0kEKQ/H0w306yXmnHVqyAZxu
            QVAq6q2tkfOhyZYrbGtP4tRjT6grJrOS4LJmW7erg+rVTDZuOpf8n0oMqvIO6u7L
            QMUpD4u73XOo9S8z8wOU8TjCKn2lwsDgJJ0uUIK+fWuJe7uFdifgq1k+6fpZJgtZ
            kvEZUhafN8OFEvavj8q+VtfIsHjj0X4XcQ/o8xp3di4GcJfQXBcymYjFOQV2dzOj
            Y2e+H4c5psGGjHsdrsACEVkLW0vcLauxFvTvhp84fpOFzRVZzpBUw5YTdzcSbvla
            DUEi+slGpsMO+clvDDf32aGD0WLLI547znoL5DRvEBfyDh3uOB1M/tUEd2q08z4x
            zp4xNujLAB5okmcctTRJweELpOGfNgdirki5TIlKb4rLGymHfphZW2Z/yzAdNFoC
            uUofFrHGhNRrfLRQyKaRLW30ZK0cewwPQN349Zp4/I+O5NZANXRlcTWJtK3blriC
            jJY5f8vYG1+YI/j8uJgp0ePWwYSi4cjcrWVncyeSVKW4gz9cxk9RHpfbyfvGY3fL
            LNEhZiaHK+Amxr7vZiOMnMxC0hzFZ28eCcu5/0IjAVAMVV/pS0x6H4nymlo1cSGP
            xlSz7gQNS8E39Dej9Uk9xliNh79nlKR9iWKa4GScTNGGHWOB5OXRuaN9waA/S57S
            XgHRYm6NyvzOEh3yiX6/A+kYQONIHko2xCdrniBE4uhHSo36oxQL8qRAw9aKRLtT
            JqISGxiyDXH2Y7zeUGk4AnnPDRclyhgOPbyQEfCDsGcJvrnmxM03Ke2DwBRifcM=
            =Y4pQ
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.10.2
